---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/9/20 18:57
---

-- 招募队友


local this = {}

function this:Recruit(roomId, roomType, crtCnt, allCnt, rankmin, rankmax)
    if self.lastTime ~= nil and Time.realtimeSinceStartup - self.lastTime < 15 then
        return
    end
    
    self.lastTime = Time.realtimeSinceStartup
    
    -- 招募
    Debug.Log(string.format("roomId = %s, roomType = %s, crtCnt = %d, allCnt = %d, rankmin = %s, rankmax = %s", roomId, tostring(roomType), crtCnt, allCnt, tostring(rankmin), tostring(rankmax)))
    local custom = {}
	custom.type = roomType
	custom.curNum = crtCnt
    custom.roomId = roomId
    custom.rankmin = rankmin
    custom.rankmax = rankmax
	ChatAPI.SendCustomMsg(custom);
    -- SendReq
    HUDTextShower.AddNormalTextEntity(502)
end

function this:GetCD()
    if self.lastTime == nil then return -1 end
    
    local time = Time.realtimeSinceStartup - self.lastTime
    if time < 15 then
        return 15 - time
    end
    
    return -1
end

RecruitData = this 
