"""Auto-generated battle payload decoders.

Generated by scripts/analysis/generate_battle_payload_decoders.py
Do not edit this file manually.
"""

from __future__ import annotations

BATTLE_PAYLOAD_DECODER_SCHEMA_VERSION = 1
BATTLE_PAYLOAD_DECODER_PAYLOAD_SHA256_16 = "14fe2f63fd98f62b"
BATTLE_PAYLOAD_DECODER_PACKET_CLASS_COUNT = 138
BATTLE_PAYLOAD_DECODER_SUPPORTED_COUNT = 137
BATTLE_PAYLOAD_DECODER_SOURCES = {
    "schema": "scripts/analysis/battle_registry_schema.json",
    "decompiled_global": "decompiled_cs/_global",
}

BATTLE_PAYLOAD_DECODER_HELPER_KEYS = ['read_battle_character_throw_rope',
 'read_battle_character_wall_space',
 'read_battle_jump_on',
 'read_battle_jump_over',
 'read_battle_leave_wall_space_by_window',
 'read_battle_pose',
 'read_battle_ray',
 'read_character_be_hurt_info',
 'read_client_info',
 'read_hit_mark_target',
 'read_lerp_data',
 'read_melee_attack_target',
 'read_one_bullet',
 'read_perform_data',
 'read_pose_delta',
 'read_quaternion',
 'read_scan_enemy_info',
 'read_throw_scene_tool_data',
 'read_transform',
 'read_transform_euler',
 'read_vector3']
BATTLE_PAYLOAD_DECODER_SUPPORTED_CLASSES = ['PktHeartBeat',
 'PktVersion',
 'ReqActiveTracker',
 'ReqAddRobot',
 'ReqArmorPackageInfo',
 'ReqBombBulletState',
 'ReqBombExplosive',
 'ReqBombGunFire',
 'ReqBuffInfo',
 'ReqCancelThrowGrenade',
 'ReqChangeBlockingBoardState',
 'ReqChangeReinforcedState',
 'ReqCharacterActionAimming',
 'ReqCharacterActionExplodeExplosive',
 'ReqCharacterActionHammerAttack',
 'ReqCharacterActionInstallTrapBomb',
 'ReqCharacterActionMeleeAttack',
 'ReqCharacterActionTakeOutPad',
 'ReqCharacterActionTilt',
 'ReqCharacterActionUninstallTrapBomb',
 'ReqCharacterChangePoseInWall',
 'ReqCharacterClimbLadder',
 'ReqCharacterGunFire',
 'ReqCharacterHammerAttack',
 'ReqCharacterInstallReinforced',
 'ReqCharacterIntoWallSpace',
 'ReqCharacterJumpOn',
 'ReqCharacterJumpOver',
 'ReqCharacterLeaveLadder',
 'ReqCharacterLeaveWallSpace',
 'ReqCharacterLeaveWallSpaceByWindow',
 'ReqCharacterLerpPos',
 'ReqCharacterMeleeAttack',
 'ReqCharacterOperateBlockingBoard',
 'ReqCharacterOperateExplosive',
 'ReqCharacterOperateShield',
 'ReqCharacterOperation',
 'ReqCharacterPose',
 'ReqCharacterState',
 'ReqCharacterThrowRope',
 'ReqClientCheatReport',
 'ReqCreatePlaceSceneTool',
 'ReqDestroyBlockingBoard',
 'ReqDestroySceneObject',
 'ReqDisturbedOperate',
 'ReqDropDefuser',
 'ReqDynamicWallInfo',
 'ReqElectricBoxInfo',
 'ReqEnterBattle',
 'ReqFoundBombTarget',
 'ReqFoundCriticalTarget',
 'ReqFoundDefuser',
 'ReqGameInfo',
 'ReqGamePlayerInfo',
 'ReqGamePoints',
 'ReqGenRobot',
 'ReqGetBackNeuroToxinOperator',
 'ReqGetBackNeuroToxinTool',
 'ReqGetBackPlaceSceneTool',
 'ReqGetBackPlaceSceneToolOperator',
 'ReqGrenadeBegin',
 'ReqGrenadeExplosivePosNtf',
 'ReqGrenadeExplosivePosReport',
 'ReqGroundMaterial',
 'ReqIntoSceneTool',
 'ReqItemPosReport',
 'ReqKillMe',
 'ReqLeaveBattle',
 'ReqLeaveSceneTool',
 'ReqLoadProgress',
 'ReqMonitorPoseDelta',
 'ReqMonitorScanEnemies',
 'ReqMountedLMGInfo',
 'ReqMoveToIntoSceneTool',
 'ReqNotifyDefuserState',
 'ReqOperateBattle',
 'ReqOperateCharacter',
 'ReqOperateGunReload',
 'ReqOperateScene',
 'ReqOperateTool',
 'ReqPickUpDefuser',
 'ReqPillarGroupInfo',
 'ReqPing',
 'ReqPlaceToolOperator',
 'ReqPlayerMark',
 'ReqPlayersResult',
 'ReqQuickChat',
 'ReqReinforcedWallInfo',
 'ReqRemoveNeuroToxinEffect',
 'ReqRemoveNeuroToxinOperator',
 'ReqReportThrowSceneToolFinalPosition',
 'ReqReportThrowSceneToolFinalPositionWithRelation',
 'ReqResetItemNum',
 'ReqRobotFire',
 'ReqRobotMove',
 'ReqRoomLoaded',
 'ReqScanEnemies',
 'ReqSecurityCameraInfo',
 'ReqShieldStateUpdate',
 'ReqShockGrenadeBomb',
 'ReqSimpleQuintainInfo',
 'ReqSimpleSceneItemInfo',
 'ReqSwitchCurrentMonitor',
 'ReqSwitchCurrentUnmannedVehicle',
 'ReqSwitchMonitorToCharacter',
 'ReqSwitchUnmannedVehicleToCharacter',
 'ReqSyncCharacterAction',
 'ReqSyncCharacterAssistTool',
 'ReqSyncCharacterTool',
 'ReqSyncCharacterWeaponState',
 'ReqSyncHandShieldState',
 'ReqSyncItemState',
 'ReqSyncNeuroToxinPosition',
 'ReqSyncPerformData',
 'ReqSyncPlayerState',
 'ReqSyncStretchHandShieldState',
 'ReqSyncThrowSceneToolPosition',
 'ReqThrowGrenadeEnd',
 'ReqThrowItem',
 'ReqThrowItemDropDown',
 'ReqThrowItemStoped',
 'ReqThrowNeuroToxin',
 'ReqThrowNeuroToxinEnd',
 'ReqThrowSceneTool',
 'ReqTrapBombInstalled',
 'ReqTrapBombUninstalled',
 'ReqTriggerFlashHandShield',
 'ReqTriggerTrapBomb',
 'ReqUnmannedVehicleSpawn',
 'ReqUnmannedVehicleTakeBack',
 'ReqUsePlaceSceneToolOperator',
 'ReqUseSceneTool',
 'ReqVehicleInfo',
 'ReqVehicleLaunchTracker',
 'ReqWallInfo',
 'RspCharacterPose',
 'RspPing']
BATTLE_PAYLOAD_DECODER_UNSUPPORTED_CLASSES = {'ReqUnmannedVehiclePoseDelta': 'manual_override_flags_payload'}
BATTLE_PAYLOAD_DECODER_FIELDS_BY_CLASS = {'PktHeartBeat': [],
 'PktVersion': [{'name': 'battle_gm', 'type': 'str8'},
                {'name': 'common', 'type': 'str8'},
                {'name': 'common_resources', 'type': 'str8'},
                {'name': 'game', 'type': 'str8'},
                {'name': 'scene', 'type': 'str8'}],
 'ReqActiveTracker': [{'name': 'tool_index', 'type': 'u16'}],
 'ReqAddRobot': [{'name': 'param', 'type': 'str8'}],
 'ReqArmorPackageInfo': [],
 'ReqBombBulletState': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                        {'name': 'trans', 'type': 'Transform'},
                        {'name': 'state', 'type': 'enum_type<BombGunBulletState, u8>'},
                        {'name': 'behurt_info', 'type': 'CharacterBeHurtInfo'},
                        {'name': 'hit_target', 'type': 'HitMarkTarget'}],
 'ReqBombExplosive': [{'name': 'throw_item_unique_id', 'type': 'u64'},
                      {'name': 'client_param', 'type': 'u32'},
                      {'name': 'trans', 'type': 'TransformEuler'}],
 'ReqBombGunFire': [{'name': 'bullet_id', 'type': 'u64'},
                    {'name': 'ray', 'type': 'BattleRay'},
                    {'name': 'euler', 'type': 'Vector3'},
                    {'name': 'security_code', 'type': 'u32'}],
 'ReqBuffInfo': [],
 'ReqCancelThrowGrenade': [{'name': 'grenade_id', 'type': 'u64'}],
 'ReqChangeBlockingBoardState': [{'name': 'id', 'type': 'cuint'},
                                 {'name': 'state', 'type': 'enum_type<BlockingBoardState, u8>'}],
 'ReqChangeReinforcedState': [{'name': 'id', 'type': 'cuint'},
                              {'name': 'state', 'type': 'enum_type<ReinforcedState, u8>'}],
 'ReqCharacterActionAimming': [{'name': 'aimming', 'type': 'boolean'}],
 'ReqCharacterActionExplodeExplosive': [{'name': 'hand_tool_id', 'type': 'u32'}],
 'ReqCharacterActionHammerAttack': [],
 'ReqCharacterActionInstallTrapBomb': [{'name': 'trap_bomb_uid', 'type': 'u64'},
                                       {'name': 'pos', 'type': 'Vector3'},
                                       {'name': 'rot', 'type': 'Quaternion'},
                                       {'name': 'install_type',
                                        'type': 'enum_type<TrapBombInstallType, u8>'}],
 'ReqCharacterActionMeleeAttack': [{'name': 'melee_attack_type', 'type': 'u8'}],
 'ReqCharacterActionTakeOutPad': [],
 'ReqCharacterActionTilt': [{'name': 'tilt_type', 'type': 'u8'}],
 'ReqCharacterActionUninstallTrapBomb': [{'name': 'trap_bomb_uid', 'type': 'u64'}],
 'ReqCharacterChangePoseInWall': [{'name': 'pose', 'type': 'BattleCharacterPose'},
                                  {'name': 'body_state', 'type': 'enum_type<EBodyState, u8>'}],
 'ReqCharacterClimbLadder': [{'name': 'ladder_id', 'type': 'u32'},
                             {'name': 'is_up', 'type': 'boolean'}],
 'ReqCharacterGunFire': [{'name': 'gun_fire_type', 'type': 'enum_type<GunFireType, u8>'},
                         {'name': 'bullets', 'type': 'vector<OneBullet>'},
                         {'name': 'security_code', 'type': 'u32'}],
 'ReqCharacterHammerAttack': [{'name': 'forward_ray', 'type': 'BattleRay'},
                              {'name': 'target', 'type': 'MeleeAttackTarget'},
                              {'name': 'target_type', 'type': 'u8'},
                              {'name': 'trans', 'type': 'Transform'},
                              {'name': 'target_mat', 'type': 'u8'}],
 'ReqCharacterInstallReinforced': [{'name': 'pose', 'type': 'BattleCharacterPose'},
                                   {'name': 'reinforced_id', 'type': 'cuint'}],
 'ReqCharacterIntoWallSpace': [{'name': 'desc', 'type': 'BattleCharacterWallSpace'},
                               {'name': 'wall_yaw', 'type': 'f32'}],
 'ReqCharacterJumpOn': [{'name': 'pose', 'type': 'BattleCharacterPose'},
                        {'name': 'desc', 'type': 'BattleCharacterJumpOn'}],
 'ReqCharacterJumpOver': [{'name': 'pose', 'type': 'BattleCharacterPose'},
                          {'name': 'desc', 'type': 'BattleCharacterJumpOver'}],
 'ReqCharacterLeaveLadder': [{'name': 'ladder_id', 'type': 'u32'},
                             {'name': 'is_up', 'type': 'boolean'}],
 'ReqCharacterLeaveWallSpace': [{'name': 'pose', 'type': 'BattleCharacterPose'},
                                {'name': 'desc', 'type': 'BattleCharacterWallSpace'}],
 'ReqCharacterLeaveWallSpaceByWindow': [{'name': 'dynamic_wall_id', 'type': 'u32'},
                                        {'name': 'pose', 'type': 'BattleCharacterPose'},
                                        {'name': 'desc',
                                         'type': 'BattleCharacterLeaveWallSpaceByWindow'}],
 'ReqCharacterLerpPos': [{'name': 'body_state', 'type': 'enum_type<ECharacterBodyState, u8>'},
                         {'name': 'pose', 'type': 'BattleCharacterPose'},
                         {'name': 'lerp_data', 'type': 'LerpData'}],
 'ReqCharacterMeleeAttack': [{'name': 'melee_cfg_id', 'type': 'u32'},
                             {'name': 'forward_ray', 'type': 'BattleRay'},
                             {'name': 'target', 'type': 'MeleeAttackTarget'}],
 'ReqCharacterOperateBlockingBoard': [{'name': 'pose', 'type': 'BattleCharacterPose'},
                                      {'name': 'block_id', 'type': 'cuint'},
                                      {'name': 'op', 'type': 'u8'}],
 'ReqCharacterOperateExplosive': [{'name': 'pose', 'type': 'BattleCharacterPose'},
                                  {'name': 'pos', 'type': 'Vector3'},
                                  {'name': 'yaw', 'type': 'f32'},
                                  {'name': 'op',
                                   'type': 'enum_type<CharacterExplosiveOperation, u8>'}],
 'ReqCharacterOperateShield': [{'name': 'pose', 'type': 'BattleCharacterPose'},
                               {'name': 'op', 'type': 'enum_type<CharacterShieldOperation, u8>'},
                               {'name': 'pos_x', 'type': 'f32'},
                               {'name': 'pos_y', 'type': 'f32'},
                               {'name': 'pos_z', 'type': 'f32'},
                               {'name': 'yaw', 'type': 'f32'}],
 'ReqCharacterOperation': [{'name': 'tool_index', 'type': 'u16'},
                           {'name': 'operation', 'type': 'enum_type<CharacterOperation, u16>'}],
 'ReqCharacterPose': [{'name': 'timestamp', 'type': 'u32'},
                      {'name': 'delta', 'type': 'BattleCharacterPoseDelta'}],
 'ReqCharacterState': [{'name': 'pose', 'type': 'BattleCharacterPose'},
                       {'name': 'state', 'type': 'enum_type<ECharacterBodyState, u8>'},
                       {'name': 'body_state', 'type': 'enum_type<EBodyState, u8>'}],
 'ReqCharacterThrowRope': [{'name': 'climb_trigger_id', 'type': 'u32'},
                           {'name': 'pose', 'type': 'BattleCharacterPose'},
                           {'name': 'desc', 'type': 'BattleCharacterThrowRope'}],
 'ReqClientCheatReport': [{'name': 'bid', 'type': 'u8'},
                          {'name': 'key', 'type': 'enum_type<ClientCheatDataKey, u8>'},
                          {'name': 'value', 'type': 'u8'}],
 'ReqCreatePlaceSceneTool': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                             {'name': 'relevant_id', 'type': 'vector<u64>'},
                             {'name': 'affected_id', 'type': 'u64'},
                             {'name': 'transform', 'type': 'TransformEuler'}],
 'ReqDestroyBlockingBoard': [{'name': 'board_id', 'type': 'u32'},
                             {'name': 'damage_source', 'type': 'Vector3'}],
 'ReqDestroySceneObject': [{'name': 'destroy_type', 'type': 'enum_type<DestroyType, u8>'},
                           {'name': 'destroy_pos', 'type': 'Vector3'},
                           {'name': 'destroy_objects', 'type': 'vector<u64>'}],
 'ReqDisturbedOperate': [{'name': 'item_uid', 'type': 'u64'},
                         {'name': 'tool_index', 'type': 'u16'},
                         {'name': 'op', 'type': 'enum_type<DisturbedOperate, u8>'}],
 'ReqDropDefuser': [],
 'ReqDynamicWallInfo': [],
 'ReqElectricBoxInfo': [],
 'ReqEnterBattle': [{'name': 'uid', 'type': 'u32'},
                    {'name': 'battle_id', 'type': 'u64'},
                    {'name': 'token', 'type': 'str8'},
                    {'name': 'client_info', 'type': 'ClientInfo'}],
 'ReqFoundBombTarget': [{'name': 'region_id', 'type': 'u32'}],
 'ReqFoundCriticalTarget': [{'name': 'region_id', 'type': 'u32'}],
 'ReqFoundDefuser': [{'name': 'defuser_id', 'type': 'u64'}],
 'ReqGameInfo': [],
 'ReqGamePlayerInfo': [],
 'ReqGamePoints': [{'name': 'player_id', 'type': 'u64'}],
 'ReqGenRobot': [{'name': 'config_id', 'type': 'u32'},
                 {'name': 'transform', 'type': 'TransformEuler'},
                 {'name': 'state', 'type': 'enum_type<ECharacterBodyState, u8>'}],
 'ReqGetBackNeuroToxinOperator': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                                  {'name': 'player_current_transform', 'type': 'TransformEuler'},
                                  {'name': 'state', 'type': 'enum_type<OperateState, u8>'}],
 'ReqGetBackNeuroToxinTool': [{'name': 'scene_tool_unique_id', 'type': 'u64'}],
 'ReqGetBackPlaceSceneTool': [{'name': 'scene_tool_unique_id', 'type': 'u64'}],
 'ReqGetBackPlaceSceneToolOperator': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                                      {'name': 'state', 'type': 'enum_type<OperateState, u8>'},
                                      {'name': 'lerp_data', 'type': 'LerpData'}],
 'ReqGrenadeBegin': [{'name': 'grenade_id', 'type': 'u64'}],
 'ReqGrenadeExplosivePosNtf': [{'name': 'grenade_id', 'type': 'u64'},
                               {'name': 'count', 'type': 'u32'},
                               {'name': 'pos', 'type': 'Vector3'}],
 'ReqGrenadeExplosivePosReport': [{'name': 'grenade_id', 'type': 'u64'},
                                  {'name': 'dir', 'type': 'Vector3'},
                                  {'name': 'trans', 'type': 'TransformEuler'}],
 'ReqGroundMaterial': [{'name': 'material', 'type': 'u32'}],
 'ReqIntoSceneTool': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                      {'name': 'hand_item_id', 'type': 'u32'}],
 'ReqItemPosReport': [{'name': 'throw_item_unique_id', 'type': 'u64'},
                      {'name': 'ray', 'type': 'BattleRay'},
                      {'name': 'angle', 'type': 'Vector3'}],
 'ReqKillMe': [],
 'ReqLeaveBattle': [{'name': 'kind', 'type': 'enum_type<LeaveBattleKind, u8>'}],
 'ReqLeaveSceneTool': [],
 'ReqLoadProgress': [{'name': 'progress', 'type': 'f32'}],
 'ReqMonitorPoseDelta': [{'name': 'monitor_id', 'type': 'u32'},
                         {'name': 'view_pitch', 'type': 'f32'},
                         {'name': 'view_yaw', 'type': 'f32'}],
 'ReqMonitorScanEnemies': [{'name': 'monitor_id', 'type': 'u32'},
                           {'name': 'view_yaw', 'type': 'f32'},
                           {'name': 'view_pitch', 'type': 'f32'},
                           {'name': 'enemies', 'type': 'vector<ScanEnemyInfo>'}],
 'ReqMountedLMGInfo': [],
 'ReqMoveToIntoSceneTool': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                            {'name': 'hand_item_id', 'type': 'u32'}],
 'ReqNotifyDefuserState': [{'name': 'state', 'type': 'enum_type<DefuserState, u8>'}],
 'ReqOperateBattle': [{'name': 'op', 'type': 'enum_type<GuidOperation, u8>'}],
 'ReqOperateCharacter': [{'name': 'hand_tool_id', 'type': 'u32'},
                         {'name': 'hand_tool_config_id', 'type': 'u32'},
                         {'name': 'target_player_bid', 'type': 'u8'},
                         {'name': 'state', 'type': 'enum_type<OperateState, u8>'}],
 'ReqOperateGunReload': [{'name': 'reload_type', 'type': 'enum_type<ReloadType, u8>'},
                         {'name': 'hand_item_id', 'type': 'u32'},
                         {'name': 'state', 'type': 'enum_type<OperateState, u8>'}],
 'ReqOperateScene': [{'name': 'hand_tool_id', 'type': 'u32'},
                     {'name': 'hand_tool_config_id', 'type': 'u32'},
                     {'name': 'target_index', 'type': 'u32'},
                     {'name': 'state', 'type': 'enum_type<OperateState, u8>'},
                     {'name': 'pose', 'type': 'BattleCharacterPose'},
                     {'name': 'trans', 'type': 'TransformEuler'}],
 'ReqOperateTool': [{'name': 'tool_index', 'type': 'u16'},
                    {'name': 'operation_type', 'type': 'enum_type<OperationType, u8>'},
                    {'name': 'state', 'type': 'enum_type<OperateState, u8>'}],
 'ReqPickUpDefuser': [],
 'ReqPillarGroupInfo': [],
 'ReqPing': [{'name': 'timestamp', 'type': 'u32'}],
 'ReqPlaceToolOperator': [{'name': 'hand_item_id', 'type': 'u32'},
                          {'name': 'relevant_id', 'type': 'vector<u64>'},
                          {'name': 'affected_id', 'type': 'u64'},
                          {'name': 'duration', 'type': 'f32'},
                          {'name': 'state', 'type': 'enum_type<OperateState, u8>'},
                          {'name': 'lerp_data', 'type': 'LerpData'}],
 'ReqPlayerMark': [{'name': 'pos', 'type': 'Vector3'}],
 'ReqPlayersResult': [],
 'ReqQuickChat': [{'name': 'chat_id', 'type': 'u8'}],
 'ReqReinforcedWallInfo': [],
 'ReqRemoveNeuroToxinEffect': [],
 'ReqRemoveNeuroToxinOperator': [],
 'ReqReportThrowSceneToolFinalPosition': [{'name': 'tool', 'type': 'ThrowSceneToolData'}],
 'ReqReportThrowSceneToolFinalPositionWithRelation': [{'name': 'tool',
                                                       'type': 'ThrowSceneToolData'},
                                                      {'name': 'relevant_id',
                                                       'type': 'vector<u64>'}],
 'ReqResetItemNum': [],
 'ReqRobotFire': [],
 'ReqRobotMove': [],
 'ReqRoomLoaded': [],
 'ReqScanEnemies': [{'name': 'vehicle_id', 'type': 'u64'},
                    {'name': 'pos', 'type': 'Vector3'},
                    {'name': 'enemies', 'type': 'vector<ScanEnemyInfo>'}],
 'ReqSecurityCameraInfo': [],
 'ReqShieldStateUpdate': [{'name': 'shield_state', 'type': 'enum_type<ShieldState, u8>'},
                          {'name': 'pos_x', 'type': 'f32'},
                          {'name': 'pos_y', 'type': 'f32'},
                          {'name': 'pos_z', 'type': 'f32'},
                          {'name': 'yaw', 'type': 'f32'}],
 'ReqShockGrenadeBomb': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                         {'name': 'trans', 'type': 'Transform'}],
 'ReqSimpleQuintainInfo': [],
 'ReqSimpleSceneItemInfo': [],
 'ReqSwitchCurrentMonitor': [{'name': 'monitor_id', 'type': 'u32'}],
 'ReqSwitchCurrentUnmannedVehicle': [{'name': 'vehicle_id', 'type': 'u64'}],
 'ReqSwitchMonitorToCharacter': [],
 'ReqSwitchUnmannedVehicleToCharacter': [],
 'ReqSyncCharacterAction': [{'name': 'action', 'type': 'u32'},
                            {'name': 'duration', 'type': 'f32'},
                            {'name': 'duration_coefficient', 'type': 'f32'}],
 'ReqSyncCharacterAssistTool': [{'name': 'assist_tool_index', 'type': 'u16'}],
 'ReqSyncCharacterTool': [{'name': 'tool_index', 'type': 'u16'}],
 'ReqSyncCharacterWeaponState': [{'name': 'weapon_state', 'type': 'enum_type<EWeaponState, u8>'}],
 'ReqSyncHandShieldState': [{'name': 'tool_index', 'type': 'u16'},
                            {'name': 'is_in_back', 'type': 'boolean'}],
 'ReqSyncItemState': [{'name': 'item_uid', 'type': 'u64'},
                      {'name': 'effect_type', 'type': 'enum_type<EffectType, u8>'}],
 'ReqSyncNeuroToxinPosition': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                               {'name': 'transform', 'type': 'TransformEuler'},
                               {'name': 'speed', 'type': 'Vector3'}],
 'ReqSyncPerformData': [{'name': 'data_type', 'type': 'u32'},
                        {'name': 'data', 'type': 'PerformData'}],
 'ReqSyncPlayerState': [{'name': 'effect_type', 'type': 'enum_type<EffectType, u8>'}],
 'ReqSyncStretchHandShieldState': [{'name': 'is_expanded', 'type': 'boolean'}],
 'ReqSyncThrowSceneToolPosition': [{'name': 'tool', 'type': 'ThrowSceneToolData'}],
 'ReqThrowGrenadeEnd': [{'name': 'grenade_id', 'type': 'u64'},
                        {'name': 'dir', 'type': 'Vector3'},
                        {'name': 'trans', 'type': 'TransformEuler'}],
 'ReqThrowItem': [{'name': 'throw_item_unique_id', 'type': 'u64'},
                  {'name': 'client_param', 'type': 'u32'},
                  {'name': 'ray', 'type': 'BattleRay'},
                  {'name': 'angle', 'type': 'Vector3'}],
 'ReqThrowItemDropDown': [{'name': 'throw_item_unique_id', 'type': 'u64'},
                          {'name': 'ray', 'type': 'BattleRay'}],
 'ReqThrowItemStoped': [{'name': 'throw_item_unique_id', 'type': 'u64'},
                        {'name': 'trans', 'type': 'TransformEuler'},
                        {'name': 'relates', 'type': 'vector<u64>'}],
 'ReqThrowNeuroToxin': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                        {'name': 'client_param', 'type': 'u32'},
                        {'name': 'transform', 'type': 'TransformEuler'},
                        {'name': 'speed', 'type': 'Vector3'}],
 'ReqThrowNeuroToxinEnd': [{'name': 'scene_tool_unique_id', 'type': 'u64'},
                           {'name': 'transform', 'type': 'TransformEuler'},
                           {'name': 'speed', 'type': 'Vector3'},
                           {'name': 'relevant_id', 'type': 'vector<u64>'}],
 'ReqThrowSceneTool': [{'name': 'tool', 'type': 'ThrowSceneToolData'}],
 'ReqTrapBombInstalled': [{'name': 'trap_bomb_uid', 'type': 'u64'},
                          {'name': 'block_id', 'type': 'u32'},
                          {'name': 'bomb_pos', 'type': 'Vector3'},
                          {'name': 'bomb_rot', 'type': 'Quaternion'},
                          {'name': 'bomb_extens', 'type': 'Vector3'},
                          {'name': 'trigger_pos', 'type': 'Vector3'},
                          {'name': 'trigger_extens', 'type': 'Vector3'},
                          {'name': 'install_type', 'type': 'enum_type<TrapBombInstallType, u8>'}],
 'ReqTrapBombUninstalled': [{'name': 'trap_bomb_uid', 'type': 'u64'}],
 'ReqTriggerFlashHandShield': [{'name': 'flash_point', 'type': 'Transform'}],
 'ReqTriggerTrapBomb': [{'name': 'trap_bomb_uid', 'type': 'u64'},
                        {'name': 'char_pos', 'type': 'Vector3'}],
 'ReqUnmannedVehiclePoseDelta': [{'name': 'vehicle_id', 'type': 'u64'},
                                 {'name': 'pos_x', 'type': 'f32'},
                                 {'name': 'pos_y', 'type': 'f32'},
                                 {'name': 'pos_z', 'type': 'f32'},
                                 {'name': 'yaw', 'type': 'f32'},
                                 {'name': 'view_pitch', 'type': 'f32'},
                                 {'name': 'view_yaw', 'type': 'f32'},
                                 {'name': 'view_roll', 'type': 'f32'}],
 'ReqUnmannedVehicleSpawn': [{'name': 'vehicle_id', 'type': 'u64'},
                             {'name': 'pose', 'type': 'BattleCharacterPose'}],
 'ReqUnmannedVehicleTakeBack': [{'name': 'vehicle_id', 'type': 'u64'}],
 'ReqUsePlaceSceneToolOperator': [{'name': 'hand_item_id', 'type': 'u32'},
                                  {'name': 'scene_tool_unique_id', 'type': 'u64'},
                                  {'name': 'state', 'type': 'enum_type<OperateState, u8>'},
                                  {'name': 'lerp_data', 'type': 'LerpData'}],
 'ReqUseSceneTool': [{'name': 'hand_item_id', 'type': 'u32'},
                     {'name': 'scene_tool_unique_id', 'type': 'u64'}],
 'ReqVehicleInfo': [],
 'ReqVehicleLaunchTracker': [{'name': 'pos_start', 'type': 'Vector3'},
                             {'name': 'pos_ends', 'type': 'vector<Vector3>'},
                             {'name': 'target_bids', 'type': 'vector<u8>'}],
 'ReqWallInfo': [],
 'RspCharacterPose': [{'name': 'bid', 'type': 'u8'},
                      {'name': 'delta', 'type': 'BattleCharacterPoseDelta'}],
 'RspPing': [{'name': 'timestamp', 'type': 'u32'}]}
BATTLE_PAYLOAD_DECODER_HELPERS_BY_CLASS = {'PktHeartBeat': [],
 'PktVersion': [],
 'ReqActiveTracker': [],
 'ReqAddRobot': [],
 'ReqArmorPackageInfo': [],
 'ReqBombBulletState': ['read_character_be_hurt_info', 'read_hit_mark_target', 'read_transform'],
 'ReqBombExplosive': ['read_transform_euler'],
 'ReqBombGunFire': ['read_battle_ray', 'read_vector3'],
 'ReqBuffInfo': [],
 'ReqCancelThrowGrenade': [],
 'ReqChangeBlockingBoardState': [],
 'ReqChangeReinforcedState': [],
 'ReqCharacterActionAimming': [],
 'ReqCharacterActionExplodeExplosive': [],
 'ReqCharacterActionHammerAttack': [],
 'ReqCharacterActionInstallTrapBomb': ['read_quaternion', 'read_vector3'],
 'ReqCharacterActionMeleeAttack': [],
 'ReqCharacterActionTakeOutPad': [],
 'ReqCharacterActionTilt': [],
 'ReqCharacterActionUninstallTrapBomb': [],
 'ReqCharacterChangePoseInWall': ['read_battle_pose'],
 'ReqCharacterClimbLadder': [],
 'ReqCharacterGunFire': ['read_one_bullet'],
 'ReqCharacterHammerAttack': ['read_battle_ray', 'read_melee_attack_target', 'read_transform'],
 'ReqCharacterInstallReinforced': ['read_battle_pose'],
 'ReqCharacterIntoWallSpace': ['read_battle_character_wall_space'],
 'ReqCharacterJumpOn': ['read_battle_jump_on', 'read_battle_pose'],
 'ReqCharacterJumpOver': ['read_battle_jump_over', 'read_battle_pose'],
 'ReqCharacterLeaveLadder': [],
 'ReqCharacterLeaveWallSpace': ['read_battle_character_wall_space', 'read_battle_pose'],
 'ReqCharacterLeaveWallSpaceByWindow': ['read_battle_leave_wall_space_by_window',
                                        'read_battle_pose'],
 'ReqCharacterLerpPos': ['read_battle_pose', 'read_lerp_data'],
 'ReqCharacterMeleeAttack': ['read_battle_ray', 'read_melee_attack_target'],
 'ReqCharacterOperateBlockingBoard': ['read_battle_pose'],
 'ReqCharacterOperateExplosive': ['read_battle_pose', 'read_vector3'],
 'ReqCharacterOperateShield': ['read_battle_pose'],
 'ReqCharacterOperation': [],
 'ReqCharacterPose': ['read_pose_delta'],
 'ReqCharacterState': ['read_battle_pose'],
 'ReqCharacterThrowRope': ['read_battle_character_throw_rope', 'read_battle_pose'],
 'ReqClientCheatReport': [],
 'ReqCreatePlaceSceneTool': ['read_transform_euler'],
 'ReqDestroyBlockingBoard': ['read_vector3'],
 'ReqDestroySceneObject': ['read_vector3'],
 'ReqDisturbedOperate': [],
 'ReqDropDefuser': [],
 'ReqDynamicWallInfo': [],
 'ReqElectricBoxInfo': [],
 'ReqEnterBattle': ['read_client_info'],
 'ReqFoundBombTarget': [],
 'ReqFoundCriticalTarget': [],
 'ReqFoundDefuser': [],
 'ReqGameInfo': [],
 'ReqGamePlayerInfo': [],
 'ReqGamePoints': [],
 'ReqGenRobot': ['read_transform_euler'],
 'ReqGetBackNeuroToxinOperator': ['read_transform_euler'],
 'ReqGetBackNeuroToxinTool': [],
 'ReqGetBackPlaceSceneTool': [],
 'ReqGetBackPlaceSceneToolOperator': ['read_lerp_data'],
 'ReqGrenadeBegin': [],
 'ReqGrenadeExplosivePosNtf': ['read_vector3'],
 'ReqGrenadeExplosivePosReport': ['read_transform_euler', 'read_vector3'],
 'ReqGroundMaterial': [],
 'ReqIntoSceneTool': [],
 'ReqItemPosReport': ['read_battle_ray', 'read_vector3'],
 'ReqKillMe': [],
 'ReqLeaveBattle': [],
 'ReqLeaveSceneTool': [],
 'ReqLoadProgress': [],
 'ReqMonitorPoseDelta': [],
 'ReqMonitorScanEnemies': ['read_scan_enemy_info'],
 'ReqMountedLMGInfo': [],
 'ReqMoveToIntoSceneTool': [],
 'ReqNotifyDefuserState': [],
 'ReqOperateBattle': [],
 'ReqOperateCharacter': [],
 'ReqOperateGunReload': [],
 'ReqOperateScene': ['read_battle_pose', 'read_transform_euler'],
 'ReqOperateTool': [],
 'ReqPickUpDefuser': [],
 'ReqPillarGroupInfo': [],
 'ReqPing': [],
 'ReqPlaceToolOperator': ['read_lerp_data'],
 'ReqPlayerMark': ['read_vector3'],
 'ReqPlayersResult': [],
 'ReqQuickChat': [],
 'ReqReinforcedWallInfo': [],
 'ReqRemoveNeuroToxinEffect': [],
 'ReqRemoveNeuroToxinOperator': [],
 'ReqReportThrowSceneToolFinalPosition': ['read_throw_scene_tool_data'],
 'ReqReportThrowSceneToolFinalPositionWithRelation': ['read_throw_scene_tool_data'],
 'ReqResetItemNum': [],
 'ReqRobotFire': [],
 'ReqRobotMove': [],
 'ReqRoomLoaded': [],
 'ReqScanEnemies': ['read_scan_enemy_info', 'read_vector3'],
 'ReqSecurityCameraInfo': [],
 'ReqShieldStateUpdate': [],
 'ReqShockGrenadeBomb': ['read_transform'],
 'ReqSimpleQuintainInfo': [],
 'ReqSimpleSceneItemInfo': [],
 'ReqSwitchCurrentMonitor': [],
 'ReqSwitchCurrentUnmannedVehicle': [],
 'ReqSwitchMonitorToCharacter': [],
 'ReqSwitchUnmannedVehicleToCharacter': [],
 'ReqSyncCharacterAction': [],
 'ReqSyncCharacterAssistTool': [],
 'ReqSyncCharacterTool': [],
 'ReqSyncCharacterWeaponState': [],
 'ReqSyncHandShieldState': [],
 'ReqSyncItemState': [],
 'ReqSyncNeuroToxinPosition': ['read_transform_euler', 'read_vector3'],
 'ReqSyncPerformData': ['read_perform_data'],
 'ReqSyncPlayerState': [],
 'ReqSyncStretchHandShieldState': [],
 'ReqSyncThrowSceneToolPosition': ['read_throw_scene_tool_data'],
 'ReqThrowGrenadeEnd': ['read_transform_euler', 'read_vector3'],
 'ReqThrowItem': ['read_battle_ray', 'read_vector3'],
 'ReqThrowItemDropDown': ['read_battle_ray'],
 'ReqThrowItemStoped': ['read_transform_euler'],
 'ReqThrowNeuroToxin': ['read_transform_euler', 'read_vector3'],
 'ReqThrowNeuroToxinEnd': ['read_transform_euler', 'read_vector3'],
 'ReqThrowSceneTool': ['read_throw_scene_tool_data'],
 'ReqTrapBombInstalled': ['read_quaternion', 'read_vector3'],
 'ReqTrapBombUninstalled': [],
 'ReqTriggerFlashHandShield': ['read_transform'],
 'ReqTriggerTrapBomb': ['read_vector3'],
 'ReqUnmannedVehicleSpawn': ['read_battle_pose'],
 'ReqUnmannedVehicleTakeBack': [],
 'ReqUsePlaceSceneToolOperator': ['read_lerp_data'],
 'ReqUseSceneTool': [],
 'ReqVehicleInfo': [],
 'ReqVehicleLaunchTracker': ['read_vector3'],
 'ReqWallInfo': [],
 'RspCharacterPose': ['read_pose_delta'],
 'RspPing': []}

def _decode_PktHeartBeat(stream, helpers):
    return {}

def _decode_PktVersion(stream, helpers):
    return {
        'battle_gm': stream.read_str8(),
        'common': stream.read_str8(),
        'common_resources': stream.read_str8(),
        'game': stream.read_str8(),
        'scene': stream.read_str8(),
    }

def _decode_ReqActiveTracker(stream, helpers):
    return {
        'tool_index': stream.read_u16(),
    }

def _decode_ReqAddRobot(stream, helpers):
    return {
        'param': stream.read_str8(),
    }

def _decode_ReqArmorPackageInfo(stream, helpers):
    return {}

def _decode_ReqBombBulletState(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'trans': helpers['read_transform'](stream),
        'state': stream.read_u8(),
        'behurt_info': helpers['read_character_be_hurt_info'](stream),
        'hit_target': helpers['read_hit_mark_target'](stream),
    }

def _decode_ReqBombExplosive(stream, helpers):
    return {
        'throw_item_unique_id': stream.read_u64(),
        'client_param': stream.read_u32(),
        'trans': helpers['read_transform_euler'](stream),
    }

def _decode_ReqBombGunFire(stream, helpers):
    return {
        'bullet_id': stream.read_u64(),
        'ray': helpers['read_battle_ray'](stream),
        'euler': helpers['read_vector3'](stream),
        'security_code': stream.read_u32(),
    }

def _decode_ReqBuffInfo(stream, helpers):
    return {}

def _decode_ReqCancelThrowGrenade(stream, helpers):
    return {
        'grenade_id': stream.read_u64(),
    }

def _decode_ReqChangeBlockingBoardState(stream, helpers):
    return {
        'id': stream.read_cuint(),
        'state': stream.read_u8(),
    }

def _decode_ReqChangeReinforcedState(stream, helpers):
    return {
        'id': stream.read_cuint(),
        'state': stream.read_u8(),
    }

def _decode_ReqCharacterActionAimming(stream, helpers):
    return {
        'aimming': stream.read_bool(),
    }

def _decode_ReqCharacterActionExplodeExplosive(stream, helpers):
    return {
        'hand_tool_id': stream.read_u32(),
    }

def _decode_ReqCharacterActionHammerAttack(stream, helpers):
    return {}

def _decode_ReqCharacterActionInstallTrapBomb(stream, helpers):
    return {
        'trap_bomb_uid': stream.read_u64(),
        'pos': helpers['read_vector3'](stream),
        'rot': helpers['read_quaternion'](stream),
        'install_type': stream.read_u8(),
    }

def _decode_ReqCharacterActionMeleeAttack(stream, helpers):
    return {
        'melee_attack_type': stream.read_u8(),
    }

def _decode_ReqCharacterActionTakeOutPad(stream, helpers):
    return {}

def _decode_ReqCharacterActionTilt(stream, helpers):
    return {
        'tilt_type': stream.read_u8(),
    }

def _decode_ReqCharacterActionUninstallTrapBomb(stream, helpers):
    return {
        'trap_bomb_uid': stream.read_u64(),
    }

def _decode_ReqCharacterChangePoseInWall(stream, helpers):
    return {
        'pose': helpers['read_battle_pose'](stream),
        'body_state': stream.read_u8(),
    }

def _decode_ReqCharacterClimbLadder(stream, helpers):
    return {
        'ladder_id': stream.read_u32(),
        'is_up': stream.read_bool(),
    }

def _decode_ReqCharacterGunFire(stream, helpers):
    return {
        'gun_fire_type': stream.read_u8(),
        'bullets': [helpers['read_one_bullet'](stream) for _ in range(stream.read_cuint())],
        'security_code': stream.read_u32(),
    }

def _decode_ReqCharacterHammerAttack(stream, helpers):
    return {
        'forward_ray': helpers['read_battle_ray'](stream),
        'target': helpers['read_melee_attack_target'](stream),
        'target_type': stream.read_u8(),
        'trans': helpers['read_transform'](stream),
        'target_mat': stream.read_u8(),
    }

def _decode_ReqCharacterInstallReinforced(stream, helpers):
    return {
        'pose': helpers['read_battle_pose'](stream),
        'reinforced_id': stream.read_cuint(),
    }

def _decode_ReqCharacterIntoWallSpace(stream, helpers):
    return {
        'desc': helpers['read_battle_character_wall_space'](stream),
        'wall_yaw': stream.read_f32(),
    }

def _decode_ReqCharacterJumpOn(stream, helpers):
    return {
        'pose': helpers['read_battle_pose'](stream),
        'desc': helpers['read_battle_jump_on'](stream),
    }

def _decode_ReqCharacterJumpOver(stream, helpers):
    return {
        'pose': helpers['read_battle_pose'](stream),
        'desc': helpers['read_battle_jump_over'](stream),
    }

def _decode_ReqCharacterLeaveLadder(stream, helpers):
    return {
        'ladder_id': stream.read_u32(),
        'is_up': stream.read_bool(),
    }

def _decode_ReqCharacterLeaveWallSpace(stream, helpers):
    return {
        'pose': helpers['read_battle_pose'](stream),
        'desc': helpers['read_battle_character_wall_space'](stream),
    }

def _decode_ReqCharacterLeaveWallSpaceByWindow(stream, helpers):
    return {
        'dynamic_wall_id': stream.read_u32(),
        'pose': helpers['read_battle_pose'](stream),
        'desc': helpers['read_battle_leave_wall_space_by_window'](stream),
    }

def _decode_ReqCharacterLerpPos(stream, helpers):
    return {
        'body_state': stream.read_u8(),
        'pose': helpers['read_battle_pose'](stream),
        'lerp_data': helpers['read_lerp_data'](stream),
    }

def _decode_ReqCharacterMeleeAttack(stream, helpers):
    return {
        'melee_cfg_id': stream.read_u32(),
        'forward_ray': helpers['read_battle_ray'](stream),
        'target': helpers['read_melee_attack_target'](stream),
    }

def _decode_ReqCharacterOperateBlockingBoard(stream, helpers):
    return {
        'pose': helpers['read_battle_pose'](stream),
        'block_id': stream.read_cuint(),
        'op': stream.read_u8(),
    }

def _decode_ReqCharacterOperateExplosive(stream, helpers):
    return {
        'pose': helpers['read_battle_pose'](stream),
        'pos': helpers['read_vector3'](stream),
        'yaw': stream.read_f32(),
        'op': stream.read_u8(),
    }

def _decode_ReqCharacterOperateShield(stream, helpers):
    return {
        'pose': helpers['read_battle_pose'](stream),
        'op': stream.read_u8(),
        'pos_x': stream.read_f32(),
        'pos_y': stream.read_f32(),
        'pos_z': stream.read_f32(),
        'yaw': stream.read_f32(),
    }

def _decode_ReqCharacterOperation(stream, helpers):
    return {
        'tool_index': stream.read_u16(),
        'operation': stream.read_u16(),
    }

def _decode_ReqCharacterPose(stream, helpers):
    return {
        'timestamp': stream.read_u32(),
        'delta': helpers['read_pose_delta'](stream),
    }

def _decode_ReqCharacterState(stream, helpers):
    return {
        'pose': helpers['read_battle_pose'](stream),
        'state': stream.read_u8(),
        'body_state': stream.read_u8(),
    }

def _decode_ReqCharacterThrowRope(stream, helpers):
    return {
        'climb_trigger_id': stream.read_u32(),
        'pose': helpers['read_battle_pose'](stream),
        'desc': helpers['read_battle_character_throw_rope'](stream),
    }

def _decode_ReqClientCheatReport(stream, helpers):
    return {
        'bid': stream.read_u8(),
        'key': stream.read_u8(),
        'value': stream.read_u8(),
    }

def _decode_ReqCreatePlaceSceneTool(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'relevant_id': [stream.read_u64() for _ in range(stream.read_cuint())],
        'affected_id': stream.read_u64(),
        'transform': helpers['read_transform_euler'](stream),
    }

def _decode_ReqDestroyBlockingBoard(stream, helpers):
    return {
        'board_id': stream.read_u32(),
        'damage_source': helpers['read_vector3'](stream),
    }

def _decode_ReqDestroySceneObject(stream, helpers):
    return {
        'destroy_type': stream.read_u8(),
        'destroy_pos': helpers['read_vector3'](stream),
        'destroy_objects': [stream.read_u64() for _ in range(stream.read_cuint())],
    }

def _decode_ReqDisturbedOperate(stream, helpers):
    return {
        'item_uid': stream.read_u64(),
        'tool_index': stream.read_u16(),
        'op': stream.read_u8(),
    }

def _decode_ReqDropDefuser(stream, helpers):
    return {}

def _decode_ReqDynamicWallInfo(stream, helpers):
    return {}

def _decode_ReqElectricBoxInfo(stream, helpers):
    return {}

def _decode_ReqEnterBattle(stream, helpers):
    return {
        'uid': stream.read_u32(),
        'battle_id': stream.read_u64(),
        'token': stream.read_str8(),
        'client_info': helpers['read_client_info'](stream),
    }

def _decode_ReqFoundBombTarget(stream, helpers):
    return {
        'region_id': stream.read_u32(),
    }

def _decode_ReqFoundCriticalTarget(stream, helpers):
    return {
        'region_id': stream.read_u32(),
    }

def _decode_ReqFoundDefuser(stream, helpers):
    return {
        'defuser_id': stream.read_u64(),
    }

def _decode_ReqGameInfo(stream, helpers):
    return {}

def _decode_ReqGamePlayerInfo(stream, helpers):
    return {}

def _decode_ReqGamePoints(stream, helpers):
    return {
        'player_id': stream.read_u64(),
    }

def _decode_ReqGenRobot(stream, helpers):
    return {
        'config_id': stream.read_u32(),
        'transform': helpers['read_transform_euler'](stream),
        'state': stream.read_u8(),
    }

def _decode_ReqGetBackNeuroToxinOperator(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'player_current_transform': helpers['read_transform_euler'](stream),
        'state': stream.read_u8(),
    }

def _decode_ReqGetBackNeuroToxinTool(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
    }

def _decode_ReqGetBackPlaceSceneTool(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
    }

def _decode_ReqGetBackPlaceSceneToolOperator(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'state': stream.read_u8(),
        'lerp_data': helpers['read_lerp_data'](stream),
    }

def _decode_ReqGrenadeBegin(stream, helpers):
    return {
        'grenade_id': stream.read_u64(),
    }

def _decode_ReqGrenadeExplosivePosNtf(stream, helpers):
    return {
        'grenade_id': stream.read_u64(),
        'count': stream.read_u32(),
        'pos': helpers['read_vector3'](stream),
    }

def _decode_ReqGrenadeExplosivePosReport(stream, helpers):
    return {
        'grenade_id': stream.read_u64(),
        'dir': helpers['read_vector3'](stream),
        'trans': helpers['read_transform_euler'](stream),
    }

def _decode_ReqGroundMaterial(stream, helpers):
    return {
        'material': stream.read_u32(),
    }

def _decode_ReqIntoSceneTool(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'hand_item_id': stream.read_u32(),
    }

def _decode_ReqItemPosReport(stream, helpers):
    return {
        'throw_item_unique_id': stream.read_u64(),
        'ray': helpers['read_battle_ray'](stream),
        'angle': helpers['read_vector3'](stream),
    }

def _decode_ReqKillMe(stream, helpers):
    return {}

def _decode_ReqLeaveBattle(stream, helpers):
    return {
        'kind': stream.read_u8(),
    }

def _decode_ReqLeaveSceneTool(stream, helpers):
    return {}

def _decode_ReqLoadProgress(stream, helpers):
    return {
        'progress': stream.read_f32(),
    }

def _decode_ReqMonitorPoseDelta(stream, helpers):
    return {
        'monitor_id': stream.read_u32(),
        'view_pitch': stream.read_f32(),
        'view_yaw': stream.read_f32(),
    }

def _decode_ReqMonitorScanEnemies(stream, helpers):
    return {
        'monitor_id': stream.read_u32(),
        'view_yaw': stream.read_f32(),
        'view_pitch': stream.read_f32(),
        'enemies': [helpers['read_scan_enemy_info'](stream) for _ in range(stream.read_cuint())],
    }

def _decode_ReqMountedLMGInfo(stream, helpers):
    return {}

def _decode_ReqMoveToIntoSceneTool(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'hand_item_id': stream.read_u32(),
    }

def _decode_ReqNotifyDefuserState(stream, helpers):
    return {
        'state': stream.read_u8(),
    }

def _decode_ReqOperateBattle(stream, helpers):
    return {
        'op': stream.read_u8(),
    }

def _decode_ReqOperateCharacter(stream, helpers):
    return {
        'hand_tool_id': stream.read_u32(),
        'hand_tool_config_id': stream.read_u32(),
        'target_player_bid': stream.read_u8(),
        'state': stream.read_u8(),
    }

def _decode_ReqOperateGunReload(stream, helpers):
    return {
        'reload_type': stream.read_u8(),
        'hand_item_id': stream.read_u32(),
        'state': stream.read_u8(),
    }

def _decode_ReqOperateScene(stream, helpers):
    return {
        'hand_tool_id': stream.read_u32(),
        'hand_tool_config_id': stream.read_u32(),
        'target_index': stream.read_u32(),
        'state': stream.read_u8(),
        'pose': helpers['read_battle_pose'](stream),
        'trans': helpers['read_transform_euler'](stream),
    }

def _decode_ReqOperateTool(stream, helpers):
    return {
        'tool_index': stream.read_u16(),
        'operation_type': stream.read_u8(),
        'state': stream.read_u8(),
    }

def _decode_ReqPickUpDefuser(stream, helpers):
    return {}

def _decode_ReqPillarGroupInfo(stream, helpers):
    return {}

def _decode_ReqPing(stream, helpers):
    return {
        'timestamp': stream.read_u32(),
    }

def _decode_ReqPlaceToolOperator(stream, helpers):
    return {
        'hand_item_id': stream.read_u32(),
        'relevant_id': [stream.read_u64() for _ in range(stream.read_cuint())],
        'affected_id': stream.read_u64(),
        'duration': stream.read_f32(),
        'state': stream.read_u8(),
        'lerp_data': helpers['read_lerp_data'](stream),
    }

def _decode_ReqPlayerMark(stream, helpers):
    return {
        'pos': helpers['read_vector3'](stream),
    }

def _decode_ReqPlayersResult(stream, helpers):
    return {}

def _decode_ReqQuickChat(stream, helpers):
    return {
        'chat_id': stream.read_u8(),
    }

def _decode_ReqReinforcedWallInfo(stream, helpers):
    return {}

def _decode_ReqRemoveNeuroToxinEffect(stream, helpers):
    return {}

def _decode_ReqRemoveNeuroToxinOperator(stream, helpers):
    return {}

def _decode_ReqReportThrowSceneToolFinalPosition(stream, helpers):
    return {
        'tool': helpers['read_throw_scene_tool_data'](stream),
    }

def _decode_ReqReportThrowSceneToolFinalPositionWithRelation(stream, helpers):
    return {
        'tool': helpers['read_throw_scene_tool_data'](stream),
        'relevant_id': [stream.read_u64() for _ in range(stream.read_cuint())],
    }

def _decode_ReqResetItemNum(stream, helpers):
    return {}

def _decode_ReqRobotFire(stream, helpers):
    return {}

def _decode_ReqRobotMove(stream, helpers):
    return {}

def _decode_ReqRoomLoaded(stream, helpers):
    return {}

def _decode_ReqScanEnemies(stream, helpers):
    return {
        'vehicle_id': stream.read_u64(),
        'pos': helpers['read_vector3'](stream),
        'enemies': [helpers['read_scan_enemy_info'](stream) for _ in range(stream.read_cuint())],
    }

def _decode_ReqSecurityCameraInfo(stream, helpers):
    return {}

def _decode_ReqShieldStateUpdate(stream, helpers):
    return {
        'shield_state': stream.read_u8(),
        'pos_x': stream.read_f32(),
        'pos_y': stream.read_f32(),
        'pos_z': stream.read_f32(),
        'yaw': stream.read_f32(),
    }

def _decode_ReqShockGrenadeBomb(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'trans': helpers['read_transform'](stream),
    }

def _decode_ReqSimpleQuintainInfo(stream, helpers):
    return {}

def _decode_ReqSimpleSceneItemInfo(stream, helpers):
    return {}

def _decode_ReqSwitchCurrentMonitor(stream, helpers):
    return {
        'monitor_id': stream.read_u32(),
    }

def _decode_ReqSwitchCurrentUnmannedVehicle(stream, helpers):
    return {
        'vehicle_id': stream.read_u64(),
    }

def _decode_ReqSwitchMonitorToCharacter(stream, helpers):
    return {}

def _decode_ReqSwitchUnmannedVehicleToCharacter(stream, helpers):
    return {}

def _decode_ReqSyncCharacterAction(stream, helpers):
    return {
        'action': stream.read_u32(),
        'duration': stream.read_f32(),
        'duration_coefficient': stream.read_f32(),
    }

def _decode_ReqSyncCharacterAssistTool(stream, helpers):
    return {
        'assist_tool_index': stream.read_u16(),
    }

def _decode_ReqSyncCharacterTool(stream, helpers):
    return {
        'tool_index': stream.read_u16(),
    }

def _decode_ReqSyncCharacterWeaponState(stream, helpers):
    return {
        'weapon_state': stream.read_u8(),
    }

def _decode_ReqSyncHandShieldState(stream, helpers):
    return {
        'tool_index': stream.read_u16(),
        'is_in_back': stream.read_bool(),
    }

def _decode_ReqSyncItemState(stream, helpers):
    return {
        'item_uid': stream.read_u64(),
        'effect_type': stream.read_u8(),
    }

def _decode_ReqSyncNeuroToxinPosition(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'transform': helpers['read_transform_euler'](stream),
        'speed': helpers['read_vector3'](stream),
    }

def _decode_ReqSyncPerformData(stream, helpers):
    return {
        'data_type': stream.read_u32(),
        'data': helpers['read_perform_data'](stream),
    }

def _decode_ReqSyncPlayerState(stream, helpers):
    return {
        'effect_type': stream.read_u8(),
    }

def _decode_ReqSyncStretchHandShieldState(stream, helpers):
    return {
        'is_expanded': stream.read_bool(),
    }

def _decode_ReqSyncThrowSceneToolPosition(stream, helpers):
    return {
        'tool': helpers['read_throw_scene_tool_data'](stream),
    }

def _decode_ReqThrowGrenadeEnd(stream, helpers):
    return {
        'grenade_id': stream.read_u64(),
        'dir': helpers['read_vector3'](stream),
        'trans': helpers['read_transform_euler'](stream),
    }

def _decode_ReqThrowItem(stream, helpers):
    return {
        'throw_item_unique_id': stream.read_u64(),
        'client_param': stream.read_u32(),
        'ray': helpers['read_battle_ray'](stream),
        'angle': helpers['read_vector3'](stream),
    }

def _decode_ReqThrowItemDropDown(stream, helpers):
    return {
        'throw_item_unique_id': stream.read_u64(),
        'ray': helpers['read_battle_ray'](stream),
    }

def _decode_ReqThrowItemStoped(stream, helpers):
    return {
        'throw_item_unique_id': stream.read_u64(),
        'trans': helpers['read_transform_euler'](stream),
        'relates': [stream.read_u64() for _ in range(stream.read_cuint())],
    }

def _decode_ReqThrowNeuroToxin(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'client_param': stream.read_u32(),
        'transform': helpers['read_transform_euler'](stream),
        'speed': helpers['read_vector3'](stream),
    }

def _decode_ReqThrowNeuroToxinEnd(stream, helpers):
    return {
        'scene_tool_unique_id': stream.read_u64(),
        'transform': helpers['read_transform_euler'](stream),
        'speed': helpers['read_vector3'](stream),
        'relevant_id': [stream.read_u64() for _ in range(stream.read_cuint())],
    }

def _decode_ReqThrowSceneTool(stream, helpers):
    return {
        'tool': helpers['read_throw_scene_tool_data'](stream),
    }

def _decode_ReqTrapBombInstalled(stream, helpers):
    return {
        'trap_bomb_uid': stream.read_u64(),
        'block_id': stream.read_u32(),
        'bomb_pos': helpers['read_vector3'](stream),
        'bomb_rot': helpers['read_quaternion'](stream),
        'bomb_extens': helpers['read_vector3'](stream),
        'trigger_pos': helpers['read_vector3'](stream),
        'trigger_extens': helpers['read_vector3'](stream),
        'install_type': stream.read_u8(),
    }

def _decode_ReqTrapBombUninstalled(stream, helpers):
    return {
        'trap_bomb_uid': stream.read_u64(),
    }

def _decode_ReqTriggerFlashHandShield(stream, helpers):
    return {
        'flash_point': helpers['read_transform'](stream),
    }

def _decode_ReqTriggerTrapBomb(stream, helpers):
    return {
        'trap_bomb_uid': stream.read_u64(),
        'char_pos': helpers['read_vector3'](stream),
    }

def _decode_ReqUnmannedVehicleSpawn(stream, helpers):
    return {
        'vehicle_id': stream.read_u64(),
        'pose': helpers['read_battle_pose'](stream),
    }

def _decode_ReqUnmannedVehicleTakeBack(stream, helpers):
    return {
        'vehicle_id': stream.read_u64(),
    }

def _decode_ReqUsePlaceSceneToolOperator(stream, helpers):
    return {
        'hand_item_id': stream.read_u32(),
        'scene_tool_unique_id': stream.read_u64(),
        'state': stream.read_u8(),
        'lerp_data': helpers['read_lerp_data'](stream),
    }

def _decode_ReqUseSceneTool(stream, helpers):
    return {
        'hand_item_id': stream.read_u32(),
        'scene_tool_unique_id': stream.read_u64(),
    }

def _decode_ReqVehicleInfo(stream, helpers):
    return {}

def _decode_ReqVehicleLaunchTracker(stream, helpers):
    return {
        'pos_start': helpers['read_vector3'](stream),
        'pos_ends': [helpers['read_vector3'](stream) for _ in range(stream.read_cuint())],
        'target_bids': [stream.read_u8() for _ in range(stream.read_cuint())],
    }

def _decode_ReqWallInfo(stream, helpers):
    return {}

def _decode_RspCharacterPose(stream, helpers):
    return {
        'bid': stream.read_u8(),
        'delta': helpers['read_pose_delta'](stream),
    }

def _decode_RspPing(stream, helpers):
    return {
        'timestamp': stream.read_u32(),
    }

_DECODER_BY_PACKET_CLASS = {
    'PktHeartBeat': _decode_PktHeartBeat,
    'PktVersion': _decode_PktVersion,
    'ReqActiveTracker': _decode_ReqActiveTracker,
    'ReqAddRobot': _decode_ReqAddRobot,
    'ReqArmorPackageInfo': _decode_ReqArmorPackageInfo,
    'ReqBombBulletState': _decode_ReqBombBulletState,
    'ReqBombExplosive': _decode_ReqBombExplosive,
    'ReqBombGunFire': _decode_ReqBombGunFire,
    'ReqBuffInfo': _decode_ReqBuffInfo,
    'ReqCancelThrowGrenade': _decode_ReqCancelThrowGrenade,
    'ReqChangeBlockingBoardState': _decode_ReqChangeBlockingBoardState,
    'ReqChangeReinforcedState': _decode_ReqChangeReinforcedState,
    'ReqCharacterActionAimming': _decode_ReqCharacterActionAimming,
    'ReqCharacterActionExplodeExplosive': _decode_ReqCharacterActionExplodeExplosive,
    'ReqCharacterActionHammerAttack': _decode_ReqCharacterActionHammerAttack,
    'ReqCharacterActionInstallTrapBomb': _decode_ReqCharacterActionInstallTrapBomb,
    'ReqCharacterActionMeleeAttack': _decode_ReqCharacterActionMeleeAttack,
    'ReqCharacterActionTakeOutPad': _decode_ReqCharacterActionTakeOutPad,
    'ReqCharacterActionTilt': _decode_ReqCharacterActionTilt,
    'ReqCharacterActionUninstallTrapBomb': _decode_ReqCharacterActionUninstallTrapBomb,
    'ReqCharacterChangePoseInWall': _decode_ReqCharacterChangePoseInWall,
    'ReqCharacterClimbLadder': _decode_ReqCharacterClimbLadder,
    'ReqCharacterGunFire': _decode_ReqCharacterGunFire,
    'ReqCharacterHammerAttack': _decode_ReqCharacterHammerAttack,
    'ReqCharacterInstallReinforced': _decode_ReqCharacterInstallReinforced,
    'ReqCharacterIntoWallSpace': _decode_ReqCharacterIntoWallSpace,
    'ReqCharacterJumpOn': _decode_ReqCharacterJumpOn,
    'ReqCharacterJumpOver': _decode_ReqCharacterJumpOver,
    'ReqCharacterLeaveLadder': _decode_ReqCharacterLeaveLadder,
    'ReqCharacterLeaveWallSpace': _decode_ReqCharacterLeaveWallSpace,
    'ReqCharacterLeaveWallSpaceByWindow': _decode_ReqCharacterLeaveWallSpaceByWindow,
    'ReqCharacterLerpPos': _decode_ReqCharacterLerpPos,
    'ReqCharacterMeleeAttack': _decode_ReqCharacterMeleeAttack,
    'ReqCharacterOperateBlockingBoard': _decode_ReqCharacterOperateBlockingBoard,
    'ReqCharacterOperateExplosive': _decode_ReqCharacterOperateExplosive,
    'ReqCharacterOperateShield': _decode_ReqCharacterOperateShield,
    'ReqCharacterOperation': _decode_ReqCharacterOperation,
    'ReqCharacterPose': _decode_ReqCharacterPose,
    'ReqCharacterState': _decode_ReqCharacterState,
    'ReqCharacterThrowRope': _decode_ReqCharacterThrowRope,
    'ReqClientCheatReport': _decode_ReqClientCheatReport,
    'ReqCreatePlaceSceneTool': _decode_ReqCreatePlaceSceneTool,
    'ReqDestroyBlockingBoard': _decode_ReqDestroyBlockingBoard,
    'ReqDestroySceneObject': _decode_ReqDestroySceneObject,
    'ReqDisturbedOperate': _decode_ReqDisturbedOperate,
    'ReqDropDefuser': _decode_ReqDropDefuser,
    'ReqDynamicWallInfo': _decode_ReqDynamicWallInfo,
    'ReqElectricBoxInfo': _decode_ReqElectricBoxInfo,
    'ReqEnterBattle': _decode_ReqEnterBattle,
    'ReqFoundBombTarget': _decode_ReqFoundBombTarget,
    'ReqFoundCriticalTarget': _decode_ReqFoundCriticalTarget,
    'ReqFoundDefuser': _decode_ReqFoundDefuser,
    'ReqGameInfo': _decode_ReqGameInfo,
    'ReqGamePlayerInfo': _decode_ReqGamePlayerInfo,
    'ReqGamePoints': _decode_ReqGamePoints,
    'ReqGenRobot': _decode_ReqGenRobot,
    'ReqGetBackNeuroToxinOperator': _decode_ReqGetBackNeuroToxinOperator,
    'ReqGetBackNeuroToxinTool': _decode_ReqGetBackNeuroToxinTool,
    'ReqGetBackPlaceSceneTool': _decode_ReqGetBackPlaceSceneTool,
    'ReqGetBackPlaceSceneToolOperator': _decode_ReqGetBackPlaceSceneToolOperator,
    'ReqGrenadeBegin': _decode_ReqGrenadeBegin,
    'ReqGrenadeExplosivePosNtf': _decode_ReqGrenadeExplosivePosNtf,
    'ReqGrenadeExplosivePosReport': _decode_ReqGrenadeExplosivePosReport,
    'ReqGroundMaterial': _decode_ReqGroundMaterial,
    'ReqIntoSceneTool': _decode_ReqIntoSceneTool,
    'ReqItemPosReport': _decode_ReqItemPosReport,
    'ReqKillMe': _decode_ReqKillMe,
    'ReqLeaveBattle': _decode_ReqLeaveBattle,
    'ReqLeaveSceneTool': _decode_ReqLeaveSceneTool,
    'ReqLoadProgress': _decode_ReqLoadProgress,
    'ReqMonitorPoseDelta': _decode_ReqMonitorPoseDelta,
    'ReqMonitorScanEnemies': _decode_ReqMonitorScanEnemies,
    'ReqMountedLMGInfo': _decode_ReqMountedLMGInfo,
    'ReqMoveToIntoSceneTool': _decode_ReqMoveToIntoSceneTool,
    'ReqNotifyDefuserState': _decode_ReqNotifyDefuserState,
    'ReqOperateBattle': _decode_ReqOperateBattle,
    'ReqOperateCharacter': _decode_ReqOperateCharacter,
    'ReqOperateGunReload': _decode_ReqOperateGunReload,
    'ReqOperateScene': _decode_ReqOperateScene,
    'ReqOperateTool': _decode_ReqOperateTool,
    'ReqPickUpDefuser': _decode_ReqPickUpDefuser,
    'ReqPillarGroupInfo': _decode_ReqPillarGroupInfo,
    'ReqPing': _decode_ReqPing,
    'ReqPlaceToolOperator': _decode_ReqPlaceToolOperator,
    'ReqPlayerMark': _decode_ReqPlayerMark,
    'ReqPlayersResult': _decode_ReqPlayersResult,
    'ReqQuickChat': _decode_ReqQuickChat,
    'ReqReinforcedWallInfo': _decode_ReqReinforcedWallInfo,
    'ReqRemoveNeuroToxinEffect': _decode_ReqRemoveNeuroToxinEffect,
    'ReqRemoveNeuroToxinOperator': _decode_ReqRemoveNeuroToxinOperator,
    'ReqReportThrowSceneToolFinalPosition': _decode_ReqReportThrowSceneToolFinalPosition,
    'ReqReportThrowSceneToolFinalPositionWithRelation': _decode_ReqReportThrowSceneToolFinalPositionWithRelation,
    'ReqResetItemNum': _decode_ReqResetItemNum,
    'ReqRobotFire': _decode_ReqRobotFire,
    'ReqRobotMove': _decode_ReqRobotMove,
    'ReqRoomLoaded': _decode_ReqRoomLoaded,
    'ReqScanEnemies': _decode_ReqScanEnemies,
    'ReqSecurityCameraInfo': _decode_ReqSecurityCameraInfo,
    'ReqShieldStateUpdate': _decode_ReqShieldStateUpdate,
    'ReqShockGrenadeBomb': _decode_ReqShockGrenadeBomb,
    'ReqSimpleQuintainInfo': _decode_ReqSimpleQuintainInfo,
    'ReqSimpleSceneItemInfo': _decode_ReqSimpleSceneItemInfo,
    'ReqSwitchCurrentMonitor': _decode_ReqSwitchCurrentMonitor,
    'ReqSwitchCurrentUnmannedVehicle': _decode_ReqSwitchCurrentUnmannedVehicle,
    'ReqSwitchMonitorToCharacter': _decode_ReqSwitchMonitorToCharacter,
    'ReqSwitchUnmannedVehicleToCharacter': _decode_ReqSwitchUnmannedVehicleToCharacter,
    'ReqSyncCharacterAction': _decode_ReqSyncCharacterAction,
    'ReqSyncCharacterAssistTool': _decode_ReqSyncCharacterAssistTool,
    'ReqSyncCharacterTool': _decode_ReqSyncCharacterTool,
    'ReqSyncCharacterWeaponState': _decode_ReqSyncCharacterWeaponState,
    'ReqSyncHandShieldState': _decode_ReqSyncHandShieldState,
    'ReqSyncItemState': _decode_ReqSyncItemState,
    'ReqSyncNeuroToxinPosition': _decode_ReqSyncNeuroToxinPosition,
    'ReqSyncPerformData': _decode_ReqSyncPerformData,
    'ReqSyncPlayerState': _decode_ReqSyncPlayerState,
    'ReqSyncStretchHandShieldState': _decode_ReqSyncStretchHandShieldState,
    'ReqSyncThrowSceneToolPosition': _decode_ReqSyncThrowSceneToolPosition,
    'ReqThrowGrenadeEnd': _decode_ReqThrowGrenadeEnd,
    'ReqThrowItem': _decode_ReqThrowItem,
    'ReqThrowItemDropDown': _decode_ReqThrowItemDropDown,
    'ReqThrowItemStoped': _decode_ReqThrowItemStoped,
    'ReqThrowNeuroToxin': _decode_ReqThrowNeuroToxin,
    'ReqThrowNeuroToxinEnd': _decode_ReqThrowNeuroToxinEnd,
    'ReqThrowSceneTool': _decode_ReqThrowSceneTool,
    'ReqTrapBombInstalled': _decode_ReqTrapBombInstalled,
    'ReqTrapBombUninstalled': _decode_ReqTrapBombUninstalled,
    'ReqTriggerFlashHandShield': _decode_ReqTriggerFlashHandShield,
    'ReqTriggerTrapBomb': _decode_ReqTriggerTrapBomb,
    'ReqUnmannedVehicleSpawn': _decode_ReqUnmannedVehicleSpawn,
    'ReqUnmannedVehicleTakeBack': _decode_ReqUnmannedVehicleTakeBack,
    'ReqUsePlaceSceneToolOperator': _decode_ReqUsePlaceSceneToolOperator,
    'ReqUseSceneTool': _decode_ReqUseSceneTool,
    'ReqVehicleInfo': _decode_ReqVehicleInfo,
    'ReqVehicleLaunchTracker': _decode_ReqVehicleLaunchTracker,
    'ReqWallInfo': _decode_ReqWallInfo,
    'RspCharacterPose': _decode_RspCharacterPose,
    'RspPing': _decode_RspPing,
}

def is_payload_decoder_supported(packet_class: str) -> bool:
    return str(packet_class) in _DECODER_BY_PACKET_CLASS

def get_payload_decoder_required_helpers(packet_class: str) -> list[str]:
    return list(BATTLE_PAYLOAD_DECODER_HELPERS_BY_CLASS.get(str(packet_class), []))

def decode_battle_payload_autogen(packet_class: str, stream, *, helpers=None) -> dict:
    packet_class = str(packet_class)
    decoder = _DECODER_BY_PACKET_CLASS.get(packet_class)
    if decoder is None:
        reason = BATTLE_PAYLOAD_DECODER_UNSUPPORTED_CLASSES.get(
            packet_class,
            'packet_class_not_in_schema',
        )
        raise NotImplementedError(
            f'payload decoder unsupported for {packet_class}: {reason}'
        )

    helper_map = helpers or {}
    required = BATTLE_PAYLOAD_DECODER_HELPERS_BY_CLASS.get(packet_class, [])
    missing_helpers = [key for key in required if key not in helper_map]
    if missing_helpers:
        raise KeyError(
            f'missing payload decoder helpers for {packet_class}: {missing_helpers}'
        )
    return decoder(stream, helper_map)
