// Namespace: 
public enum AkCommonOutputSettings.ChannelConfiguration.ChannelMask // TypeDefIndex: 5988
{
	// Fields
	public int value__; // 0x0
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask NONE = 0;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask FRONT_LEFT = 1;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask FRONT_RIGHT = 2;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask FRONT_CENTER = 4;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask LOW_FREQUENCY = 8;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask BACK_LEFT = 16;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask BACK_RIGHT = 32;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask BACK_CENTER = 256;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SIDE_LEFT = 512;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SIDE_RIGHT = 1024;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask TOP = 2048;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask HEIGHT_FRONT_LEFT = 4096;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask HEIGHT_FRONT_CENTER = 8192;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask HEIGHT_FRONT_RIGHT = 16384;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask HEIGHT_BACK_LEFT = 32768;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask HEIGHT_BACK_CENTER = 65536;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask HEIGHT_BACK_RIGHT = 131072;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_MONO = 4;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_0POINT1 = 8;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_1POINT1 = 12;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_STEREO = 3;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_2POINT1 = 11;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_3STEREO = 7;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_3POINT1 = 15;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_4 = 1539;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_4POINT1 = 1547;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_5 = 1543;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_5POINT1 = 1551;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_6 = 1587;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_6POINT1 = 1595;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_7 = 1591;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_7POINT1 = 1599;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_SURROUND = 259;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DPL2 = 1539;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_HEIGHT_4 = 184320;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_HEIGHT_5 = 192512;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_HEIGHT_ALL = 258048;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_222 = 22019;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_8 = 185859;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_9 = 185863;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_9POINT1 = 185871;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_10 = 187911;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_10POINT1 = 187919;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_11 = 196103;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_11POINT1 = 196111;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_11_740 = 185911;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_11POINT1_740 = 185919;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_13_751 = 196151;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_AURO_13POINT1_751 = 196159;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_5_0_2 = 22023;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_5_1_2 = 22031;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_6_0_2 = 22067;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_6_1_2 = 22075;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_6_0_4 = 185907;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_6_1_4 = 185915;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_7_0_2 = 22071;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_7_1_2 = 22079;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_7_0_4 = 185911;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_DOLBY_7_1_4 = 185919;
	public const AkCommonOutputSettings.ChannelConfiguration.ChannelMask SETUP_ALL_SPEAKERS = 261951;
}
