---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/12/19 1:00
---

local this = {}

function this.change_show_character(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    if msg.errorcode ~= 0 then
        ErrorCodeHelper.HandErrorCode(msg.errorcode);
        return
    end

    UiMgr:RemoveUi(LuaPanelNames.SelectDisplayCharacterPanel)
    PlayerData.Instance.ShowCharacterId = msg.character_id;
    PlayerGlobalStatData.Update(PlayerData.Instance.Uid, tostring(RoleStatsInfo.show_character_id), msg.character_id);
end

function this.query_role(msg)
    --Debug.Log(tostring(msg))
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    
    if msg.errorcode ~= 0 then
        ErrorCodeHelper.HandErrorCode(msg.errorcode);
        return
    end

    if msg.role == nil then
        Debug.LogError(string.format("query_role.response.data为空, uid = {%d}", msg.uid))
        return   
    end

    SprotoUtils.load_role_ResetEventStats(msg.uid, msg.role)
    local data = msg.role;
    local uid = msg.uid

    RemotePlayerData.Instance.Uid = uid
    PlayerBaseData.Update(uid, data);
    PlayerGlobalStatData.Update(uid, data.stats);
    PlayerBattleStatData.Update(uid, data.event_stats);
    PlayerUnlockedCharacterData.Update(uid, data.characters);
    PlayerSkinData.AddOrUpdate(uid, msg.show_character)

    RemotePlayerData.Instance:OnQueryRole()
end

function this.change_icon(msg)
    if msg.errorcode ~= 0 then
        ErrorCodeHelper.HandErrorCode(msg.errorcode);
        return 
    end

    local playerData = PlayerData.Instance;
    playerData.IconId = msg.icon;
    PlayerBaseData.UpdateIcon(playerData.Uid, msg.icon, string.Empty);
    PlayerBaseInfoManager.UpdateIcon(playerData.Uid, playerData.IconId, string.Empty);
end

function this.change_icon_url(msg)
    if msg.errorcode ~= 0 then
        ErrorCodeHelper.HandErrorCode(msg.errorcode);
        return
    end

    local playerData = PlayerData.Instance;
    playerData.IconUrl = msg.icon_url;
    PlayerBaseData.UpdateIcon(playerData.Uid, playerData.IconId, msg.icon_url);
    PlayerBaseInfoManager.UpdateIcon(playerData.Uid, playerData.IconId, msg.icon_url);
end

function this.update_event_stat_notify(msg)
    if (msg.event_type == EventTypeKey.ICON_UNLOCK_STATE) then
        UnlockedIconDataIns:ChangeUnlockIcons(msg.type, msg.value)
    elseif string.startswith(msg.event_type, EventTypeKey.season) then
        SeasonData.Get(PlayerData.Instance.Uid):UpdateSeasonItemValue(msg.event_type, msg.type, msg.value)
    else
        PlayerBattleStatData.Update(PlayerData.Instance.Uid, msg.event_type, msg.type, msg.value)
    end
    PlayerData.Instance:UpdateBattleStat(msg.event_type, msg.type, msg.value)
end

function this.load_role(msg)
    if msg.errorcode == 0 then
        ServerSavedClientConfigData.Instance:ResetClientConfig(msg);

        SprotoUtils.load_role_ResetEventStats(msg.uid, msg.role)

        UnlockedIconDataIns:ResetOpRecord(msg.role.client_config);

        CS.FGame.DataManager.CustomizableUiDataManager.ResetCustomizableCfg()
    end

    SprotoUtils.load_role_sendMsg(msg)
end

function this.online_status(msg)
    if msg ~= nil then
        if msg.online == false then
            PreBattleData.Instance:OnRemoteOffline(msg.uid)
        else
            PreBattleData.Instance:OnRemoteReConnect(msg.uid)
        end
    end
end

function this.create_role(msg)

    local fsmMsg = StateMessage.new(MessageType.CREATE_ROLE)
    fsmMsg.errorcode = msg.errorcode
    fsmMsg.userId = msg.uid
    HandleFSMMsg(fsmMsg)
    
    if msg.errorcode == 1206 then
        AlertManager.Instance:ShowDlg("",LoginDataManager.Instance.TempMsg,"确定",nil);
        return
    end

    if msg.errorcode ~= 0 then
        return
    end

    PlayerData.Instance.Name = msg.name

    GangplankSetPlayerInfo(msg.uid, msg.name, PlayerData.Instance.SDKServerName)

    CS.EjoySDKFB.FBPoint(CS.FBCode.ads_role_created);
end

function this.query_leaderboard(msg)
    if msg.errorcode ~= 0 then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
        return
    end

    LeaderboardDataManager.Instance:OnQueryLeaderboard(msg);
end

function this.query_friend_leaderboard(msg)
    if msg.errorcode ~= 0 then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
        return
    end

    LeaderboardDataManager.Instance:OnQueryFriendLeaderboard(msg);
end

function this.change_name(msg)
    if msg.errorcode == 0 then
        PlayerData.Instance.Name = msg.name
    end
    
    local fsmMsg = StateMessage.new(MessageType.ON_CHANGE_ROLE)
    fsmMsg.errorcode = msg.errorcode
    HandleFSMMsg(fsmMsg)
end

function this.get_skins_req(msg)
    local uid = PlayerData.Instance.Uid
    local cnt = msg.char_skins.Count
    for i = 0, cnt - 1 do
        PlayerSkinData.AddOrUpdate(uid, msg.char_skins[i])
    end
end

return this


