---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/12/20 14:19
---

local this = {}

function this.ReqCreateRoom(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    if (msg.errorcode ~= 0) then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
    end
end

function this.ReqOpenMode(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    if (msg.errorcode ~= 0) then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
    end
end

function this.ReqUserGuide(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    if (msg.errorcode ~= 0) then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
    else
        HandleFSMMsg(StateMessage.new(MessageType.ENTER_LEVELLOADINGSTATE))
    end
end

function this.RspBattleFinalResult(msg)
    local stateMsg = StateMessage.new(MessageType.GAME_BATTLE_RESULT)
    stateMsg.pkt = msg
    HandleFSMMsg(stateMsg)
end

function this.ReqRoomStart(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    if (msg.errorcode ~= 0) then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
    end
end

function this.ReqReportBadPlayer(msg)
    if msg.errorcode ~= 0 then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
        return
    end

    ReportData.Instance:Add(msg.uid);
    AlertManager.Instance:ShowDlg(LanguageMgrInst:GetString(63005), LanguageMgrInst:GetString(63006), LanguageMgrInst:GetString(63007), nil);
end

function this.RspRoomStart(msg)
    -- 匹配模式，匹配成功后播放音效
    if msg.combat_type == CombatType.rank_mode or msg.combat_type == CombatType.normal_mode or msg.combat_type == CombatType.newcomer_mode or msg.combat_type == CombatType.rookie_mode then
        GameMusicStates.PostEvent("Play_UI_Notice_Match")
    end
end

function this.RspOpenMode(msg)
    SelectCampAndModeDataIns:Reset(msg)
    HandleFSMMsg(StateMessage.new(MessageType.RSP_OPEN_MODE))
end

function this.RspUserGuideRoundStart(msg)
    print("Lua 收到引导回合信息")
    GuideDataIns:Reset(msg)
    HandleFSMMsg(StateMessage.new(MessageType.RspUserGuideRoundStart))
end

function this.RspErrorCode(msg)
    if (msg.errorcode == 0) then
        return
    end
    ErrorCodeHelper.HandErrorCode(msg.errorcode);
end

return this