---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/12/25 17:05
---

local this = {}

function this.invite_reply_req(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)

    if msg.errorcode ~= 0 then
        ErrorCodeHelper.HandErrorCode(msg.errorcode);
        return
    end
end

function this.invite_notify(msg)
    local player = msg.invite_player;
    if (player == nil) then
        error("pkt.invite_player is null")
    end

    PlayerBaseInfoManager.AddOrUpdate(
            player.uid,
            player.name,
            player.level,
            player.icon,
            player.icon_url,
            msg.invite_player.extra_arg,
            player.rank_score);

    TeamInviteData.Instance:OnInvited(player.uid, msg.identify_id, msg.combat_type)
    UiMgr:ShowUi(LuaPanelNames.InvitePanel, UILayer.Up);
end

function this.invite_req(msg)
    if msg.errorcode ~= 0 then
        ErrorCodeHelper.HandErrorCode(msg.errorcode);
    end
end

return this