---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/12/19 1:08
---

require 'SprotoHandler.SprotoUtils'

local this = {}

this.client = require("SprotoHandler.client")
this.team = require("SprotoHandler.team")
this.game = require("SprotoHandler.game")
this.invite = require("SprotoHandler.invite")

return this