---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2020/1/10 21:01
---

SprotoUtils = {}
local this = SprotoUtils

function this.UpdateTeamMember(member)
    if member == nil then
        error("Member is Nil")
    end
    
    local info = member.info;

    PlayerBaseInfoManager.AddOrUpdate(info.uid,
            info.name,
            info.level,
            info.icon,
            info.icon_url,
            string.Empty,
            info.rank_score);

    local slot = CS.FGame.RoomSlot()
    slot.PlayerUid = info.uid
    slot.IsReady = member.is_ready
    slot.CharacterSkin = info.show_character
    MatchRoomData.Instance:UpdateSlot(member.pos, slot);
end

function this.load_role_sendMsg(msg)
    local loadRoleSucc = msg.errorcode == 0
    local RoleId = loadRoleSucc and msg.uid or 0
    local name = msg.role == nil and string.Empty or msg.role.name;
    local isActive = msg.role == nil and false or msg.role.is_active;
    if loadRoleSucc == true then
        GameInstance.user:SetUserID(RoleId)
    end

    local fsmMsg = StateMessage.new(MessageType.LOAD_ROLE)
    fsmMsg.loadRoleSucc = loadRoleSucc
    fsmMsg.userId = RoleId
    fsmMsg.userName = name
    fsmMsg.isActive = isActive
    HandleFSMMsg(fsmMsg)
end

function this.load_role_ResetEventStats(uid, role)
    local seasonData = SeasonData.AddOrReset(uid, role.current_season_id)
    
    local eventStats = role.event_stats
    if eventStats == nil or eventStats.Count == 0 then
        return
    end
    
    local selfId = PlayerData.Instance.Uid

    for i = 0, eventStats.Count - 1 do
        local stat = eventStats[i]
        if stat.event_type == EventTypeKey.ICON_UNLOCK_STATE and selfId == uid then
            UnlockedIconDataIns:ResetUnlockData(stat.stats);
        elseif string.startswith(stat.event_type, EventTypeKey.season) then
            seasonData:UpdateSeasonItemValue(stat.event_type, stat.stats)
        end
    end
end

