---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/12/19 2:45
---

local SprotoSprotoType = require "SprotoHandler.SprotoSprotoType"
require "SprotoHandler.SprotoTypeMsgHandler"


local MsgIdsEnum = CS.MsgIdsEnum

local this = {}

local msgIds = {}

function this.RegistAll()
    for module, v in pairs(SprotoSprotoType) do
        for f, _ in pairs(v) do
            local id = MsgIdsEnum[module .. '_' .. f]
            if id == nil then
                Debug.LogError(string.format("sproto handler注册失败！枚举MsgIdsEnum.%s不存在", module .. '_' .. f))
            else
                table.insert(msgIds, id)
                CSharpAPI.AddMessengerListener_Sproto(id, HandleSprotoTypeMsg)
                --Debug.Log("add sproto listener : " .. tostring(id))
            end
        end
    end
end

function this.RemoveAll()
    if msgIds == nil then
        return
    end

    for _, v in ipairs(msgIds) do
        CSharpAPI.RemoveMessengerListener_Sproto(v, HandleSprotoTypeMsg)
    end
    
    msgIds = nil
end

return this

