---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/12/18 14:23
---
local SprotoSprotoType = require "SprotoHandler.SprotoSprotoType"

local _loadedHandler = {}

local function _handle_msg( msg)
    if DEFINE_SPROTOHandler_Log then
        print(msg:GetType(), msg)
    end
    
    local msgType = msg:GetType().FullName
    if string.IsNullOrEmpty(msgType) then
        Debug.LogError("msgType为空")
        return
    end

    local splits = string.Split(msgType, '.+')
    if splits == nil or #splits < 3 or splits[1] ~= "SprotoSprotoType" then
        Debug.LogError(string.format("msgType:%s 必须在SprotoSprotoType命名空间,且至少3段", tostring(msgType)))
        return
    end

    local handlerTableName = splits[2]

    if not _loadedHandler[handlerTableName] then
        require("SprotoHandler." .. handlerTableName)
        _loadedHandler[handlerTableName] = true
    end

    local subTypeHandler = SprotoSprotoType[handlerTableName]
    if subTypeHandler == nil then
        Debug.LogError(string.format("未实现协议%s对应处理类型SprotoSprotoType.%s", msgType, splits[2]))
        return
    end

    local handlerFunc = subTypeHandler[splits[3]]
    if handlerFunc == nil then
        Debug.LogError(string.format("未实现协议%s的处理函数", msgType))
        return
    end

    handlerFunc(msg)
end

local function _error_handler(str)
    Debug.LogError(debug.traceback(str))
end

function HandleSprotoTypeMsg(msg)
    xpcall(_handle_msg, _error_handler, msg)
end 
