---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/12/20 11:41
---

local this = {}

function this.create_team_req(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    if (msg.errorcode ~= 0) then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
    end
end

function this.leave_team_req(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    if (msg.errorcode ~= 0) then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
    else
        if MatchRoomDataIns.CombatType == CS_CombatType.rank_mode then
            UiMgr:ShowUi(LuaPanelNames.RankPanel, UILayer.Up)
        end
    end
end

function this.team_join_match_req(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    if (msg.errorcode ~= 0) then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
    end
end

function this.team_quit_match_req(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    if (msg.errorcode ~= 0) then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
    end
end

function this.return_team_req(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    ViewManager:CloseView(typeof(CS.Game.UI.UIBattle. UIBattleScoreResultControll))

    if msg.errorcode == 0 then
        HandleFSMMsg(StateMessage.new(MessageType.ReturnToTeam))
    else
        HandleFSMMsg(StateMessage.new(MessageType.ForceToLobby))
    end
end

function this.return_hall_req(msg)
    UiMgr:HideUi(LuaPanelNames.WaitPktPanel)
    ViewManager:CloseView(typeof(CS.Game.UI.UIBattle. UIBattleScoreResultControll))
    ProtocolParser.ReceivePackage("ForceToLobby")
end

function this.chat_enter_team_req(msg)
    if (msg.errorcode ~= 0) then
        ErrorCodeHelper.HandErrorCode(msg.errorcode)
    end
end

function this.team_sync_notify(msg)
    if msg.team_data == nil then
        Debug.LogError("team_sync_notify.team_data is nil")
        return
    end

    TeamInviteData.Instance:Clear();
    MatchRoomData.ResetByPkt(msg.team_data);
end

function this.team_member_enter_notify(msg)
    SprotoUtils.UpdateTeamMember(msg.new_member)
end

function this.member_sync_notify(msg)
    SprotoUtils.UpdateTeamMember(msg.member)
end

function this.team_member_leave_notify(msg)
    if (msg.leave_pos == MatchRoomData.Instance.SelfIndex) then
        local fsmMsg = StateMessage.new(MessageType.SelfLeaveRoom)
        fsmMsg.leaveType = msg.leave_type
        fsmMsg.combatType = 
        HandleFSMMsg(fsmMsg)
        Message.Dispatch(MessageKey.OnSelfLeaveMatchRoom, msg.leave_type);
        MatchRoomData.Instance:Clear();
    else
        MatchRoomData.Instance:RemoveAt(msg.leave_pos);
    end
end

function this.team_match_punish_notify(msg)
    UiMgr:ShowUi(LuaPanelNames.PopPunishPanel, UILayer.Up, msg.combat_type, msg.punish_timeout, msg.punish_battle_cnt);
end

function this.match_success_notify(msg)
    MatchConfirmData.Instance:ResetFromPkt(msg);
    MatchRoomData.Instance:CancelMatch();
    Message.Dispatch(MessageKey.OnMatchTeamConfirmEnter);
    SendMsgHelp.ReqConfirmMatch();
end

return this