---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/8/21 17:00
---

MessageKey = {
    OnUIShow = "OnUIShow", -- UI打开时的通用通知
    OnUIRemove = "OnUIRemove", -- UI关闭时的通用通知
    
    OnUpdatePlayerData = "OnUpdatePlayerData", -- 玩家数据更新
    OnLeaderboardUpdate  = "OnLeaderboardUpdate", -- 排行榜更新
    OnMatchRoomMemberUpdate = "OnMatchRoomMemberUpdate", -- 匹配队伍成员更新
    OnMatchRoomInitialize = "OnMatchRoomInitialize", -- 匹配队伍初始化完成
    OnSelfLeaveMatchRoom = "OnSelfLeaveMatchRoom", -- 玩家自己离开匹配队伍
    MatchConfirmUpdate = "MatchConfirmUpdate", -- 匹配确认更新
    OnMatchRoomStateChange = "OnMatchRoomStateChange", -- 匹配状态变化
    
    OnMatchConfirmTimeOut = "OnMatchConfirmTimeOut",        -- 匹配超时
    OnMatchTeamConfirmEnter = "OnMatchTeamConfirmEnter",  -- 进入匹配确认
    
    --好友
    OnOpenPage = "OnOpenPage",
    OnSearchPlayerRet = "OnSearchPlayerRet",
    OnRefreshFriendinfoList = "OnRefreshFriendinfoList",
    OnFriendStateChange = "OnFriendStateChange",
    GetApplyListSucc = "GetApplyListSucc",
    OnRefreshFBFriendinfoList = "OnRefreshFBFriendinfoList",

    --聊天
    OnReceivedMsg = "OnReceivedMsg",
    OnChooseFriendChat = "OnChooseFriendChat",
    OnFriendBtnClick = "OnFriendBtnClick",
    RefreshRedPoint = "RefreshRedPoint",
    OnGroupBtnClick = "OnGroupBtnClick",
    OnSelfLeaveRoom = "OnSelfLeaveRoom",   --自己离开房间
    
    -- 个人信息
    OnClickPlayerInfo = "OnClickPlayerInfo",  -- 点击玩家图像
    OnPersonalBaseInfoChange = "OnPersonalBaseInfoChange",

    --邮件
    OnClickMailNode = "OnClickMailNode",    --点击邮件列表项
    OnSelectMail = "OnSelectMail",  --选中邮件
    OnDeselectAllMail = "OnDeselectAllMail",  --清除所有邮件选中状态

    --公告
    OnGetAnnouncement = "OnGetAnnouncement",    --获取到公告
    OnClickBillboardTab = "OnClickBillboardTab",    --点击公告项
    OnSelectBillboardTab = "OnSelectBillboardTab",  --选中公告项

    --局内公告
    OnGetInternalAnnouncement = "OnGetInternalAnnouncement",    --获取到公告
    OnClickBillboardForHallTab = "OnClickBillboardForHallTab",    --点击公告项
    OnSelectBillboardForHallTab = "OnSelectBillboardForHallTab",  --选中公告项

    --跑马灯
    OnNewRealtimeNoticeInfo = "OnNewRealtimeNoticeInfo",    --新跑马灯消息
    OnRealtimeNoticeChangeMode = "OnRealtimeNoticeChangeMode",  --跑马灯模式转换
    -- 选择战斗服
    OnRoomBattleZoneChange = "OnRoomBattleZoneChange",
    MsgClickBattleZoneNode = "MsgClickBattleZoneNode", -- 点击选战斗区域入口
    --排位规则
    OnClickRankRuleTab = "OnClickRankRuleTab",    --点击规则左侧标签
    OnSelectRankRuleTab = "OnSelectRankRuleTab",  --选中规则左侧标签
    OnSelectRankRuleContent = "OnSelectRankRuleContent",    --选中某一规则内容


    --商城
    GiftBuyOver = "GiftBuyOver", 
    OnGetStoreItems = "OnGetStoreItems",
    --获得奖励
    OnGetRewardNotify = "OnGetRewardNotify",
    --开宝箱
    OpenBoxOnSelectBoxNode = "OpenBoxOnSelectBoxNode", 
    OpenBoxOnDeselectAllBoxNode = "OpenBoxOnDeselectAllBoxNode", 
    OpenBoxOnClickBoxNodeDetail = "OpenBoxOnClickBoxNodeDetail", 
    OpenBoxOnSelectItemNode = "OpenBoxOnSelectItemNode", 
    OpenBoxOnDeselectAllItemNode = "OpenBoxOnDeselectAllItemNode", 
    OpenBoxOnClickItemListNodeBack = "OpenBoxOnClickItemListNodeBack", 
    --获得宝箱
    BoxRewardClosePopPanel = "BoxRewardClosePopPanel",
    --获得礼包
    BundleRewardClosePopPanel = "BundleRewardClosePopPanel",

    --招募
    EnlistSyncChanged = "EnlistSyncChanged",

    --活动领取道具
    ActiveRewardEvent = "ActiveRewardEvent" , 

    --刷新解锁
    WarehosueUpdateLockChar = "WarehosueUpdateLockChar"


}