---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/8/21 18:01
---

-- event_keys
StatsGroupKey = {
    EVENT_TYPE_ALL = "EVENT_TYPE_ALL",
    EVENT_TYPE_RANK = "EVENT_TYPE_RANK",
    EVENT_TYPE_NORMAL = "EVENT_TYPE_NORMAL",
}

EventTypeKey = {
    ICON_UNLOCK_STATE = "ICON_UNLOCK_STATE",
    season = "season",
}

