---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/9/18 13:38
---

-- UiCtrl中的函数名，可以供CallUiFunction使用

UiFuncName = {
    OnResetData = "OnResetData",
}