return{
    battle_mode = {
        {
            additional_skill = {
            },
            additional_skill_target = {
            },
            allow_leave = 0,
            allow_region_selection_of_defender = 0,
            allow_return_when_pre_battle = 0,
            allow_round_replay = 1,
            battle_time = 240,
            can_selected_in_room = 1,
            choose_character_time = 45,
            class_type = "EliminateThreat",
            defuser_time = 0,
            hold_on_time = 15,
            id = 1,
            infinite_bullet = 0,
            infinite_item = 0,
            lang_index = 51300,
            mode_choose_bg = "img_RoomSet_mode_1",
            name = "肃清威胁",
            prepare_time = 45,
            reset_item = 0,
            script = "ModeEliminateThreat",
            select_available = 1,
            select_weight = 100,
            show_other_team_info = 1,
        },
        {
            additional_skill = {
            },
            additional_skill_target = {
            },
            allow_leave = 1,
            allow_region_selection_of_defender = 1,
            allow_return_when_pre_battle = 0,
            allow_round_replay = 0,
            battle_time = 1800,
            can_selected_in_room = 0,
            choose_character_time = 0,
            class_type = "EliminateThreatGuide",
            defuser_time = 0,
            hold_on_time = 5,
            id = 2,
            infinite_bullet = 1,
            infinite_item = 0,
            lang_index = 52300,
            mode_choose_bg = "img_RoomSet_mode_1",
            name = "肃清威胁引导进攻方",
            prepare_time = 0,
            reset_item = 0,
            script = "ModeEliminateThreatGuide",
            select_available = 0,
            select_weight = 0,
            show_other_team_info = 1,
        },
        {
            additional_skill = {
            },
            additional_skill_target = {
            },
            allow_leave = 1,
            allow_region_selection_of_defender = 1,
            allow_return_when_pre_battle = 1,
            allow_round_replay = 0,
            battle_time = 2700,
            can_selected_in_room = 0,
            choose_character_time = 300,
            class_type = "Training",
            defuser_time = 0,
            hold_on_time = 0,
            id = 3,
            infinite_bullet = 1,
            infinite_item = 0,
            lang_index = 52302,
            mode_choose_bg = "img_RoomSet_mode_1",
            name = "训练场",
            prepare_time = 0,
            reset_item = 1,
            script = "ModeTraining",
            select_available = 0,
            select_weight = 0,
            show_other_team_info = 0,
        },
        {
            additional_skill = {
                6,
                7,
            },
            additional_skill_target = {
                1,
                2,
            },
            allow_leave = 0,
            allow_region_selection_of_defender = 0,
            allow_return_when_pre_battle = 0,
            allow_round_replay = 1,
            battle_time = 240,
            can_selected_in_room = 1,
            choose_character_time = 45,
            class_type = "Bomb",
            defuser_time = 45,
            hold_on_time = 0,
            id = 4,
            infinite_bullet = 0,
            infinite_item = 0,
            lang_index = 51301,
            mode_choose_bg = "img_RoomSet_mode_2",
            name = "炸弹",
            prepare_time = 45,
            reset_item = 0,
            script = "ModeBomb",
            select_available = 1,
            select_weight = 100,
            show_other_team_info = 1,
        },
    },
}