return{
    character = {
        [1] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "10.0",
            camp = 1,
            choose_limit = 0,
            default_body_skin = 90013000,
            default_head_skin = 90012000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "新人没有特殊道具，但可以装备两件通用道具",
            desc_lang_index = 10100,
            difficulty_level = 1,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 0,
            hp = 100,
            icon = "zy_icon_char00.png",
            id = 1,
            main_skill = {
                295,
                297,
            },
            name = "新人",
            name_lang_index = 10000,
            pic = "char00.png",
            preload_particle_id_array = {
                1101,
                1102,
            },
            primary_weapon = {
                10086,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 3,
            speed_level = 2,
            sub_skills = {
                299,
                298,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [2] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "20.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90023000,
            default_head_skin = 90022000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "使用破墙槌来突破可以破坏的表面和已经加固的墙面",
            desc_lang_index = 10101,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char07.png",
            id = 2,
            main_skill = {
                201,
            },
            name = "大锤",
            name_lang_index = 10001,
            pic = "char07.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10058,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 4,
            speed_level = 2,
            sub_skills = {
                299,
                298,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [3] = {
            armor_level = 1,
            army = "",
            available = 1,
            bag_id_index = "30.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90033000,
            default_head_skin = 90032000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "发射一枚爆破箭头粘附在目标表面并自动引爆",
            desc_lang_index = 10102,
            difficulty_level = 1,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char02.png",
            id = 3,
            main_skill = {
                202,
            },
            name = "野火",
            name_lang_index = 10002,
            pic = "char02.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10086,
                10035,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 1,
            speed_level = 3,
            sub_skills = {
                298,
                297,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [4] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "40.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90043000,
            default_head_skin = 90042000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "设置热切炸药来破坏已经加固的墙面和活动地板",
            desc_lang_index = 10103,
            difficulty_level = 1,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char09.png",
            id = 4,
            main_skill = {
                203,
            },
            name = "火山",
            name_lang_index = 10003,
            pic = "char09.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10007,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 2,
            speed_level = 2,
            sub_skills = {
                298,
                295,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [5] = {
            armor_level = 2,
            army = "",
            available = 0,
            bag_id_index = "50.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90053000,
            default_head_skin = 90052000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "",
            desc_lang_index = 0,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "",
            id = 5,
            main_skill = {
                204,
            },
            name = "毒刺",
            name_lang_index = 0,
            pic = "",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10086,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 0,
            speed_level = 2,
            sub_skills = {
                295,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [6] = {
            armor_level = 3,
            army = "",
            available = 1,
            bag_id_index = "60.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90063000,
            default_head_skin = 90062000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "装备防弹的伸缩护盾和手枪，护盾伸展开后可以提供前方全身的保护",
            desc_lang_index = 10104,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char01.png",
            id = 6,
            main_skill = {
                205,
            },
            name = "磐石",
            name_lang_index = 10004,
            pic = "char01.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10083,
            },
            secondary_weapon = {
                10064,
                10065,
            },
            sound_id = 1,
            speed_level = 1,
            sub_skills = {
                297,
                298,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [7] = {
            armor_level = 1,
            army = "",
            available = 1,
            bag_id_index = "70.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90073000,
            default_head_skin = 90072000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "切换到放大瞄准镜，远距离轻松打击敌人",
            desc_lang_index = 10105,
            difficulty_level = 3,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char12.png",
            id = 7,
            main_skill = {
                206,
            },
            name = "鹰眼",
            name_lang_index = 10005,
            pic = "char12.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10052,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 2,
            speed_level = 3,
            sub_skills = {
                297,
                295,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [8] = {
            armor_level = 2,
            army = "",
            available = 0,
            bag_id_index = "80.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90083000,
            default_head_skin = 90082000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "使用战术侦查镜来观察内部的敌人",
            desc_lang_index = 0,
            difficulty_level = 3,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char02.png",
            id = 8,
            main_skill = {
                225,
            },
            name = "五眼",
            name_lang_index = 0,
            pic = "char02.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10086,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 2,
            speed_level = 2,
            sub_skills = {
                295,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [9] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "90.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90093000,
            default_head_skin = 90092000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "操控两台追踪无人机发射特殊的追踪弹来定位被击中的敌人",
            desc_lang_index = 10106,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char11.png",
            id = 9,
            main_skill = {
                210,
            },
            name = "幽灵",
            name_lang_index = 10006,
            pic = "char11.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10087,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 3,
            speed_level = 2,
            sub_skills = {
                295,
                299,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [10] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "100.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90103000,
            default_head_skin = 90102000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "投掷电磁脉冲手雷，可以使摄像头失效，并且摧毁敌方电子设备",
            desc_lang_index = 10107,
            difficulty_level = 1,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char10.png",
            id = 10,
            main_skill = {
                214,
            },
            name = "磁场",
            name_lang_index = 10007,
            pic = "char10.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10001,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 5,
            speed_level = 2,
            sub_skills = {
                295,
                299,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle02_aoc",
        },
        [11] = {
            armor_level = 3,
            army = "",
            available = 1,
            bag_id_index = "110.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90113000,
            default_head_skin = 90112000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "对自己使用强化激素，一段时间内移动速度增加、血量暂时增加，并且可以直接跳过完整的封阻门窗。倒地后仍然可以使用。",
            desc_lang_index = 10115,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char23.png",
            id = 11,
            main_skill = {
                226,
            },
            name = "猎豹",
            name_lang_index = 10015,
            pic = "char23.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10006,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 1,
            speed_level = 1,
            sub_skills = {
                297,
                298,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [12] = {
            armor_level = 1,
            army = "",
            available = 1,
            bag_id_index = "120.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90123000,
            default_head_skin = 90122000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "使用安装在盾牌上的闪光装置，可以使前方锥形范围内的敌人致盲",
            desc_lang_index = 10117,
            difficulty_level = 3,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char21.png",
            id = 12,
            main_skill = {
                217,
            },
            name = "闪光",
            name_lang_index = 10017,
            pic = "char21.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10082,
            },
            secondary_weapon = {
                10088,
            },
            sound_id = 2,
            speed_level = 3,
            sub_skills = {
                297,
                295,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [13] = {
            armor_level = 1,
            army = "",
            available = 0,
            bag_id_index = "130.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90133000,
            default_head_skin = 90132000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "神秘新干员",
            desc_lang_index = 0,
            difficulty_level = 0,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char02.png",
            id = 13,
            main_skill = {
                202,
            },
            name = "神秘",
            name_lang_index = 0,
            pic = "char02.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10086,
                10036,
            },
            secondary_weapon = {
                10065,
            },
            sound_id = 1,
            speed_level = 3,
            sub_skills = {
                298,
                297,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [14] = {
            armor_level = 2,
            army = "",
            available = 0,
            bag_id_index = "140.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90143000,
            default_head_skin = 90142000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "神秘新干员",
            desc_lang_index = 0,
            difficulty_level = 0,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char11.png",
            id = 14,
            main_skill = {
                210,
            },
            name = "神秘",
            name_lang_index = 0,
            pic = "char11.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10087,
                10036,
            },
            secondary_weapon = {
                10065,
            },
            sound_id = 3,
            speed_level = 2,
            sub_skills = {
                295,
                299,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [15] = {
            armor_level = 2,
            army = "",
            available = 0,
            bag_id_index = "150.0",
            camp = 1,
            choose_limit = 1,
            default_body_skin = 90153000,
            default_head_skin = 90152000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "神秘新干员",
            desc_lang_index = 0,
            difficulty_level = 0,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char10.png",
            id = 15,
            main_skill = {
                214,
            },
            name = "神秘",
            name_lang_index = 0,
            pic = "char10.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10086,
                10036,
            },
            secondary_weapon = {
                10065,
            },
            sound_id = 5,
            speed_level = 2,
            sub_skills = {
                295,
                299,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [101] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "1010.0",
            camp = 2,
            choose_limit = 0,
            default_body_skin = 91013002,
            default_head_skin = 91012002,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "新人没有特殊道具，但可以装备两件通用道具",
            desc_lang_index = 10100,
            difficulty_level = 1,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 0,
            hp = 100,
            icon = "zy_icon_char00_01.png",
            id = 101,
            main_skill = {
                195,
            },
            name = "新人",
            name_lang_index = 10000,
            pic = "char00_01.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10036,
                10021,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 2,
            speed_level = 2,
            sub_skills = {
                199,
                197,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [102] = {
            armor_level = 2,
            army = "",
            available = 0,
            bag_id_index = "1020.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91023000,
            default_head_skin = 91022000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "使用比一般障碍物有更好抗性的防弹装甲板来封阻窗户和门",
            desc_lang_index = 0,
            difficulty_level = 1,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char14.png",
            id = 102,
            main_skill = {
                101,
            },
            name = "米迦勒",
            name_lang_index = 0,
            pic = "char14.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10022,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 3,
            speed_level = 2,
            sub_skills = {
                197,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [103] = {
            armor_level = 3,
            army = "",
            available = 1,
            bag_id_index = "1030.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91033000,
            default_head_skin = 91032000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "放置内有防弹护甲的补给包供队伍使用，防弹护甲可以降低受到的伤害",
            desc_lang_index = 10108,
            difficulty_level = 1,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char08.png",
            id = 103,
            main_skill = {
                102,
            },
            name = "壁垒",
            name_lang_index = 10008,
            pic = "char08.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10022,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 1,
            speed_level = 1,
            sub_skills = {
                197,
                198,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [104] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "1040.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91043000,
            default_head_skin = 91042000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "在窗户和门框上布置触发后会爆炸的陷阱",
            desc_lang_index = 10109,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char13.png",
            id = 104,
            main_skill = {
                103,
            },
            name = "孤狼",
            name_lang_index = 10009,
            pic = "char13.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10021,
                10035,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 2,
            speed_level = 2,
            sub_skills = {
                198,
                199,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [105] = {
            armor_level = 3,
            army = "",
            available = 1,
            bag_id_index = "1050.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91053000,
            default_head_skin = 91052000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "部署附有防弹护盾的机枪提供强大的火力支援",
            desc_lang_index = 10110,
            difficulty_level = 1,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char03.png",
            id = 105,
            main_skill = {
                104,
            },
            name = "火舌",
            name_lang_index = 10010,
            pic = "char03.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10023,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 4,
            speed_level = 1,
            sub_skills = {
                197,
                195,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [106] = {
            armor_level = 1,
            army = "",
            available = 1,
            bag_id_index = "1060.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91063000,
            default_head_skin = 91062000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "投掷可以将金属道具通电的电子装置，并对任何接触到的物体造成伤害",
            desc_lang_index = 10111,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char04.png",
            id = 106,
            main_skill = {
                105,
            },
            name = "闪电",
            name_lang_index = 10011,
            pic = "char04.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10019,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 3,
            speed_level = 3,
            sub_skills = {
                195,
                199,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [107] = {
            armor_level = 3,
            army = "",
            available = 0,
            bag_id_index = "1070.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91073000,
            default_head_skin = 91072000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "",
            desc_lang_index = 0,
            difficulty_level = 3,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "",
            id = 107,
            main_skill = {
                106,
            },
            name = "黑镜",
            name_lang_index = 0,
            pic = "",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10022,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 0,
            speed_level = 1,
            sub_skills = {
                197,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [108] = {
            armor_level = 1,
            army = "",
            available = 1,
            bag_id_index = "1080.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91083000,
            default_head_skin = 91082000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "放置干扰敌方无人机和其他电子设备的装置",
            desc_lang_index = 10112,
            difficulty_level = 1,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char17.png",
            id = 108,
            main_skill = {
                114,
            },
            name = "寂静",
            name_lang_index = 10012,
            pic = "char17.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10024,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 4,
            speed_level = 3,
            sub_skills = {
                199,
                195,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [109] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "1090.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91093000,
            default_head_skin = 91092000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "毒素陷阱会将释放有毒气体，使敌人逐渐失去生命值",
            desc_lang_index = 10113,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char06.png",
            id = 109,
            main_skill = {
                112,
            },
            name = "蝮蛇",
            name_lang_index = 10013,
            pic = "char06.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10031,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 4,
            speed_level = 2,
            sub_skills = {
                198,
                197,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [110] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "1100.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91103000,
            default_head_skin = 91102000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "投掷可以粘附在物体上的毒气烟雾弹，引爆后释放出大范围有毒烟雾。干员佩戴防毒面具，毒雾中可确保自身安全",
            desc_lang_index = 10114,
            difficulty_level = 3,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char20.png",
            id = 110,
            main_skill = {
                117,
            },
            name = "沼泽",
            name_lang_index = 10014,
            pic = "char20.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10025,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 4,
            speed_level = 2,
            sub_skills = {
                195,
                198,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [111] = {
            armor_level = 1,
            army = "",
            available = 1,
            bag_id_index = "1110.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91113000,
            default_head_skin = 91112000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "投掷可以在一定范围内感知敌方干员存在的生命体探测装置，装置可以粘附在物体表面",
            desc_lang_index = 10116,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char05.png",
            id = 111,
            main_skill = {
                125,
            },
            name = "狼蛛",
            name_lang_index = 10016,
            pic = "char05.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10028,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 5,
            speed_level = 3,
            sub_skills = {
                195,
                199,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle02_aoc",
        },
        [112] = {
            armor_level = 2,
            army = "",
            available = 1,
            bag_id_index = "1120.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91123000,
            default_head_skin = 91122000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "放置在水平地面或墙面的磁力防御装置，可以吸附球形范围内的金属类爆炸物并摧毁它们",
            desc_lang_index = 10118,
            difficulty_level = 2,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char18.png",
            id = 112,
            main_skill = {
                118,
            },
            name = "黑洞",
            name_lang_index = 10018,
            pic = "char18.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10026,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 2,
            speed_level = 2,
            sub_skills = {
                198,
                197,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [113] = {
            armor_level = 1,
            army = "",
            available = 0,
            bag_id_index = "1130.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91133000,
            default_head_skin = 91132000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "神秘新干员",
            desc_lang_index = 0,
            difficulty_level = 0,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char17.png",
            id = 113,
            main_skill = {
                114,
            },
            name = "神秘",
            name_lang_index = 0,
            pic = "char17.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10023,
                10036,
            },
            secondary_weapon = {
                10074,
                10065,
            },
            sound_id = 4,
            speed_level = 3,
            sub_skills = {
                199,
                195,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [114] = {
            armor_level = 2,
            army = "",
            available = 0,
            bag_id_index = "1140.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91143000,
            default_head_skin = 91142000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "神秘新干员",
            desc_lang_index = 0,
            difficulty_level = 0,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char06.png",
            id = 114,
            main_skill = {
                112,
            },
            name = "神秘",
            name_lang_index = 0,
            pic = "char06.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10031,
                10036,
            },
            secondary_weapon = {
                10065,
            },
            sound_id = 4,
            speed_level = 2,
            sub_skills = {
                198,
                197,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [115] = {
            armor_level = 2,
            army = "",
            available = 0,
            bag_id_index = "1150.0",
            camp = 2,
            choose_limit = 1,
            default_body_skin = 91153000,
            default_head_skin = 91152000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "神秘新干员",
            desc_lang_index = 0,
            difficulty_level = 0,
            dying_hp = 40,
            dying_time = 120,
            has_unique_skill = 1,
            hp = 100,
            icon = "zy_icon_char20.png",
            id = 115,
            main_skill = {
                117,
            },
            name = "神秘",
            name_lang_index = 0,
            pic = "char20.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10025,
                10036,
            },
            secondary_weapon = {
                10065,
            },
            sound_id = 4,
            speed_level = 2,
            sub_skills = {
                195,
                198,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [10001] = {
            armor_level = 1,
            army = "",
            available = 0,
            bag_id_index = "100010.0",
            camp = 2,
            choose_limit = 0,
            default_body_skin = 90013000,
            default_head_skin = 90012000,
            default_skill1 = 0,
            default_skill2 = 0,
            default_skill3 = 200,
            desc = "新人没有特殊道具，但可以装备两件通用道具",
            desc_lang_index = 10100,
            difficulty_level = 0,
            dying_hp = 0,
            dying_time = 1,
            has_unique_skill = 0,
            hp = 100,
            icon = "cainiao_icon.png",
            id = 10001,
            main_skill = {
                195,
            },
            name = "恐怖分子（训练用）",
            name_lang_index = 0,
            pic = "char00_01.png",
            preload_particle_id_array = {
            },
            primary_weapon = {
                10036,
                10021,
            },
            secondary_weapon = {
                10065,
            },
            sound_id = 2,
            speed_level = 3,
            sub_skills = {
                199,
                197,
            },
            trigger_skills = {
                2,
                194,
                193,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
        [10002] = {
            armor_level = 2,
            army = "",
            available = 0,
            bag_id_index = "100020.0",
            camp = 1,
            choose_limit = 0,
            default_body_skin = 90013000,
            default_head_skin = 90012000,
            default_skill1 = 0,
            default_skill2 = 293,
            default_skill3 = 200,
            desc = "新人没有特殊道具，但可以装备两件通用道具",
            desc_lang_index = 10100,
            difficulty_level = 1,
            dying_hp = 0,
            dying_time = 1,
            has_unique_skill = 0,
            hp = 100,
            icon = "zy_icon_char00.png",
            id = 10002,
            main_skill = {
                295,
                297,
            },
            name = "新人",
            name_lang_index = 0,
            pic = "char00.png",
            preload_particle_id_array = {
                1101,
                1102,
            },
            primary_weapon = {
                10086,
                10036,
            },
            secondary_weapon = {
                10065,
            },
            sound_id = 3,
            speed_level = 2,
            sub_skills = {
                299,
                298,
            },
            trigger_skills = {
                2,
                301,
                294,
            },
            ware_house_default_aoc = "p2_char_avatar@warehouse_notsuit_universal_idle01_aoc",
        },
    },
}