return{
    error_code = {
        ACTIVE_CODE_ALEADY_ACTIVE = {
            desc = "激活码没有设定使用效果",
            id = 1504,
            language_id = 0,
            message_id = 1108,
            name = "ACTIVE_CODE_ALEADY_ACTIVE",
        },
        ACTIVE_CODE_GET_LOCK_FAIL = {
            desc = "当前有其他人正在使用同一个激活码：繁忙，重试",
            id = 1507,
            language_id = 0,
            message_id = 1110,
            name = "ACTIVE_CODE_GET_LOCK_FAIL",
        },
        ACTIVE_CODE_NO_ACTION = {
            desc = "激活码平台方错误",
            id = 1503,
            language_id = 0,
            message_id = 1107,
            name = "ACTIVE_CODE_NO_ACTION",
        },
        ACTIVE_CODE_TYPE_UNUSABLE = {
            desc = "激活码类型不在时效内 / 不满足激活码类型设定的领取条件",
            id = 1502,
            language_id = 0,
            message_id = 1106,
            name = "ACTIVE_CODE_TYPE_UNUSABLE",
        },
        ACTIVE_CODE_UNUSABLE = {
            desc = "无激活码/激活码次数已用完",
            id = 1501,
            language_id = 0,
            message_id = 1105,
            name = "ACTIVE_CODE_UNUSABLE",
        },
        ACTIVE_CODE_USED = {
            desc = "激活码类型设定只能使用一次，且当前玩家已使用过同类型激活码",
            id = 1506,
            language_id = 0,
            message_id = 1109,
            name = "ACTIVE_CODE_USED",
        },
        ALREADY_IN_ROOME = {
            desc = "已经在房间中",
            id = 1007,
            language_id = 0,
            message_id = 0,
            name = "ALREADY_IN_ROOME",
        },
        ALREADY_RECRUITED = {
            desc = "招募关系建立失败，每个账号只能接受一次招募邀请",
            id = 2200,
            language_id = 0,
            message_id = 850,
            name = "ALREADY_RECRUITED",
        },
        BATTLE_ZONE_INVALID = {
            desc = "无效的BATTLE区域id",
            id = 1318,
            language_id = 0,
            message_id = 418,
            name = "BATTLE_ZONE_INVALID",
        },
        CANCEL_MATCH_ERROR = {
            desc = "服务器错误-1309（取消匹配失效）",
            id = 1309,
            language_id = 0,
            message_id = 2009,
            name = "CANCEL_MATCH_ERROR",
        },
        CANNOT_KICK_SELF = {
            desc = "非法请求-1303（不能踢自己）",
            id = 1303,
            language_id = 0,
            message_id = 2007,
            name = "CANNOT_KICK_SELF",
        },
        CHARACTER_ALREADY_UNLOCKED = {
            desc = "职业已经解锁",
            id = 1208,
            language_id = 0,
            message_id = 0,
            name = "CHARACTER_ALREADY_UNLOCKED",
        },
        CHARACTER_CANT_CHOOSE = {
            desc = "无法选择该角色",
            id = 1200,
            language_id = 0,
            message_id = 0,
            name = "CHARACTER_CANT_CHOOSE",
        },
        CHARACTER_NOT_UNLOCKED = {
            desc = "角色未解锁",
            id = 1401,
            language_id = 0,
            message_id = 0,
            name = "CHARACTER_NOT_UNLOCKED",
        },
        CONFIG_ERROR = {
            desc = "配置错误-102",
            id = 102,
            language_id = 0,
            message_id = 2003,
            name = "CONFIG_ERROR",
        },
        CREATE_ROOM_BUSY = {
            desc = "创建房间太频繁，处于时间限制中",
            id = 366,
            language_id = 0,
            message_id = 425,
            name = "CREATE_ROOM_BUSY",
        },
        DIAMOND_NOT_ENOUGH = {
            desc = "钻石不足",
            id = 1209,
            language_id = 0,
            message_id = 0,
            name = "DIAMOND_NOT_ENOUGH",
        },
        ERROR_CODE_2000000 = {
            desc = "操作成功",
            id = 301,
            language_id = 0,
            message_id = 3001,
            name = "ERROR_CODE_2000000",
        },
        ERROR_CODE_2001000 = {
            desc = "存在游客数据及第三方帐号未绑定，提示玩家绑定",
            id = 302,
            language_id = 0,
            message_id = 3002,
            name = "ERROR_CODE_2001000",
        },
        ERROR_CODE_4000000 = {
            desc = "请求参数错误",
            id = 303,
            language_id = 0,
            message_id = 3003,
            name = "ERROR_CODE_4000000",
        },
        ERROR_CODE_4000001 = {
            desc = "业务参数错误",
            id = 304,
            language_id = 0,
            message_id = 3004,
            name = "ERROR_CODE_4000001",
        },
        ERROR_CODE_4001001 = {
            desc = "游戏账号不存在",
            id = 305,
            language_id = 0,
            message_id = 3005,
            name = "ERROR_CODE_4001001",
        },
        ERROR_CODE_4001002 = {
            desc = "该第三方帐号已绑定游戏账号",
            id = 306,
            language_id = 0,
            message_id = 3006,
            name = "ERROR_CODE_4001002",
        },
        ERROR_CODE_4001003 = {
            desc = "游戏账号已绑定此类第三方账号",
            id = 307,
            language_id = 0,
            message_id = 3007,
            name = "ERROR_CODE_4001003",
        },
        ERROR_CODE_4001004 = {
            desc = "第三方账号已经在平台创建",
            id = 308,
            language_id = 0,
            message_id = 3008,
            name = "ERROR_CODE_4001004",
        },
        ERROR_CODE_4001005 = {
            desc = "平台帐号不存在",
            id = 309,
            language_id = 0,
            message_id = 3009,
            name = "ERROR_CODE_4001005",
        },
        ERROR_CODE_4001006 = {
            desc = "第三方账号已绑定平台账号",
            id = 310,
            language_id = 0,
            message_id = 3010,
            name = "ERROR_CODE_4001006",
        },
        ERROR_CODE_4001101 = {
            desc = "token无效",
            id = 311,
            language_id = 0,
            message_id = 3011,
            name = "ERROR_CODE_4001101",
        },
        ERROR_CODE_4001102 = {
            desc = "token过期",
            id = 312,
            language_id = 0,
            message_id = 3012,
            name = "ERROR_CODE_4001102",
        },
        ERROR_CODE_4001103 = {
            desc = "第三方token无效",
            id = 313,
            language_id = 0,
            message_id = 3013,
            name = "ERROR_CODE_4001103",
        },
        ERROR_CODE_4004001 = {
            desc = "本地不存在游客数据",
            id = 314,
            language_id = 0,
            message_id = 3014,
            name = "ERROR_CODE_4004001",
        },
        ERROR_CODE_4004002 = {
            desc = "跨区校验帐号数据异常",
            id = 315,
            language_id = 0,
            message_id = 3015,
            name = "ERROR_CODE_4004002",
        },
        ERROR_CODE_4004003 = {
            desc = "平台账号被封禁",
            id = 316,
            language_id = 0,
            message_id = 3016,
            name = "ERROR_CODE_4004003",
        },
        ERROR_CODE_4004004 = {
            desc = "跨区token不合法",
            id = 317,
            language_id = 0,
            message_id = 3017,
            name = "ERROR_CODE_4004004",
        },
        ERROR_CODE_4004005 = {
            desc = "跨区token失效",
            id = 318,
            language_id = 0,
            message_id = 3018,
            name = "ERROR_CODE_4004005",
        },
        ERROR_CODE_4004006 = {
            desc = "出生地校验一致，跨区登录失效",
            id = 319,
            language_id = 0,
            message_id = 3019,
            name = "ERROR_CODE_4004006",
        },
        ERROR_CODE_4004007 = {
            desc = "游戏账号不一致",
            id = 320,
            language_id = 0,
            message_id = 3020,
            name = "ERROR_CODE_4004007",
        },
        ERROR_CODE_5000000 = {
            desc = "服务器内部错误",
            id = 321,
            language_id = 0,
            message_id = 3021,
            name = "ERROR_CODE_5000000",
        },
        ERROR_CODE_5000000_1 = {
            desc = "网络繁忙，请稍后重试",
            id = 322,
            language_id = 0,
            message_id = 3022,
            name = "ERROR_CODE_5000000_1",
        },
        ERROR_CODE_5000001 = {
            desc = "未知错误",
            id = 323,
            language_id = 0,
            message_id = 3023,
            name = "ERROR_CODE_5000001",
        },
        ERROR_CODE_5000003 = {
            desc = "系统繁忙，请稍后重试",
            id = 324,
            language_id = 0,
            message_id = 3024,
            name = "ERROR_CODE_5000003",
        },
        ERROR_CODE_5000004 = {
            desc = "第三方平台服务器异常",
            id = 325,
            language_id = 0,
            message_id = 3025,
            name = "ERROR_CODE_5000004",
        },
        ERROR_CODE_5000005 = {
            desc = "非全球服集群",
            id = 326,
            language_id = 0,
            message_id = 3026,
            name = "ERROR_CODE_5000005",
        },
        ERROR_CODE_5001001 = {
            desc = "跨集群登录失败",
            id = 327,
            language_id = 0,
            message_id = 3027,
            name = "ERROR_CODE_5001001",
        },
        ERROR_CODE_5001002 = {
            desc = "跨集群绑定失败",
            id = 328,
            language_id = 0,
            message_id = 3028,
            name = "ERROR_CODE_5001002",
        },
        EXCEED_RECRUIT_LEVEL = {
            desc = "招募关系建立失败，超出招募邀请等级",
            id = 2202,
            language_id = 0,
            message_id = 852,
            name = "EXCEED_RECRUIT_LEVEL",
        },
        EXCHANGE_SELF_ERROR = {
            desc = "不能替换自己所在的位置",
            id = 1314,
            language_id = 0,
            message_id = 0,
            name = "EXCHANGE_SELF_ERROR",
        },
        GET_ACTIVITY_REWARD_ERROR = {
            desc = "领取奖励失败",
            id = 1319,
            language_id = 1200044,
            message_id = 0,
            name = "GET_ACTIVITY_REWARD_ERROR",
        },
        GOLD_NOT_ENOUGH = {
            desc = "金币不足",
            id = 1210,
            language_id = 0,
            message_id = 700,
            name = "GOLD_NOT_ENOUGH",
        },
        ICON_FRAME_NOT_UNLOCK = {
            desc = "头像框未解锁",
            id = 1400,
            language_id = 0,
            message_id = 0,
            name = "ICON_FRAME_NOT_UNLOCK",
        },
        ICON_NOT_UNLOCK = {
            desc = "头像未解锁",
            id = 2100,
            language_id = 0,
            message_id = 802,
            name = "ICON_NOT_UNLOCK",
        },
        INVALID_RECRUIT_CODE = {
            desc = "招募关系建立失败，无效招募码",
            id = 2203,
            language_id = 0,
            message_id = 853,
            name = "INVALID_RECRUIT_CODE",
        },
        INVALID_REQUEST = {
            desc = "非法请求-101",
            id = 101,
            language_id = 0,
            message_id = 2002,
            name = "INVALID_REQUEST",
        },
        INVITE_SUCCESS = {
            desc = "邀请发送成功",
            id = 1322,
            language_id = 0,
            message_id = 416,
            name = "INVITE_SUCCESS",
        },
        INVITE_TOO_FREQUENT = {
            desc = "邀请过于频繁",
            id = 1311,
            language_id = 0,
            message_id = 408,
            name = "INVITE_TOO_FREQUENT",
        },
        INVITE_TYPE_ERROR = {
            desc = "非法请求-1310（邀请类型错误）",
            id = 1310,
            language_id = 0,
            message_id = 2010,
            name = "INVITE_TYPE_ERROR",
        },
        KICK_TARGET_NOT_IN_ROOM = {
            desc = "踢人的目标不在房间中",
            id = 1317,
            language_id = 0,
            message_id = 414,
            name = "KICK_TARGET_NOT_IN_ROOM",
        },
        LEADERBOARD_PARAM_ERROR = {
            desc = "非法请求-1203（排行榜类型错误）",
            id = 1203,
            language_id = 0,
            message_id = 2000,
            name = "LEADERBOARD_PARAM_ERROR",
        },
        MAP_NOT_EXISTS = {
            desc = "地图不存在",
            id = 1101,
            language_id = 0,
            message_id = 0,
            name = "MAP_NOT_EXISTS",
        },
        MATCH_IN_SHUTDOWN = {
            desc = "服务器即将进行维护,暂时无法进入游戏",
            id = 1505,
            language_id = 0,
            message_id = 2012,
            name = "MATCH_IN_SHUTDOWN",
        },
        MATCH_TICKET_EMPTY = {
            desc = "服务器错误-1308（匹配票据为空）",
            id = 1308,
            language_id = 0,
            message_id = 2008,
            name = "MATCH_TICKET_EMPTY",
        },
        MAX_BOUGHT_LIMIT = {
            desc = "购买次数已达上限",
            id = 1211,
            language_id = 0,
            message_id = 0,
            name = "MAX_BOUGHT_LIMIT",
        },
        NAME_ALREADY_EXIST = {
            desc = "名字重复",
            id = 1207,
            language_id = 50042,
            message_id = 0,
            name = "NAME_ALREADY_EXIST",
        },
        NAME_IS_BANED = {
            desc = "名字是屏蔽词",
            id = 1202,
            language_id = 50023,
            message_id = 0,
            name = "NAME_IS_BANED",
        },
        NAME_LENGTH_TOO_LONG = {
            desc = "名字长度过长",
            id = 1201,
            language_id = 50022,
            message_id = 0,
            name = "NAME_LENGTH_TOO_LONG",
        },
        NAME_LENGTH_TOO_SHORT = {
            desc = "名字长度过短",
            id = 1205,
            language_id = 50024,
            message_id = 0,
            name = "NAME_LENGTH_TOO_SHORT",
        },
        NOT_IN_SELLING_TIME = {
            desc = "不在售卖时段",
            id = 1213,
            language_id = 0,
            message_id = 0,
            name = "NOT_IN_SELLING_TIME",
        },
        NOT_NEED_TO_BUY = {
            desc = "无需购买（已经获得）",
            id = 1212,
            language_id = 0,
            message_id = 0,
            name = "NOT_NEED_TO_BUY",
        },
        NOT_SAME_RECRUIT_GROUP = {
            desc = "招募关系建立失败，招募人与被招募人不在同一大区",
            id = 2204,
            language_id = 0,
            message_id = 854,
            name = "NOT_SAME_RECRUIT_GROUP",
        },
        NO_INVITATION = {
            desc = "非法请求-1312（没有收到过邀请）",
            id = 1312,
            language_id = 0,
            message_id = 2011,
            name = "NO_INVITATION",
        },
        OK = {
            desc = "成功",
            id = 0,
            language_id = 0,
            message_id = 0,
            name = "OK",
        },
        PLAYER_ALEADY_IN_TEAM = {
            desc = "玩家已在队伍中",
            id = 1301,
            language_id = 0,
            message_id = 409,
            name = "PLAYER_ALEADY_IN_TEAM",
        },
        PLAYER_IN_PUNISH = {
            desc = "玩家正在匹配惩罚中",
            id = 1320,
            language_id = 0,
            message_id = 419,
            name = "PLAYER_IN_PUNISH",
        },
        PLAYER_NOT_EXIST = {
            desc = "玩家id不存在",
            id = 1511,
            language_id = 0,
            message_id = 0,
            name = "PLAYER_NOT_EXIST",
        },
        PLAYER_NOT_IN_TEAM = {
            desc = "玩家不在队伍中",
            id = 1305,
            language_id = 0,
            message_id = 0,
            name = "PLAYER_NOT_IN_TEAM",
        },
        PLAYER_NOT_LEADER = {
            desc = "非法请求-1302（不是队长不能踢人）",
            id = 1302,
            language_id = 0,
            message_id = 2006,
            name = "PLAYER_NOT_LEADER",
        },
        PLAYER_STATE_ERROR = {
            desc = "非法请求-104（玩家状态错误）",
            id = 104,
            language_id = 0,
            message_id = 2005,
            name = "PLAYER_STATE_ERROR",
        },
        QUERY_ROLE_EMPTY = {
            desc = "非法请求-1204（查询玩家为空）",
            id = 1204,
            language_id = 0,
            message_id = 2001,
            name = "QUERY_ROLE_EMPTY",
        },
        RANK_HAS_NO_REWARD = {
            desc = "该级别无奖励",
            id = 2002,
            language_id = 0,
            message_id = 0,
            name = "RANK_HAS_NO_REWARD",
        },
        RANK_NOT_REACHED = {
            desc = "冲级奖励还没到该段位",
            id = 2001,
            language_id = 0,
            message_id = 0,
            name = "RANK_NOT_REACHED",
        },
        RANK_REWARD_ALREADY_GOT = {
            desc = "该级别奖励已领取",
            id = 2003,
            language_id = 0,
            message_id = 0,
            name = "RANK_REWARD_ALREADY_GOT",
        },
        RECRUIT_SELF = {
            desc = "招募关系建立失败，无法招募自己",
            id = 2201,
            language_id = 0,
            message_id = 851,
            name = "RECRUIT_SELF",
        },
        REFRESH_TASK_ERROR = {
            desc = "任务已过期",
            id = 2300,
            language_id = 0,
            message_id = 830,
            name = "REFRESH_TASK_ERROR",
        },
        REWARD_ALREADY_REWARDED = {
            desc = "已领取过激活码对应奖励的同类奖励",
            id = 1509,
            language_id = 0,
            message_id = 1112,
            name = "REWARD_ALREADY_REWARDED",
        },
        REWARD_CONFLICT = {
            desc = "已领取过激活码对应奖励的互斥奖励",
            id = 1510,
            language_id = 0,
            message_id = 1113,
            name = "REWARD_CONFLICT",
        },
        REWARD_UNUSABLE = {
            desc = "不满足激活码奖励的领取条件",
            id = 1508,
            language_id = 0,
            message_id = 1111,
            name = "REWARD_UNUSABLE",
        },
        RISK_BLOCKED_ACTIVATE_ROLE = {
            desc = "激活角色被风控阻断，错误码提前占坑，编号、描述等均可修改",
            id = 202,
            language_id = 0,
            message_id = 0,
            name = "RISK_BLOCKED_ACTIVATE_ROLE",
        },
        RISK_BLOCKED_CREATE_ROLE = {
            desc = "创建角色被风控阻断，错误码提前占坑，编号、描述等均可修改",
            id = 201,
            language_id = 0,
            message_id = 0,
            name = "RISK_BLOCKED_CREATE_ROLE",
        },
        RISK_BLOCKED_LOGIN_ROLE = {
            desc = "登陆角色被风控阻断，错误码提前占坑，编号、描述等均可修改",
            id = 203,
            language_id = 0,
            message_id = 0,
            name = "RISK_BLOCKED_LOGIN_ROLE",
        },
        ROLE_COUNT_LIMIT = {
            desc = "建角人数限制",
            id = 1206,
            language_id = 0,
            message_id = 0,
            name = "ROLE_COUNT_LIMIT",
        },
        ROOM_CAMP_LIMIT_AMOUNT = {
            desc = "阵营数量限制",
            id = 1004,
            language_id = 0,
            message_id = 0,
            name = "ROOM_CAMP_LIMIT_AMOUNT",
        },
        ROOM_FULL = {
            desc = "房间满",
            id = 1002,
            language_id = 0,
            message_id = 100,
            name = "ROOM_FULL",
        },
        ROOM_NEED_OWNER = {
            desc = "需要房主操作",
            id = 1006,
            language_id = 0,
            message_id = 0,
            name = "ROOM_NEED_OWNER",
        },
        ROOM_NOT_EXISTS = {
            desc = "房间不存在",
            id = 1001,
            language_id = 0,
            message_id = 101,
            name = "ROOM_NOT_EXISTS",
        },
        ROOM_NOT_IN_ROOM = {
            desc = "不在房间中",
            id = 1003,
            language_id = 0,
            message_id = 0,
            name = "ROOM_NOT_IN_ROOM",
        },
        ROOM_STATE_LIMIT = {
            desc = "房间状态限制",
            id = 1005,
            language_id = 0,
            message_id = 0,
            name = "ROOM_STATE_LIMIT",
        },
        SDK_10411 = {
            desc = "登录失败，服务器目前处于关闭状态，请留意公告。",
            id = 356,
            language_id = 0,
            message_id = 3056,
            name = "SDK_10411",
        },
        SDK_10413 = {
            desc = "排队人数过多，请稍后再试。",
            id = 357,
            language_id = 0,
            message_id = 3057,
            name = "SDK_10413",
        },
        SDK_10415 = {
            desc = "登录失败，此账号已被禁止登录，请联系客服。",
            id = 358,
            language_id = 0,
            message_id = 3058,
            name = "SDK_10415",
        },
        SDK_4001003 = {
            desc = "此游戏账号已绑定此类第三方账号",
            id = 361,
            language_id = 0,
            message_id = 3061,
            name = "SDK_4001003",
        },
        SDK_4001004 = {
            desc = "此第三方账号已经在平台创建",
            id = 362,
            language_id = 0,
            message_id = 3062,
            name = "SDK_4001004",
        },
        SDK_4001005 = {
            desc = "平台账号不存在",
            id = 363,
            language_id = 0,
            message_id = 3063,
            name = "SDK_4001005",
        },
        SDK_4001006 = {
            desc = "第三方账号已绑定平台账号",
            id = 364,
            language_id = 0,
            message_id = 3064,
            name = "SDK_4001006",
        },
        SDK_4004003 = {
            desc = "账号被封禁， 请联系客服。",
            id = 365,
            language_id = 0,
            message_id = 3065,
            name = "SDK_4004003",
        },
        SDK_409 = {
            desc = "此账号已在其他地方登录，请稍后再试。",
            id = 353,
            language_id = 0,
            message_id = 3053,
            name = "SDK_409",
        },
        SDK_411 = {
            desc = "账号已经绑定过了，无法重复绑定。",
            id = 354,
            language_id = 0,
            message_id = 3054,
            name = "SDK_411",
        },
        SDK_413 = {
            desc = "排队中",
            id = 355,
            language_id = 0,
            message_id = 3055,
            name = "SDK_413",
        },
        SDK_ABNORMAL = {
            desc = "发生异常，请联系客服。（错误码：{0}）",
            id = 350,
            language_id = 0,
            message_id = 3050,
            name = "SDK_ABNORMAL",
        },
        SDK_ABNORMAL_TAUTOLOGY = {
            desc = "发生异常，请重试或联系客服。（错误码：{0}）",
            id = 351,
            language_id = 0,
            message_id = 3051,
            name = "SDK_ABNORMAL_TAUTOLOGY",
        },
        SDK_BINDING = {
            desc = "此第三方账号已绑定过游戏账号了，请使用未绑定过第三方账号进行绑定。（错误码：{0}）",
            id = 352,
            language_id = 0,
            message_id = 3052,
            name = "SDK_BINDING",
        },
        SDK_BUSY = {
            desc = "系统繁忙，请稍后重试。（错误码：{0}）",
            id = 359,
            language_id = 0,
            message_id = 3059,
            name = "SDK_BUSY",
        },
        SELF_IN_EXCHANGE = {
            desc = "自身正在交换位置中",
            id = 1315,
            language_id = 0,
            message_id = 404,
            name = "SELF_IN_EXCHANGE",
        },
        SERVER_ERROR = {
            desc = "服务器错误-103",
            id = 103,
            language_id = 0,
            message_id = 2004,
            name = "SERVER_ERROR",
        },
        TARGET_IN_EXCHANGE = {
            desc = "对面正在交换位置中",
            id = 1316,
            language_id = 0,
            message_id = 403,
            name = "TARGET_IN_EXCHANGE",
        },
        TEAM_FULL = {
            desc = "队伍人数已满不能加入",
            id = 1304,
            language_id = 0,
            message_id = 406,
            name = "TEAM_FULL",
        },
        TEAM_IS_IN_MATCHING = {
            desc = "队伍在匹配中",
            id = 1306,
            language_id = 0,
            message_id = 410,
            name = "TEAM_IS_IN_MATCHING",
        },
        TEAM_LEVEL_LIMIT = {
            desc = "邀请等级限制",
            id = 1323,
            language_id = 0,
            message_id = 424,
            name = "TEAM_LEVEL_LIMIT",
        },
        TEAM_MEMBER_IN_PUNISH = {
            desc = "有玩家处于禁赛期间，已自动踢出房间",
            id = 1321,
            language_id = 0,
            message_id = 420,
            name = "TEAM_MEMBER_IN_PUNISH",
        },
        TEAM_NOT_ALL_READY = {
            desc = "不是所有人都准备",
            id = 1307,
            language_id = 0,
            message_id = 400,
            name = "TEAM_NOT_ALL_READY",
        },
        TEAM_RANK_LIMIT = {
            desc = "邀请段位限制",
            id = 1324,
            language_id = 0,
            message_id = 422,
            name = "TEAM_RANK_LIMIT",
        },
        TEAN_NOT_EXIST = {
            desc = "队伍不存在-1313",
            id = 1313,
            language_id = 0,
            message_id = 407,
            name = "TEAN_NOT_EXIST",
        },
    },
}