return{
    attachment = {
        [1] = {
            default_skin = 0,
            desc = "",
            desc_lang_index = 0,
            icon = "",
            id = 1,
            name = "消音器",
            name_lang_indwx = 11205,
            parent_point_name = "",
            type = 1,
        },
        [2] = {
            default_skin = 0,
            desc = "",
            desc_lang_index = 0,
            icon = "",
            id = 2,
            name = "消焰器",
            name_lang_indwx = 11206,
            parent_point_name = "",
            type = 1,
        },
        [3] = {
            default_skin = 0,
            desc = "",
            desc_lang_index = 0,
            icon = "",
            id = 3,
            name = "补偿器",
            name_lang_indwx = 11207,
            parent_point_name = "",
            type = 1,
        },
        [4] = {
            default_skin = 0,
            desc = "",
            desc_lang_index = 0,
            icon = "",
            id = 4,
            name = "制退器",
            name_lang_indwx = 11208,
            parent_point_name = "",
            type = 1,
        },
        [5] = {
            default_skin = 0,
            desc = "",
            desc_lang_index = 0,
            icon = "",
            id = 5,
            name = "延伸枪管",
            name_lang_indwx = 11209,
            parent_point_name = "",
            type = 1,
        },
        [1001] = {
            default_skin = 5988,
            desc = "",
            desc_lang_index = 0,
            icon = "",
            id = 1001,
            name = "垂直握把",
            name_lang_indwx = 11210,
            parent_point_name = "",
            type = 2,
        },
        [1002] = {
            default_skin = 5989,
            desc = "",
            desc_lang_index = 0,
            icon = "",
            id = 1002,
            name = "转角握把",
            name_lang_indwx = 11211,
            parent_point_name = "",
            type = 2,
        },
        [2001] = {
            default_skin = 6001,
            desc = "视野开阔，常用瞄具",
            desc_lang_index = 11222,
            icon = "ui_2d_hongdian",
            id = 2001,
            name = "红点瞄准镜",
            name_lang_indwx = 11212,
            parent_point_name = "hongdian",
            type = 3,
        },
        [2002] = {
            default_skin = 6002,
            desc = "性能优异，常用于扫射",
            desc_lang_index = 11223,
            icon = "ui_2d_quanxi",
            id = 2002,
            name = "全息瞄准镜",
            name_lang_indwx = 11213,
            parent_point_name = "quanxi",
            type = 3,
        },
        [2003] = {
            default_skin = 6003,
            desc = "三角形准线，视野更好",
            desc_lang_index = 11224,
            icon = "ui_2d_fanshe",
            id = 2003,
            name = "反射瞄准镜",
            name_lang_indwx = 11214,
            parent_point_name = "fanshe",
            type = 3,
        },
        [2004] = {
            default_skin = 6004,
            desc = "适用于远距的高倍瞄具",
            desc_lang_index = 11225,
            icon = "ui_2d_acog",
            id = 2004,
            name = "先进光学瞄准镜",
            name_lang_indwx = 11215,
            parent_point_name = "acog",
            type = 3,
        },
        [2011] = {
            default_skin = 5994,
            desc = "视野开阔，常用瞄具",
            desc_lang_index = 11222,
            icon = "ui_2d_hongdian",
            id = 2011,
            name = "红点瞄准镜",
            name_lang_indwx = 11216,
            parent_point_name = "hongdian",
            type = 3,
        },
        [2012] = {
            default_skin = 5995,
            desc = "性能优异，常用于扫射",
            desc_lang_index = 11223,
            icon = "ui_2d_quanxi",
            id = 2012,
            name = "全息瞄准镜",
            name_lang_indwx = 11217,
            parent_point_name = "quanxi",
            type = 3,
        },
        [2013] = {
            default_skin = 5996,
            desc = "三角形准线，视野更好",
            desc_lang_index = 11224,
            icon = "ui_2d_fanshe",
            id = 2013,
            name = "反射瞄准镜",
            name_lang_indwx = 11218,
            parent_point_name = "fanshe",
            type = 3,
        },
        [2014] = {
            default_skin = 5997,
            desc = "适用于远距的高倍瞄具",
            desc_lang_index = 11225,
            icon = "ui_2d_acog",
            id = 2014,
            name = "先进光学战斗瞄准镜",
            name_lang_indwx = 11219,
            parent_point_name = "acog",
            type = 3,
        },
        [2021] = {
            default_skin = 6005,
            desc = "视野开阔，常用瞄具",
            desc_lang_index = 11222,
            icon = "ui_2d_hongdian",
            id = 2021,
            name = "红点瞄准镜",
            name_lang_indwx = 11220,
            parent_point_name = "hongdian",
            type = 3,
        },
        [3001] = {
            default_skin = 5999,
            desc = "",
            desc_lang_index = 0,
            icon = "",
            id = 3001,
            name = "镭射瞄准器",
            name_lang_indwx = 11221,
            parent_point_name = "",
            type = 4,
        },
        [10001] = {
            default_skin = 5000,
            desc = "",
            desc_lang_index = 0,
            icon = "ui_2d_acog",
            id = 10001,
            name = "挂件",
            name_lang_indwx = 11220,
            parent_point_name = "guajian",
            type = 5,
        },
    },
    barrel = {
        {
            fire_light = 0.0,
            first_recoil = 100.0,
            id = 1,
            recoil = 100.0,
            recoil_recover_time = 100.0,
            sound = 0.0,
            special = 1,
        },
        {
            fire_light = 50.0,
            first_recoil = 62.5,
            id = 2,
            recoil = 95.0,
            recoil_recover_time = 70.0,
            sound = 100.0,
            special = 0,
        },
        {
            fire_light = 100.0,
            first_recoil = 100.0,
            id = 3,
            recoil = 82.25,
            recoil_recover_time = 100.0,
            sound = 100.0,
            special = 0,
        },
        {
            fire_light = 100.0,
            first_recoil = 55.0,
            id = 4,
            recoil = 100.0,
            recoil_recover_time = 55.0,
            sound = 100.0,
            special = 0,
        },
        {
            fire_light = 100.0,
            first_recoil = 100.0,
            id = 5,
            recoil = 100.0,
            recoil_recover_time = 100.0,
            sound = 100.0,
            special = 2,
        },
    },
    grip = {
        [1001] = {
            aim_in_time = 100.0,
            id = 1001,
            recoil = 80.0,
        },
        [1002] = {
            aim_in_time = 60.0,
            id = 1002,
            recoil = 100.0,
        },
    },
    pendant = {
        [10001] = {
            id = 10001,
        },
    },
    sight = {
        [2001] = {
            crosshair_id = 0,
            fov = 48.0,
            gun_fov = 13.0,
            id = 2001,
            power_type = 0,
        },
        [2002] = {
            crosshair_id = 0,
            fov = 48.0,
            gun_fov = 20.0,
            id = 2002,
            power_type = 0,
        },
        [2003] = {
            crosshair_id = 0,
            fov = 48.0,
            gun_fov = 30.0,
            id = 2003,
            power_type = 0,
        },
        [2004] = {
            crosshair_id = 0,
            fov = 28.0,
            gun_fov = 10.0,
            id = 2004,
            power_type = 1,
        },
        [2011] = {
            crosshair_id = 0,
            fov = 48.0,
            gun_fov = 13.0,
            id = 2011,
            power_type = 0,
        },
        [2012] = {
            crosshair_id = 0,
            fov = 48.0,
            gun_fov = 20.0,
            id = 2012,
            power_type = 0,
        },
        [2013] = {
            crosshair_id = 0,
            fov = 48.0,
            gun_fov = 30.0,
            id = 2013,
            power_type = 0,
        },
        [2014] = {
            crosshair_id = 0,
            fov = 28.0,
            gun_fov = 10.0,
            id = 2014,
            power_type = 1,
        },
        [2021] = {
            crosshair_id = 0,
            fov = 48.0,
            gun_fov = 13.0,
            id = 2021,
            power_type = 0,
        },
    },
    under_barrel = {
        [3001] = {
            id = 3001,
            scatter = 75.0,
        },
    },
}