return{
    map_mode_combination = {
        {
            [1] = {
                attacker_regionpanel = "1_Attacker_RegionPanel",
                defender_regionpanel = "1_Defender_RegionPanel",
                editor_only_prefab = "",
                map_id = 1,
                mode_id = 1,
                prefab = "level02_can/eliminate_threat_mode",
                scene_file = "",
            },
            [2] = {
                attacker_regionpanel = "2_Attacker_RegionPanel",
                defender_regionpanel = "2_Defender_RegionPanel",
                editor_only_prefab = "",
                map_id = 2,
                mode_id = 1,
                prefab = "level03_mex/eliminate_threat_mode",
                scene_file = "",
            },
            [6] = {
                attacker_regionpanel = "6_Attacker_RegionPanel",
                defender_regionpanel = "6_Defender_RegionPanel",
                editor_only_prefab = "",
                map_id = 6,
                mode_id = 1,
                prefab = "level04_rus/eliminate_threat_mode",
                scene_file = "",
            },
            [7] = {
                attacker_regionpanel = "7_Attacker_RegionPanel",
                defender_regionpanel = "7_Defender_RegionPanel",
                editor_only_prefab = "",
                map_id = 7,
                mode_id = 1,
                prefab = "level05_jpn/eliminate_threat_mode",
                scene_file = "",
            },
        },
        {
            [3] = {
                attacker_regionpanel = "",
                defender_regionpanel = "",
                editor_only_prefab = "",
                map_id = 3,
                mode_id = 2,
                prefab = "level00_tra/eliminate_threat_mode",
                scene_file = "",
            },
        },
        {
            [1] = {
                attacker_regionpanel = "1_Attacker_RegionPanel",
                defender_regionpanel = "1_Defender_RegionPanel",
                editor_only_prefab = "level02_can/training_mode",
                map_id = 1,
                mode_id = 3,
                prefab = "level02_can/training_mode",
                scene_file = "Training_level02_can.bin",
            },
            [2] = {
                attacker_regionpanel = "2_Attacker_RegionPanel",
                defender_regionpanel = "2_Defender_RegionPanel",
                editor_only_prefab = "level03_mex/training_mode",
                map_id = 2,
                mode_id = 3,
                prefab = "",
                scene_file = "Training_level03_mex.bin",
            },
            [6] = {
                attacker_regionpanel = "6_Attacker_RegionPanel",
                defender_regionpanel = "6_Defender_RegionPanel",
                editor_only_prefab = "level04_rus/training_mode",
                map_id = 6,
                mode_id = 3,
                prefab = "",
                scene_file = "Training_level04_rus.bin",
            },
            [7] = {
                attacker_regionpanel = "7_Attacker_RegionPanel",
                defender_regionpanel = "7_Defender_RegionPanel",
                editor_only_prefab = "level05_jpn/training_mode",
                map_id = 7,
                mode_id = 3,
                prefab = "",
                scene_file = "Training_level05_jpn.bin",
            },
        },
        {
            [1] = {
                attacker_regionpanel = "1_Attacker_RegionPanel",
                defender_regionpanel = "1_Defender_RegionPanel_Bomb",
                editor_only_prefab = "",
                map_id = 1,
                mode_id = 4,
                prefab = "level02_can/bomb_mode",
                scene_file = "Bomb_level02_can.bin",
            },
            [2] = {
                attacker_regionpanel = "2_Attacker_RegionPanel",
                defender_regionpanel = "2_Defender_RegionPanel_Bomb",
                editor_only_prefab = "",
                map_id = 2,
                mode_id = 4,
                prefab = "level03_mex/bomb_mode",
                scene_file = "Bomb_level03_mex.bin",
            },
            [6] = {
                attacker_regionpanel = "6_Attacker_RegionPanel",
                defender_regionpanel = "6_Defender_RegionPanel_Bomb",
                editor_only_prefab = "",
                map_id = 6,
                mode_id = 4,
                prefab = "level04_rus/bomb_mode",
                scene_file = "Bomb_level04_rus.bin",
            },
            [7] = {
                attacker_regionpanel = "7_Attacker_RegionPanel",
                defender_regionpanel = "7_Defender_RegionPanel_Bomb",
                editor_only_prefab = "",
                map_id = 7,
                mode_id = 4,
                prefab = "level05_jpn/bomb_mode",
                scene_file = "Bomb_level05_jpn.bin",
            },
        },
    },
}