return{
    maps = {
        {
            attacker_born = {
                26,
                27,
                28,
                29,
                30,
                6,
                7,
                8,
                9,
                10,
                16,
                17,
                18,
                19,
                20,
            },
            attacker_born_name = {
                61,
                58,
                54,
            },
            attacker_born_ui_maps = {
                "I_5",
                "I_5",
                "I_5",
            },
            available = 1,
            bomb_defender_born = {
                211,
                212,
                213,
                214,
                215,
                206,
                207,
                208,
                209,
                210,
                201,
                202,
                203,
                204,
                205,
            },
            bomb_defender_born_name = {
                7,
                9,
                24,
                23,
                50,
                47,
            },
            bomb_defender_born_ui_maps = {
                "B_2",
                "B_1",
                "B_0",
            },
            bomb_target_zone = {
                5,
                6,
                3,
                4,
                1,
                2,
            },
            defender_born = {
                11,
                12,
                13,
                14,
                15,
                1,
                2,
                3,
                4,
                5,
                21,
                22,
                23,
                24,
                25,
                31,
                32,
                33,
                34,
                35,
            },
            defender_born_name = {
                14,
                24,
                37,
                49,
            },
            defender_born_ui_maps = {
                "I_3",
                "I_2",
                "I_1",
                "I_0",
            },
            drone_born = {
                101,
                102,
                103,
                104,
                105,
            },
            floor_json = "{\"-1\":\"-7.009939\",\"0\":\"-2.577364\",\"1\":\"1.415879\",\"2\":\"5.065877\",\"3\":\"8.711\"}",
            floor_sound_threshold = 1.8,
            id = 1,
            map_bg = "level02_can",
            map_bg_prefab = "level02_loading_01",
            map_choose_bg = "img_RoomSet_2",
            name = "运输船码头",
            name_lang_index = 200001,
            preload_particle_id_array = {
                12,
                13,
                18,
                19,
                1031,
                1032,
                1033,
                1034,
                1035,
                1036,
                1037,
                1038,
                1039,
                1040,
                1041,
                1042,
                1043,
                1044,
                1045,
                1046,
                1047,
                1048,
                1049,
                1050,
                1051,
                1052,
                1053,
                1054,
                1055,
                1056,
                1057,
                1058,
                1059,
                1060,
                1061,
                1062,
                1063,
                1064,
                1065,
                1066,
                1067,
                1068,
                1069,
                1070,
                1071,
                1072,
                1073,
                1074,
                1075,
                1076,
                1077,
                1078,
                1079,
                1080,
                1081,
                1082,
                1083,
                1084,
                1085,
                1086,
                1087,
                1088,
                1089,
                1090,
                1091,
                1092,
                1093,
                1094,
                1095,
                1096,
                1097,
                1098,
                1099,
                1100,
                1102,
            },
            scene_name = "level02_can",
            select_available = 1,
            select_weight = 100,
            sound_banks = {
                "Map_CargoDock",
                "Map_RoomTone",
            },
            target_zone = {
                1,
                0,
                2,
                3,
            },
            uva_destroyed_ui = "I_5",
        },
        {
            attacker_born = {
                6,
                7,
                8,
                9,
                10,
                16,
                17,
                18,
                19,
                20,
                26,
                27,
                28,
                29,
                30,
            },
            attacker_born_name = {
                135,
                140,
                138,
            },
            attacker_born_ui_maps = {
                "I_5",
                "I_5",
                "I_5",
            },
            available = 1,
            bomb_defender_born = {
                211,
                212,
                213,
                214,
                215,
                216,
                217,
                218,
                219,
                220,
                201,
                202,
                203,
                204,
                205,
                206,
                207,
                208,
                209,
                210,
            },
            bomb_defender_born_name = {
                125,
                126,
                121,
                122,
                112,
                110,
                106,
                107,
            },
            bomb_defender_born_ui_maps = {
                "B_2",
                "B_3",
                "B_0",
                "B_1",
            },
            bomb_target_zone = {
                5,
                6,
                7,
                8,
                1,
                2,
                3,
                4,
            },
            defender_born = {
                21,
                22,
                23,
                24,
                25,
                31,
                32,
                33,
                34,
                35,
                1,
                2,
                3,
                4,
                5,
                11,
                12,
                13,
                14,
                15,
            },
            defender_born_name = {
                122,
                125,
                106,
                112,
            },
            defender_born_ui_maps = {
                "I_2",
                "I_3",
                "I_0",
                "I_1",
            },
            drone_born = {
                101,
                102,
                103,
                104,
                105,
            },
            floor_json = "{\"0\":\"0\",\"1\":\"3.653\",\"2\":\"7.276\"}",
            floor_sound_threshold = 1.8,
            id = 2,
            map_bg = "level03_mex",
            map_bg_prefab = "level03_loading_01",
            map_choose_bg = "img_RoomSet_3",
            name = "卡特尔豪宅",
            name_lang_index = 200101,
            preload_particle_id_array = {
                12,
                13,
                18,
                19,
                1031,
                1032,
                1033,
                1034,
                1035,
                1036,
                1037,
                1038,
                1039,
                1040,
                1041,
                1042,
                1043,
                1044,
                1045,
                1046,
                1047,
                1048,
                1049,
                1050,
                1051,
                1052,
                1053,
                1054,
                1055,
                1056,
                1057,
                1058,
                1059,
                1060,
                1061,
                1062,
                1063,
                1064,
                1065,
                1066,
                1067,
                1068,
                1069,
                1070,
                1071,
                1072,
                1073,
                1074,
                1075,
                1076,
                1077,
                1078,
                1079,
                1080,
                1081,
                1082,
                1083,
                1084,
                1085,
                1086,
                1087,
                1088,
                1089,
                1090,
                1091,
                1092,
                1093,
                1094,
                1095,
                1096,
                1097,
                1098,
                1099,
                1100,
                1102,
            },
            scene_name = "level03_mex",
            select_available = 1,
            select_weight = 100,
            sound_banks = {
                "Map_Mexico",
                "Map_RoomTone",
            },
            target_zone = {
                2,
                3,
                0,
                1,
            },
            uva_destroyed_ui = "I_5",
        },
        {
            attacker_born = {
                6,
                6,
                6,
                6,
                6,
            },
            attacker_born_name = {
                101,
            },
            attacker_born_ui_maps = {
            },
            available = 1,
            bomb_defender_born = {
                1,
                1,
                1,
                1,
                1,
            },
            bomb_defender_born_name = {
                102,
            },
            bomb_defender_born_ui_maps = {
            },
            bomb_target_zone = {
            },
            defender_born = {
                1,
                1,
                1,
                1,
                1,
            },
            defender_born_name = {
                1,
            },
            defender_born_ui_maps = {
            },
            drone_born = {
                101,
                101,
                101,
                101,
                101,
            },
            floor_json = "",
            floor_sound_threshold = 0,
            id = 3,
            map_bg = "level02_can",
            map_bg_prefab = "guide_loading_01",
            map_choose_bg = "img_RoomSet_2",
            name = "新手引导",
            name_lang_index = 52300,
            preload_particle_id_array = {
            },
            scene_name = "level00_tra",
            select_available = 0,
            select_weight = 0,
            sound_banks = {
            },
            target_zone = {
                1,
                2,
            },
            uva_destroyed_ui = "",
        },
        {
            attacker_born = {
                6,
                7,
                8,
                9,
                10,
                16,
                17,
                18,
                19,
                20,
                26,
                27,
                28,
                29,
                30,
                36,
                37,
                38,
                39,
                40,
            },
            attacker_born_name = {
                101,
                102,
                103,
                104,
            },
            attacker_born_ui_maps = {
            },
            available = 0,
            bomb_defender_born = {
                1,
                2,
                3,
                4,
                5,
                11,
                12,
                13,
                14,
                15,
                21,
                22,
                23,
                24,
                25,
                31,
                32,
                33,
                34,
                35,
            },
            bomb_defender_born_name = {
                101,
                102,
                103,
                104,
            },
            bomb_defender_born_ui_maps = {
            },
            bomb_target_zone = {
            },
            defender_born = {
                1,
                2,
                3,
                4,
                5,
                11,
                12,
                13,
                14,
                15,
                21,
                22,
                23,
                24,
                25,
                31,
                32,
                33,
                34,
                35,
            },
            defender_born_name = {
                101,
                102,
                103,
                104,
            },
            defender_born_ui_maps = {
            },
            drone_born = {
                101,
                102,
                103,
                104,
                105,
            },
            floor_json = "",
            floor_sound_threshold = 0,
            id = 4,
            map_bg = "Demo_Villa",
            map_bg_prefab = "",
            map_choose_bg = "img_RoomSet_3",
            name = "芝加哥豪宅",
            name_lang_index = 0,
            preload_particle_id_array = {
            },
            scene_name = "Demo_Villa",
            select_available = 0,
            select_weight = 0,
            sound_banks = {
            },
            target_zone = {
                0,
                1,
                2,
                3,
            },
            uva_destroyed_ui = "",
        },
        {
            attacker_born = {
                6,
                7,
                8,
                9,
                10,
                16,
                17,
                18,
                19,
                20,
                26,
                27,
                28,
                29,
                30,
                36,
                37,
                38,
                39,
                40,
            },
            attacker_born_name = {
            },
            attacker_born_ui_maps = {
            },
            available = 0,
            bomb_defender_born = {
                1,
                2,
                3,
                4,
                5,
                11,
                12,
                13,
                14,
                15,
                21,
                22,
                23,
                24,
                25,
                31,
                32,
                33,
                34,
                35,
            },
            bomb_defender_born_name = {
            },
            bomb_defender_born_ui_maps = {
            },
            bomb_target_zone = {
            },
            defender_born = {
                1,
                2,
                3,
                4,
                5,
                11,
                12,
                13,
                14,
                15,
                21,
                22,
                23,
                24,
                25,
                31,
                32,
                33,
                34,
                35,
            },
            defender_born_name = {
            },
            defender_born_ui_maps = {
            },
            drone_born = {
                101,
                102,
                103,
                104,
                105,
            },
            floor_json = "",
            floor_sound_threshold = 0,
            id = 5,
            map_bg = "Demo_Villa",
            map_bg_prefab = "",
            map_choose_bg = "img_RoomSet_3",
            name = "外部测试",
            name_lang_index = 0,
            preload_particle_id_array = {
            },
            scene_name = "Demo_Villa_Test",
            select_available = 0,
            select_weight = 0,
            sound_banks = {
            },
            target_zone = {
                0,
                1,
                2,
                3,
            },
            uva_destroyed_ui = "",
        },
        {
            attacker_born = {
                6,
                7,
                8,
                9,
                10,
                16,
                17,
                18,
                19,
                20,
                26,
                27,
                28,
                29,
                30,
            },
            attacker_born_name = {
                250,
                251,
                249,
            },
            attacker_born_ui_maps = {
                "I_5",
                "I_5",
                "I_5",
            },
            available = 1,
            bomb_defender_born = {
                216,
                217,
                218,
                219,
                220,
                211,
                212,
                213,
                214,
                215,
                206,
                207,
                208,
                209,
                210,
                201,
                202,
                203,
                204,
                205,
            },
            bomb_defender_born_name = {
                203,
                207,
                220,
                217,
                219,
                221,
                235,
                237,
            },
            bomb_defender_born_ui_maps = {
                "B_3",
                "B_2",
                "B_1",
                "B_0",
            },
            bomb_target_zone = {
                7,
                8,
                5,
                6,
                3,
                4,
                1,
                2,
            },
            defender_born = {
                1,
                2,
                3,
                4,
                5,
                11,
                12,
                13,
                14,
                15,
                21,
                22,
                23,
                24,
                25,
                31,
                32,
                33,
                34,
                35,
            },
            defender_born_name = {
                203,
                219,
                220,
                235,
            },
            defender_born_ui_maps = {
                "I_0",
                "I_1",
                "I_2",
                "I_3",
            },
            drone_born = {
                101,
                102,
                103,
                104,
                105,
            },
            floor_json = "{\"-1\":\"-5.4483\",\"0\":\"-1.775\",\"1\":\"1.87\",\"2\":\"6.161\"}",
            floor_sound_threshold = 1.8,
            id = 6,
            map_bg = "level04_rus",
            map_bg_prefab = "level04_loading_01",
            map_choose_bg = "img_RoomSet_4",
            name = "俄罗斯车站",
            name_lang_index = 200201,
            preload_particle_id_array = {
                12,
                13,
                18,
                19,
                1031,
                1032,
                1033,
                1034,
                1035,
                1036,
                1037,
                1038,
                1039,
                1040,
                1041,
                1042,
                1043,
                1044,
                1045,
                1046,
                1047,
                1048,
                1049,
                1050,
                1051,
                1052,
                1053,
                1054,
                1055,
                1056,
                1057,
                1058,
                1059,
                1060,
                1061,
                1062,
                1063,
                1064,
                1065,
                1066,
                1067,
                1068,
                1069,
                1070,
                1071,
                1072,
                1073,
                1074,
                1075,
                1076,
                1077,
                1078,
                1079,
                1080,
                1081,
                1082,
                1083,
                1084,
                1085,
                1086,
                1087,
                1088,
                1089,
                1090,
                1091,
                1092,
                1093,
                1094,
                1095,
                1096,
                1097,
                1098,
                1099,
                1100,
                1102,
            },
            scene_name = "level04_rus",
            select_available = 1,
            select_weight = 100,
            sound_banks = {
                "Map_Russia",
                "Map_RoomTone",
            },
            target_zone = {
                0,
                1,
                2,
                3,
            },
            uva_destroyed_ui = "I_5",
        },
        {
            attacker_born = {
                6,
                7,
                8,
                9,
                10,
                16,
                17,
                18,
                19,
                20,
                26,
                27,
                28,
                29,
                30,
            },
            attacker_born_name = {
                332,
                335,
                336,
            },
            attacker_born_ui_maps = {
                "I_5",
                "I_5",
                "I_5",
            },
            available = 1,
            bomb_defender_born = {
                216,
                217,
                218,
                219,
                220,
                211,
                212,
                213,
                214,
                215,
                206,
                207,
                208,
                209,
                210,
                201,
                202,
                203,
                204,
                205,
            },
            bomb_defender_born_name = {
                325,
                324,
                326,
                323,
                311,
                312,
                305,
                306,
            },
            bomb_defender_born_ui_maps = {
                "B_3",
                "B_2",
                "B_1",
                "B_0",
            },
            bomb_target_zone = {
                7,
                8,
                5,
                6,
                3,
                4,
                1,
                2,
            },
            defender_born = {
                31,
                32,
                33,
                34,
                35,
                21,
                22,
                23,
                24,
                25,
                11,
                12,
                13,
                14,
                15,
                1,
                2,
                3,
                4,
                5,
            },
            defender_born_name = {
                325,
                322,
                311,
                305,
            },
            defender_born_ui_maps = {
                "I_3",
                "I_2",
                "I_1",
                "I_0",
            },
            drone_born = {
                101,
                102,
                103,
                104,
                105,
            },
            floor_json = "{\"0\":\"0\",\"1\":\"4.636\",\"2\":\"11.315\"}",
            floor_sound_threshold = 1.8,
            id = 7,
            map_bg = "level05_jpn",
            map_bg_prefab = "level05_loading_01",
            map_choose_bg = "img_RoomSet_5",
            name = "日本温泉",
            name_lang_index = 200301,
            preload_particle_id_array = {
                12,
                13,
                18,
                19,
                1031,
                1032,
                1033,
                1034,
                1035,
                1036,
                1037,
                1038,
                1039,
                1040,
                1041,
                1042,
                1043,
                1044,
                1045,
                1046,
                1047,
                1048,
                1049,
                1050,
                1051,
                1052,
                1053,
                1054,
                1055,
                1056,
                1057,
                1058,
                1059,
                1060,
                1061,
                1062,
                1063,
                1064,
                1065,
                1066,
                1067,
                1068,
                1069,
                1070,
                1071,
                1072,
                1073,
                1074,
                1075,
                1076,
                1077,
                1078,
                1079,
                1080,
                1081,
                1082,
                1083,
                1084,
                1085,
                1086,
                1087,
                1088,
                1089,
                1090,
                1091,
                1092,
                1093,
                1094,
                1095,
                1096,
                1097,
                1098,
                1099,
                1100,
                1102,
            },
            scene_name = "level05_jpn",
            select_available = 1,
            select_weight = 100,
            sound_banks = {
                "Map_Japan",
                "Map_RoomTone",
            },
            target_zone = {
                3,
                2,
                1,
                0,
            },
            uva_destroyed_ui = "I_5",
        },
    },
}