return{
    rank = {
        [0] = {
            compensate_mail = 0,
            fall_point = 0,
            id = 0,
            inherit_score = 1200,
            is_top_rank = 0,
            language_id = 19200,
            num = "",
            pic = "icon_rank_0",
            protect_point = 0,
            rank = 0,
            rank_fall = 0,
            rank_mmr_max = 0,
            rank_mmr_min = 0,
            rank_star = 0,
            rank_to_mmr = 0,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 0,
            reward_value = {
            },
            small_num = "",
            small_pic = "small_icon_rank_0",
            star_fall = 0,
            sub_rank = 0,
        },
        [1] = {
            compensate_mail = 0,
            fall_point = 0,
            id = 1,
            inherit_score = 1020,
            is_top_rank = 0,
            language_id = 19201,
            num = "icon_number_copper_1",
            pic = "icon_rank_1",
            protect_point = 0,
            rank = 1,
            rank_fall = 0,
            rank_mmr_max = 989,
            rank_mmr_min = 900,
            rank_star = 3,
            rank_to_mmr = 900,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 2,
            reward_value = {
            },
            small_num = "1.0",
            small_pic = "small_icon_rank_1",
            star_fall = 0,
            sub_rank = 1,
        },
        [2] = {
            compensate_mail = 9,
            fall_point = 0,
            id = 2,
            inherit_score = 1074,
            is_top_rank = 0,
            language_id = 19202,
            num = "icon_number_copper_2",
            pic = "icon_rank_1",
            protect_point = 0,
            rank = 1,
            rank_fall = 0,
            rank_mmr_max = 1079,
            rank_mmr_min = 990,
            rank_star = 3,
            rank_to_mmr = 990,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 2,
            reward_value = {
            },
            small_num = "2.0",
            small_pic = "small_icon_rank_1",
            star_fall = 0,
            sub_rank = 2,
        },
        [3] = {
            compensate_mail = 9,
            fall_point = 0,
            id = 3,
            inherit_score = 1128,
            is_top_rank = 0,
            language_id = 19203,
            num = "icon_number_copper_3",
            pic = "icon_rank_1",
            protect_point = 0,
            rank = 1,
            rank_fall = 0,
            rank_mmr_max = 1169,
            rank_mmr_min = 1080,
            rank_star = 3,
            rank_to_mmr = 1080,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 2,
            reward_value = {
            },
            small_num = "3.0",
            small_pic = "small_icon_rank_1",
            star_fall = 0,
            sub_rank = 3,
        },
        [4] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 4,
            inherit_score = 1182,
            is_top_rank = 0,
            language_id = 19204,
            num = "icon_number_silver_1",
            pic = "icon_rank_2",
            protect_point = 20,
            rank = 2,
            rank_fall = 0,
            rank_mmr_max = 1289,
            rank_mmr_min = 1170,
            rank_star = 4,
            rank_to_mmr = 1170,
            reward_id = {
                40001,
            },
            reward_index = 0,
            reward_mail = 3,
            reward_value = {
                1,
            },
            small_num = "1.0",
            small_pic = "small_icon_rank_2",
            star_fall = 1,
            sub_rank = 1,
        },
        [5] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 5,
            inherit_score = 1254,
            is_top_rank = 0,
            language_id = 19205,
            num = "icon_number_silver_2",
            pic = "icon_rank_2",
            protect_point = 20,
            rank = 2,
            rank_fall = 1,
            rank_mmr_max = 1409,
            rank_mmr_min = 1290,
            rank_star = 4,
            rank_to_mmr = 1290,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 3,
            reward_value = {
            },
            small_num = "2.0",
            small_pic = "small_icon_rank_2",
            star_fall = 1,
            sub_rank = 2,
        },
        [6] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 6,
            inherit_score = 1326,
            is_top_rank = 0,
            language_id = 19206,
            num = "icon_number_silver_3",
            pic = "icon_rank_2",
            protect_point = 20,
            rank = 2,
            rank_fall = 1,
            rank_mmr_max = 1529,
            rank_mmr_min = 1410,
            rank_star = 4,
            rank_to_mmr = 1410,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 3,
            reward_value = {
            },
            small_num = "3.0",
            small_pic = "small_icon_rank_2",
            star_fall = 1,
            sub_rank = 3,
        },
        [7] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 7,
            inherit_score = 1398,
            is_top_rank = 0,
            language_id = 19207,
            num = "icon_number_golden_1",
            pic = "icon_rank_3",
            protect_point = 30,
            rank = 3,
            rank_fall = 1,
            rank_mmr_max = 1649,
            rank_mmr_min = 1530,
            rank_star = 4,
            rank_to_mmr = 1530,
            reward_id = {
                1008330020,
            },
            reward_index = 0,
            reward_mail = 4,
            reward_value = {
                1,
            },
            small_num = "1.0",
            small_pic = "small_icon_rank_3",
            star_fall = 1,
            sub_rank = 1,
        },
        [8] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 8,
            inherit_score = 1470,
            is_top_rank = 0,
            language_id = 19208,
            num = "icon_number_golden_2",
            pic = "icon_rank_3",
            protect_point = 30,
            rank = 3,
            rank_fall = 1,
            rank_mmr_max = 1769,
            rank_mmr_min = 1650,
            rank_star = 4,
            rank_to_mmr = 1650,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 4,
            reward_value = {
            },
            small_num = "2.0",
            small_pic = "small_icon_rank_3",
            star_fall = 1,
            sub_rank = 2,
        },
        [9] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 9,
            inherit_score = 1542,
            is_top_rank = 0,
            language_id = 19209,
            num = "icon_number_golden_3",
            pic = "icon_rank_3",
            protect_point = 30,
            rank = 3,
            rank_fall = 1,
            rank_mmr_max = 1889,
            rank_mmr_min = 1770,
            rank_star = 4,
            rank_to_mmr = 1770,
            reward_id = {
                40001,
            },
            reward_index = 0,
            reward_mail = 4,
            reward_value = {
                1,
            },
            small_num = "3.0",
            small_pic = "small_icon_rank_3",
            star_fall = 1,
            sub_rank = 3,
        },
        [10] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 10,
            inherit_score = 1614,
            is_top_rank = 0,
            language_id = 19210,
            num = "icon_number_golden_4",
            pic = "icon_rank_3",
            protect_point = 30,
            rank = 3,
            rank_fall = 1,
            rank_mmr_max = 2009,
            rank_mmr_min = 1890,
            rank_star = 4,
            rank_to_mmr = 1890,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 4,
            reward_value = {
            },
            small_num = "4.0",
            small_pic = "small_icon_rank_3",
            star_fall = 1,
            sub_rank = 4,
        },
        [11] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 11,
            inherit_score = 1686,
            is_top_rank = 0,
            language_id = 19211,
            num = "icon_number_silver_1",
            pic = "icon_rank_4",
            protect_point = 40,
            rank = 4,
            rank_fall = 1,
            rank_mmr_max = 2159,
            rank_mmr_min = 2010,
            rank_star = 5,
            rank_to_mmr = 2010,
            reward_id = {
                40001,
            },
            reward_index = 0,
            reward_mail = 5,
            reward_value = {
                1,
            },
            small_num = "1.0",
            small_pic = "small_icon_rank_4",
            star_fall = 1,
            sub_rank = 1,
        },
        [12] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 12,
            inherit_score = 1776,
            is_top_rank = 0,
            language_id = 19212,
            num = "icon_number_silver_2",
            pic = "icon_rank_4",
            protect_point = 40,
            rank = 4,
            rank_fall = 1,
            rank_mmr_max = 2309,
            rank_mmr_min = 2160,
            rank_star = 5,
            rank_to_mmr = 2160,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 5,
            reward_value = {
            },
            small_num = "2.0",
            small_pic = "small_icon_rank_4",
            star_fall = 1,
            sub_rank = 2,
        },
        [13] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 13,
            inherit_score = 1866,
            is_top_rank = 0,
            language_id = 19213,
            num = "icon_number_silver_3",
            pic = "icon_rank_4",
            protect_point = 40,
            rank = 4,
            rank_fall = 1,
            rank_mmr_max = 2459,
            rank_mmr_min = 2310,
            rank_star = 5,
            rank_to_mmr = 2310,
            reward_id = {
                40001,
            },
            reward_index = 0,
            reward_mail = 5,
            reward_value = {
                1,
            },
            small_num = "3.0",
            small_pic = "small_icon_rank_4",
            star_fall = 1,
            sub_rank = 3,
        },
        [14] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 14,
            inherit_score = 1956,
            is_top_rank = 0,
            language_id = 19214,
            num = "icon_number_silver_4",
            pic = "icon_rank_4",
            protect_point = 40,
            rank = 4,
            rank_fall = 1,
            rank_mmr_max = 2609,
            rank_mmr_min = 2460,
            rank_star = 5,
            rank_to_mmr = 2460,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 5,
            reward_value = {
            },
            small_num = "4.0",
            small_pic = "small_icon_rank_4",
            star_fall = 1,
            sub_rank = 4,
        },
        [15] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 15,
            inherit_score = 2046,
            is_top_rank = 0,
            language_id = 19215,
            num = "icon_number_silver_1",
            pic = "icon_rank_5",
            protect_point = 50,
            rank = 5,
            rank_fall = 1,
            rank_mmr_max = 2759,
            rank_mmr_min = 2610,
            rank_star = 5,
            rank_to_mmr = 2610,
            reward_id = {
                50270,
            },
            reward_index = 0,
            reward_mail = 6,
            reward_value = {
                1,
            },
            small_num = "1.0",
            small_pic = "small_icon_rank_5",
            star_fall = 1,
            sub_rank = 1,
        },
        [16] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 16,
            inherit_score = 2136,
            is_top_rank = 0,
            language_id = 19216,
            num = "icon_number_silver_2",
            pic = "icon_rank_5",
            protect_point = 50,
            rank = 5,
            rank_fall = 1,
            rank_mmr_max = 2909,
            rank_mmr_min = 2760,
            rank_star = 5,
            rank_to_mmr = 2760,
            reward_id = {
                40001,
            },
            reward_index = 0,
            reward_mail = 6,
            reward_value = {
                1,
            },
            small_num = "2.0",
            small_pic = "small_icon_rank_5",
            star_fall = 1,
            sub_rank = 2,
        },
        [17] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 17,
            inherit_score = 2226,
            is_top_rank = 0,
            language_id = 19217,
            num = "icon_number_silver_3",
            pic = "icon_rank_5",
            protect_point = 50,
            rank = 5,
            rank_fall = 1,
            rank_mmr_max = 3059,
            rank_mmr_min = 2910,
            rank_star = 5,
            rank_to_mmr = 2910,
            reward_id = {
                40001,
            },
            reward_index = 0,
            reward_mail = 6,
            reward_value = {
                1,
            },
            small_num = "3.0",
            small_pic = "small_icon_rank_5",
            star_fall = 1,
            sub_rank = 3,
        },
        [18] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 18,
            inherit_score = 2316,
            is_top_rank = 0,
            language_id = 19218,
            num = "icon_number_silver_4",
            pic = "icon_rank_5",
            protect_point = 50,
            rank = 5,
            rank_fall = 1,
            rank_mmr_max = 3209,
            rank_mmr_min = 3060,
            rank_star = 5,
            rank_to_mmr = 3060,
            reward_id = {
                40001,
            },
            reward_index = 0,
            reward_mail = 6,
            reward_value = {
                1,
            },
            small_num = "4.0",
            small_pic = "small_icon_rank_5",
            star_fall = 1,
            sub_rank = 4,
        },
        [19] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 19,
            inherit_score = 2406,
            is_top_rank = 0,
            language_id = 19219,
            num = "icon_number_silver_5",
            pic = "icon_rank_5",
            protect_point = 50,
            rank = 5,
            rank_fall = 1,
            rank_mmr_max = 3210,
            rank_mmr_min = 3210,
            rank_star = 5,
            rank_to_mmr = 3210,
            reward_id = {
                40001,
            },
            reward_index = 0,
            reward_mail = 6,
            reward_value = {
                1,
            },
            small_num = "5.0",
            small_pic = "small_icon_rank_5",
            star_fall = 1,
            sub_rank = 5,
        },
        [20] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 20,
            inherit_score = 2496,
            is_top_rank = 1,
            language_id = 19220,
            num = "",
            pic = "icon_rank_6",
            protect_point = 100,
            rank = 6,
            rank_fall = 0,
            rank_mmr_max = 0,
            rank_mmr_min = 0,
            rank_star = 10,
            rank_to_mmr = 3360,
            reward_id = {
                80024,
            },
            reward_index = 0,
            reward_mail = 7,
            reward_value = {
                1,
            },
            small_num = "",
            small_pic = "small_icon_rank_6",
            star_fall = 1,
            sub_rank = 0,
        },
        [21] = {
            compensate_mail = 9,
            fall_point = 10,
            id = 21,
            inherit_score = 2676,
            is_top_rank = 1,
            language_id = 19221,
            num = "",
            pic = "icon_rank_7",
            protect_point = 200,
            rank = 7,
            rank_fall = 0,
            rank_mmr_max = 0,
            rank_mmr_min = 0,
            rank_star = 0,
            rank_to_mmr = 3660,
            reward_id = {
            },
            reward_index = 0,
            reward_mail = 8,
            reward_value = {
            },
            small_num = "",
            small_pic = "small_icon_rank_7",
            star_fall = 1,
            sub_rank = 0,
        },
    },
    rank_big = {
        {
            id = 1,
            limit_language_id = 19228,
        },
        {
            id = 2,
            limit_language_id = 19229,
        },
        {
            id = 3,
            limit_language_id = 19230,
        },
        {
            id = 4,
            limit_language_id = 19231,
        },
        {
            id = 5,
            limit_language_id = 19232,
        },
        {
            id = 6,
            limit_language_id = 19233,
        },
    },
}