return{
    recharge = {
        [1001] = {
            allow_double_currency = 1,
            base_currency = 100,
            bonus_currency = 0,
            double_currency_id = 1,
            icon = "1.0",
            id = 1001,
            perform = 0,
            product_id = "com.f2.areaf2.xh1usd.ios",
            reward = {
            },
        },
        [1002] = {
            allow_double_currency = 1,
            base_currency = 310,
            bonus_currency = 0,
            double_currency_id = 2,
            icon = "2.0",
            id = 1002,
            perform = 0,
            product_id = "com.f2.areaf2.xh3usd.ios",
            reward = {
            },
        },
        [1003] = {
            allow_double_currency = 1,
            base_currency = 520,
            bonus_currency = 0,
            double_currency_id = 3,
            icon = "3.0",
            id = 1003,
            perform = 0,
            product_id = "com.f2.areaf2.xh5usd.ios",
            reward = {
            },
        },
        [1004] = {
            allow_double_currency = 1,
            base_currency = 1280,
            bonus_currency = 0,
            double_currency_id = 4,
            icon = "4.0",
            id = 1004,
            perform = 0,
            product_id = "com.f2.areaf2.xh12usd.ios",
            reward = {
            },
        },
        [1005] = {
            allow_double_currency = 1,
            base_currency = 2700,
            bonus_currency = 0,
            double_currency_id = 5,
            icon = "5.0",
            id = 1005,
            perform = 0,
            product_id = "com.f2.areaf2.xh25usd.ios",
            reward = {
            },
        },
        [1006] = {
            allow_double_currency = 1,
            base_currency = 5700,
            bonus_currency = 0,
            double_currency_id = 6,
            icon = "6.0",
            id = 1006,
            perform = 0,
            product_id = "com.f2.areaf2.xh50usd.ios",
            reward = {
            },
        },
        [2001] = {
            allow_double_currency = 1,
            base_currency = 100,
            bonus_currency = 0,
            double_currency_id = 1,
            icon = "1.0",
            id = 2001,
            perform = 0,
            product_id = "com.f2.areaf2.xh1usd.gp",
            reward = {
            },
        },
        [2002] = {
            allow_double_currency = 1,
            base_currency = 310,
            bonus_currency = 0,
            double_currency_id = 2,
            icon = "2.0",
            id = 2002,
            perform = 0,
            product_id = "com.f2.areaf2.xh3usd.gp",
            reward = {
            },
        },
        [2003] = {
            allow_double_currency = 1,
            base_currency = 520,
            bonus_currency = 0,
            double_currency_id = 3,
            icon = "3.0",
            id = 2003,
            perform = 0,
            product_id = "com.f2.areaf2.xh5usd.gp",
            reward = {
            },
        },
        [2004] = {
            allow_double_currency = 1,
            base_currency = 1280,
            bonus_currency = 0,
            double_currency_id = 4,
            icon = "4.0",
            id = 2004,
            perform = 0,
            product_id = "com.f2.areaf2.xh12usd.gp",
            reward = {
            },
        },
        [2005] = {
            allow_double_currency = 1,
            base_currency = 2700,
            bonus_currency = 0,
            double_currency_id = 5,
            icon = "5.0",
            id = 2005,
            perform = 0,
            product_id = "com.f2.areaf2.xh25usd.gp",
            reward = {
            },
        },
        [2006] = {
            allow_double_currency = 1,
            base_currency = 5700,
            bonus_currency = 0,
            double_currency_id = 6,
            icon = "6.0",
            id = 2006,
            perform = 0,
            product_id = "com.f2.areaf2.xh50usd.gp",
            reward = {
            },
        },
        [3001] = {
            allow_double_currency = 1,
            base_currency = 100,
            bonus_currency = 0,
            double_currency_id = 1,
            icon = "1.0",
            id = 3001,
            perform = 0,
            product_id = "com.f2.areaf2.xh1usd.web",
            reward = {
            },
        },
        [3002] = {
            allow_double_currency = 1,
            base_currency = 310,
            bonus_currency = 0,
            double_currency_id = 2,
            icon = "2.0",
            id = 3002,
            perform = 0,
            product_id = "com.f2.areaf2.xh3usd.web",
            reward = {
            },
        },
        [3003] = {
            allow_double_currency = 1,
            base_currency = 520,
            bonus_currency = 0,
            double_currency_id = 3,
            icon = "3.0",
            id = 3003,
            perform = 0,
            product_id = "com.f2.areaf2.xh5usd.web",
            reward = {
            },
        },
        [3004] = {
            allow_double_currency = 1,
            base_currency = 1280,
            bonus_currency = 0,
            double_currency_id = 4,
            icon = "4.0",
            id = 3004,
            perform = 0,
            product_id = "com.f2.areaf2.xh12usd.web",
            reward = {
            },
        },
        [3005] = {
            allow_double_currency = 1,
            base_currency = 2700,
            bonus_currency = 0,
            double_currency_id = 5,
            icon = "5.0",
            id = 3005,
            perform = 0,
            product_id = "com.f2.areaf2.xh25usd.web",
            reward = {
            },
        },
        [3006] = {
            allow_double_currency = 1,
            base_currency = 5700,
            bonus_currency = 0,
            double_currency_id = 6,
            icon = "6.0",
            id = 3006,
            perform = 0,
            product_id = "com.f2.areaf2.xh50usd.web",
            reward = {
            },
        },
        [4000] = {
            allow_double_currency = 0,
            base_currency = 0,
            bonus_currency = 0,
            double_currency_id = 0,
            icon = "",
            id = 4000,
            perform = 1,
            product_id = "com.f2.areaf2.yk2usd.ios",
            reward = {
                "50091-1",
            },
        },
        [4001] = {
            allow_double_currency = 0,
            base_currency = 100,
            bonus_currency = 0,
            double_currency_id = 0,
            icon = "",
            id = 4001,
            perform = 1,
            product_id = "com.f2.areaf2.yk8usd.ios",
            reward = {
                "50133-1",
            },
        },
        [5000] = {
            allow_double_currency = 0,
            base_currency = 0,
            bonus_currency = 0,
            double_currency_id = 0,
            icon = "",
            id = 5000,
            perform = 1,
            product_id = "com.f2.areaf2.yk2usd.gp",
            reward = {
                "50091-1",
            },
        },
        [5001] = {
            allow_double_currency = 0,
            base_currency = 100,
            bonus_currency = 0,
            double_currency_id = 0,
            icon = "",
            id = 5001,
            perform = 1,
            product_id = "com.f2.areaf2.yk8usd.gp",
            reward = {
                "50133-1",
            },
        },
        [5002] = {
            allow_double_currency = 0,
            base_currency = 0,
            bonus_currency = 0,
            double_currency_id = 0,
            icon = "",
            id = 5002,
            perform = 1,
            product_id = "com.f2.areaf2.ykxh2usd.gp",
            reward = {
                "50091-1",
            },
        },
        [5003] = {
            allow_double_currency = 0,
            base_currency = 100,
            bonus_currency = 0,
            double_currency_id = 0,
            icon = "",
            id = 5003,
            perform = 1,
            product_id = "com.f2.areaf2.ykxh8usd.gp",
            reward = {
                "50133-1",
            },
        },
        [6000] = {
            allow_double_currency = 0,
            base_currency = 0,
            bonus_currency = 0,
            double_currency_id = 0,
            icon = "",
            id = 6000,
            perform = 1,
            product_id = "com.f2.areaf2.yk2usd.web",
            reward = {
                "50091-1",
            },
        },
        [6001] = {
            allow_double_currency = 0,
            base_currency = 100,
            bonus_currency = 0,
            double_currency_id = 0,
            icon = "",
            id = 6001,
            perform = 1,
            product_id = "com.f2.areaf2.yk8usd.web",
            reward = {
                "50133-1",
            },
        },
    },
}