return{
    skill = {
        [2] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 0,
            id = 2,
            index = 2,
            init_number = 999,
            name = "救人",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "intonate_skill.asset",
            type = 0,
        },
        [6] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 6,
            index = 6,
            init_number = 0,
            name = "拆弹器",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [7] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 7,
            index = 7,
            init_number = -1,
            name = "拆弹器",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 3.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [101] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 101.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 101,
            index = 101,
            init_number = 3,
            name = "龙鳞板",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [102] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 102.0,
            desc = "放置内有防弹护甲的补给包供队伍使用，防弹护甲可以降低受到的伤害",
            desc_lang_index = 12500,
            energy_id = 0,
            icon = "ui_2d_fangdanhujiaban",
            icon_3d = "ui_3d_fangdanhujiaban",
            icon_position = 1,
            id = 102,
            index = 102,
            init_number = 1,
            name = "防弹护甲板",
            name_lang_index = 12000,
            related_skill = {
                1021,
            },
            related_skill_target = {
                7,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [103] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 103.0,
            desc = "在窗户和门框上布置触发后会爆炸的陷阱",
            desc_lang_index = 12501,
            energy_id = 0,
            icon = "ui_2d_banlei",
            icon_3d = "ui_3d_banlei",
            icon_position = 1,
            id = 103,
            index = 103,
            init_number = 5,
            name = "绊雷",
            name_lang_index = 12001,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "trap_bomb_skill.asset",
            type = 0,
        },
        [104] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 104.0,
            desc = "部署附有防弹护盾的机枪提供强大的火力支援",
            desc_lang_index = 12502,
            energy_id = 0,
            icon = "ui_2d_jiashejiqiang",
            icon_3d = "ui_3d_mountedlmg",
            icon_position = 1,
            id = 104,
            index = 104,
            init_number = 1,
            name = "架设机枪",
            name_lang_index = 12002,
            related_skill = {
                1041,
            },
            related_skill_target = {
                7,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [105] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 105.0,
            desc = "投掷可以将金属道具通电的电子装置，并对任何接触到的物体造成伤害",
            desc_lang_index = 12503,
            energy_id = 0,
            icon = "ui_2d_fangdianzhuangzhi",
            icon_3d = "ui_3d_fangdianzhuangzhi",
            icon_position = 1,
            id = 105,
            index = 105,
            init_number = 4,
            name = "放电装置",
            name_lang_index = 12003,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 50.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [106] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 106.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 106,
            index = 106,
            init_number = 2,
            name = "黑镜",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [107] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 107.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 107,
            index = 107,
            init_number = 3,
            name = "全息投影",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [108] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 108.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 108,
            index = 108,
            init_number = 2,
            name = "静音装置",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [109] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 109,
            index = 20005,
            init_number = -1,
            name = "泡沫喷枪",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 50.0,
            script_config_path = "",
            type = 1,
        },
        [110] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 110.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 110,
            index = 110,
            init_number = 5,
            name = "标记陷阱",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [111] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 111,
            index = 111,
            init_number = 3,
            name = "液氮冲击雷",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [112] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "毒素陷阱会将释放有毒气体，使敌人逐渐失去生命值",
            desc_lang_index = 12504,
            energy_id = 0,
            icon = "ui_2d_dusuxianjing",
            icon_3d = "ui_3d_dusuxianjing",
            icon_position = 1,
            id = 112,
            index = 112,
            init_number = 5,
            name = "毒素陷阱",
            name_lang_index = 12004,
            related_skill = {
                1121,
            },
            related_skill_target = {
                4,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [113] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 113.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 113,
            index = 113,
            init_number = 4,
            name = "震动感知器",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [114] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 114.0,
            desc = "放置干扰敌方无人机和其他电子设备的装置",
            desc_lang_index = 12505,
            energy_id = 0,
            icon = "ui_2d_xinhaoganraoqi",
            icon_3d = "ui_3d_xinhaoganraoqi",
            icon_position = 1,
            id = 114,
            index = 114,
            init_number = 4,
            name = "信号干扰器",
            name_lang_index = 12005,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [115] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 115,
            index = 115,
            init_number = 4,
            name = "心跳探测器",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [116] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 116,
            index = 20008,
            init_number = -1,
            name = "治疗手枪",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 9999.0,
            script_config_path = "",
            type = 1,
        },
        [117] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "投掷可以粘附在物体上的毒气烟雾弹，引爆后释放出大范围有毒烟雾。干员佩戴防毒面具，毒雾中可确保自身安全",
            desc_lang_index = 12506,
            energy_id = 0,
            icon = "ui_2d_duqiyanwudan",
            icon_3d = "ui_3d_duqiyanwudan",
            icon_position = 1,
            id = 117,
            index = 117,
            init_number = 3,
            name = "毒气烟雾弹",
            name_lang_index = 12006,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [118] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 118.0,
            desc = "放置在水平地面或墙面的磁力防御装置，可以吸附球形范围内的金属类爆炸物并摧毁它们。",
            desc_lang_index = 12525,
            energy_id = 0,
            icon = "ui_2d_ads",
            icon_3d = "ui_3d_ads",
            icon_position = 1,
            id = 118,
            index = 118,
            init_number = 3,
            name = "主动防御系统",
            name_lang_index = 12025,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [119] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 119.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 119,
            index = 119,
            init_number = 3,
            name = "迎宾踏垫",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [120] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 120,
            index = 120,
            init_number = 3,
            name = "黑眼摄像头",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [121] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 121,
            index = 121,
            init_number = 2,
            name = "妖怪无人机",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [122] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 122.0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 122,
            index = 122,
            init_number = -1,
            name = "视频干扰器",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [123] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 123.0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 123,
            index = 123,
            init_number = 0,
            name = "蛊雷",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [124] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 124.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 124,
            index = 124,
            init_number = 2,
            name = "激光摄像头",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [125] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "投掷可以粘附在物体上的生命感知装置，可以感知一定范围内的生命体",
            desc_lang_index = 12522,
            energy_id = 0,
            icon = "ui_2d_zhendong",
            icon_3d = "ui_3d_zhendong",
            icon_position = 1,
            id = 125,
            index = 125,
            init_number = 3,
            name = "生命感知装置",
            name_lang_index = 12022,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [192] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 193.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 192,
            index = 193,
            init_number = 1,
            name = "强化铁板",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [193] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 193.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 193,
            index = 193,
            init_number = 2,
            name = "强化铁板",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [194] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 194.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 194,
            index = 194,
            init_number = -1,
            name = "封阻板",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [195] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 195.0,
            desc = "带有倒刺的铁丝网，来犯者踩上后会减速",
            desc_lang_index = 12507,
            energy_id = 0,
            icon = "ui_2d_tiesiwang",
            icon_3d = "ui_3d_tiesiwang",
            icon_position = 1,
            id = 195,
            index = 195,
            init_number = 2,
            name = "倒刺铁丝网",
            name_lang_index = 12007,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [196] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 196.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 196,
            index = 196,
            init_number = 1,
            name = "防弹摄像头",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [197] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 197.0,
            desc = "约为人蹲下高度的可部署掩体，能抵挡所有武器的伤害",
            desc_lang_index = 12508,
            energy_id = 0,
            icon = "ui_2d_jidonghudun",
            icon_3d = "ui_3d_jidonghudun",
            icon_position = 1,
            id = 197,
            index = 197,
            init_number = 1,
            name = "折叠护盾",
            name_lang_index = 12008,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [198] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "受到冲击才会引爆的手榴弹",
            desc_lang_index = 12509,
            energy_id = 0,
            icon = "ui_2d_chongjishoulei",
            icon_3d = "ui_3d_chongjishoulei",
            icon_position = 1,
            id = 198,
            index = 198,
            init_number = 2,
            name = "冲击手雷",
            name_lang_index = 12009,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [199] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "可以远程引爆的炸药",
            desc_lang_index = 12510,
            energy_id = 0,
            icon = "ui_2d_yaokongzhayao",
            icon_3d = "ui_3d_yaokongzhayao",
            icon_position = 1,
            id = 199,
            index = 199,
            init_number = 1,
            name = "遥控炸弹",
            name_lang_index = 12010,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [200] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 200,
            index = 200,
            init_number = 0,
            name = "手机遥控",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "pad_skill.asset",
            type = 2,
        },
        [201] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "使用破墙槌来突破可以破坏的表面和已经加固的墙面",
            desc_lang_index = 12511,
            energy_id = 0,
            icon = "ui_2d_poqiangchui",
            icon_3d = "ui_3d_poqiangchui",
            icon_position = 1,
            id = 201,
            index = 20001,
            init_number = 15,
            name = "破墙槌",
            name_lang_index = 12011,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 1,
        },
        [202] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "发射一枚爆破箭头粘附在目标表面并自动引爆",
            desc_lang_index = 12512,
            energy_id = 0,
            icon = "ui_2d_baoponu",
            icon_3d = "ui_3d_baoponu",
            icon_position = 1,
            id = 202,
            index = 20002,
            init_number = 3,
            name = "爆破弩",
            name_lang_index = 12012,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 9999.0,
            script_config_path = "bombgun_skill.asset",
            type = 1,
        },
        [203] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 203.0,
            desc = "设置热切炸药来破坏已经加固的墙面和活动地板",
            desc_lang_index = 12513,
            energy_id = 0,
            icon = "ui_2d_reqiezhayao",
            icon_3d = "ui_3d_reqiezhayao",
            icon_position = 1,
            id = 203,
            index = 203,
            init_number = 2,
            name = "热切炸药",
            name_lang_index = 12013,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [204] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 204,
            index = 204,
            init_number = 2,
            name = "电击无人机",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [205] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "站立时可以伸展盾牌以获得全身防护",
            desc_lang_index = 12514,
            energy_id = 0,
            icon = "ui_2d_shensuohudun",
            icon_3d = "ui_3d_shensuohudun",
            icon_position = 1,
            id = 205,
            index = 10083,
            init_number = -1,
            name = "伸缩护盾",
            name_lang_index = 12014,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 2,
        },
        [206] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "切换到放大瞄准镜，远距离轻松打击敌人",
            desc_lang_index = 12515,
            energy_id = 0,
            icon = "ui_2d_zhediemiaozhunjing",
            icon_3d = "ui_3d_zhediemiaozhunjing",
            icon_position = 1,
            id = 206,
            index = 10052,
            init_number = -1,
            name = "折叠瞄准镜",
            name_lang_index = 12015,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "switch_sniper_sight_skill.asset",
            type = 2,
        },
        [207] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 207.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 207,
            index = 207,
            init_number = 3,
            name = "霰射炸药",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [208] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 15.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 208,
            index = 208,
            init_number = 3,
            name = "卫星扫描",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [209] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 209.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 209,
            index = 209,
            init_number = 3,
            name = "便携工程梯",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [210] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "操控两台追踪无人机发射特殊的追踪弹来定位被击中的敌人",
            desc_lang_index = 12516,
            energy_id = 0,
            icon = "ui_2d_zhuizongwurenji",
            icon_3d = "ui_3d_zhuizongwurenji",
            icon_position = 1,
            id = 210,
            index = 210,
            init_number = 2,
            name = "追踪无人机",
            name_lang_index = 12016,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [211] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 211,
            index = 211,
            init_number = 3,
            name = "燃烧瓶",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [212] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 212,
            index = 212,
            init_number = 3,
            name = "电磁侦查手雷",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [213] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 213,
            index = 213,
            init_number = -1,
            name = "液氮发射器",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 9999.0,
            script_config_path = "",
            type = 1,
        },
        [214] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "投掷EMP手雷，可以使摄像头失效，并且摧毁敌方电子设备",
            desc_lang_index = 12517,
            energy_id = 0,
            icon = "ui_2d_diancimaichongshoulei",
            icon_3d = "ui_3d_diancimaichongshoulei",
            icon_position = 1,
            id = 214,
            index = 214,
            init_number = 3,
            name = "EMP",
            name_lang_index = 12017,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [215] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 215,
            index = 215,
            init_number = 2,
            name = "步枪盾牌",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [216] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 10.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 216,
            index = 216,
            init_number = 3,
            name = "肾上腺素",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [217] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 2,
            cooldown_time = 7.0,
            deployment_id = 0,
            desc = "使用安装在盾牌上的闪光装置，可以使前方锥形范围内的敌人致盲。",
            desc_lang_index = 12524,
            energy_id = 0,
            icon = "ui_2d_shanguangdun",
            icon_3d = "ui_3d_shanguangdun",
            icon_position = 1,
            id = 217,
            index = 10082,
            init_number = 4,
            name = "闪光护盾",
            name_lang_index = 12024,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [218] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 218,
            index = 218,
            init_number = -1,
            name = "电子侦测器",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [219] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 219,
            index = 0,
            init_number = -1,
            name = "霰弹枪管",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [220] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 220,
            index = 220,
            init_number = 2,
            name = "逻辑爆弹",
            name_lang_index = 0,
            related_skill = {
                2201,
                2202,
            },
            related_skill_target = {
                4,
                1,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [221] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 28.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 221,
            index = 221,
            init_number = 2,
            name = "动作侦测",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [222] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 222,
            index = 20011,
            init_number = -1,
            name = "爆破弩丸",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 9999.0,
            script_config_path = "",
            type = 1,
        },
        [223] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 223,
            index = 223,
            init_number = -1,
            name = "足迹追踪器",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [224] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 224,
            index = 224,
            init_number = 3,
            name = "烛光弹",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "",
            type = 3,
        },
        [225] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 225.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 225.0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 225,
            index = 225,
            init_number = 3,
            name = "战术侦查镜",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [226] = {
            active_time = 14.0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 16.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 12523,
            energy_id = 0,
            icon = "ui_2d_jisu",
            icon_3d = "ui_3d_jisu",
            icon_position = 1,
            id = 226,
            index = 226,
            init_number = 3,
            name = "强化激素",
            name_lang_index = 12023,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 2,
        },
        [293] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 293,
            index = 293,
            init_number = 2,
            name = "无人侦查机",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [294] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 294,
            index = 294,
            init_number = -1,
            name = "锚钩枪",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [295] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 295.0,
            desc = "可安放在可破坏表面的炸药，能炸毁墙面、地板和封阻门窗",
            desc_lang_index = 12518,
            energy_id = 0,
            icon = "ui_2d_baopozhayao",
            icon_3d = "ui_3d_baopozhayao",
            icon_position = 1,
            id = 295,
            index = 295,
            init_number = 2,
            name = "爆破炸药",
            name_lang_index = 12018,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 0,
        },
        [296] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 296.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 296,
            index = 296,
            init_number = 1,
            name = "人员杀伤地雷",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
        [297] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "会产生烟雾并阻挡视线的手榴弹",
            desc_lang_index = 12519,
            energy_id = 0,
            icon = "ui_2d_yanwushouliudan",
            icon_3d = "ui_3d_yanwushouliudan",
            icon_position = 1,
            id = 297,
            index = 297,
            init_number = 2,
            name = "烟雾弹",
            name_lang_index = 12019,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [298] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "产生非致命的爆炸波，能使附近人员眩盲",
            desc_lang_index = 12520,
            energy_id = 0,
            icon = "ui_2d_shanguangshoulei",
            icon_3d = "ui_3d_shanguangshoulei",
            icon_position = 1,
            id = 298,
            index = 298,
            init_number = 3,
            name = "闪光弹",
            name_lang_index = 12020,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [299] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "拉开插销后不久就会爆炸的破片型手榴弹",
            desc_lang_index = 12521,
            energy_id = 0,
            icon = "ui_2d_popianshouliudan",
            icon_3d = "ui_3d_popianshouliudan",
            icon_position = 1,
            id = 299,
            index = 299,
            init_number = 2,
            name = "手雷",
            name_lang_index = 12021,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "tool_skill.asset",
            type = 3,
        },
        [300] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 1,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "近战",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 300,
            index = 300,
            init_number = -1,
            name = "近战",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [301] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 301,
            index = 0,
            init_number = -1,
            name = "锚钩枪",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 200.0,
            script_config_path = "throwrope_skill.asset",
            type = 0,
        },
        [1021] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "ui_2d_fangdanhujiaban",
            icon_3d = "ui_3d_fangdanhujiaban",
            icon_position = 2,
            id = 1021,
            index = 1021,
            init_number = -1,
            name = "防弹护甲板",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "tool_skill.asset",
            type = 4,
        },
        [1041] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 0,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 1041.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "ui_2d_jiashejiqiang",
            icon_3d = "",
            icon_position = 2,
            id = 1041,
            index = 1041,
            init_number = 1,
            name = "架设机枪",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "mounted_lmg_skill.asset",
            type = 4,
        },
        [1121] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 2,
            id = 1121,
            index = 1121,
            init_number = 999,
            name = "毒素陷阱",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "remove neurotoxin skill.asset",
            type = 2,
        },
        [2201] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 2201,
            index = 2201,
            init_number = -1,
            name = "解除蜂鸣",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 2,
        },
        [2202] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 2,
            id = 2202,
            index = 2202,
            init_number = -1,
            name = "入侵手机",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 4,
        },
        [2241] = {
            active_time = 0,
            allow_infinite_item = 0,
            allow_reset_item = 1,
            button_type = 0,
            cooldown_time = 0.0,
            deployment_id = 2241.0,
            desc = "",
            desc_lang_index = 0,
            energy_id = 0,
            icon = "",
            icon_3d = "",
            icon_position = 1,
            id = 2241,
            index = 224,
            init_number = 3,
            name = "烛光弹",
            name_lang_index = 0,
            related_skill = {
                0,
            },
            related_skill_target = {
                0,
            },
            safe_distance = 5.0,
            script_config_path = "",
            type = 0,
        },
    },
}