return{
    task = {
        [200000] = {
            activation = 10,
            growth_type = 0,
            id = 200000,
            name1 = 302700,
            param1 = 90000,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                100,
                0,
                0,
                0,
            },
        },
        [200001] = {
            activation = 10,
            growth_type = 0,
            id = 200001,
            name1 = 302701,
            param1 = 90001,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200002] = {
            activation = 10,
            growth_type = 0,
            id = 200002,
            name1 = 302702,
            param1 = 90002,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200003] = {
            activation = 10,
            growth_type = 0,
            id = 200003,
            name1 = 302703,
            param1 = 90003,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200004] = {
            activation = 10,
            growth_type = 1,
            id = 200004,
            name1 = 302704,
            param1 = 90004,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200005] = {
            activation = 10,
            growth_type = 0,
            id = 200005,
            name1 = 302705,
            param1 = 90005,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200006] = {
            activation = 10,
            growth_type = 0,
            id = 200006,
            name1 = 302706,
            param1 = 90006,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200007] = {
            activation = 10,
            growth_type = 0,
            id = 200007,
            name1 = 302707,
            param1 = 90007,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200008] = {
            activation = 10,
            growth_type = 0,
            id = 200008,
            name1 = 302708,
            param1 = 90008,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200009] = {
            activation = 10,
            growth_type = 0,
            id = 200009,
            name1 = 302709,
            param1 = 90009,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200010] = {
            activation = 10,
            growth_type = 1,
            id = 200010,
            name1 = 302710,
            param1 = 90010,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200011] = {
            activation = 10,
            growth_type = 0,
            id = 200011,
            name1 = 302711,
            param1 = 90011,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200012] = {
            activation = 10,
            growth_type = 0,
            id = 200012,
            name1 = 302712,
            param1 = 90012,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200013] = {
            activation = 10,
            growth_type = 0,
            id = 200013,
            name1 = 302713,
            param1 = 90013,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [200014] = {
            activation = 10,
            growth_type = 1,
            id = 200014,
            name1 = 302714,
            param1 = 90014,
            param2 = 0,
            param3 = 0,
            type = 1,
            unlock_condition = 0,
            weight_slot = {
                0,
                100,
                100,
                100,
            },
        },
        [210000] = {
            activation = 0,
            growth_type = 0,
            id = 210000,
            name1 = 0,
            param1 = 95000,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 1,
            weight_slot = {
            },
        },
        [210001] = {
            activation = 0,
            growth_type = 0,
            id = 210001,
            name1 = 0,
            param1 = 95001,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 2,
            weight_slot = {
            },
        },
        [210002] = {
            activation = 0,
            growth_type = 0,
            id = 210002,
            name1 = 0,
            param1 = 95002,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 3,
            weight_slot = {
            },
        },
        [210003] = {
            activation = 0,
            growth_type = 0,
            id = 210003,
            name1 = 0,
            param1 = 95003,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 4,
            weight_slot = {
            },
        },
        [210004] = {
            activation = 0,
            growth_type = 0,
            id = 210004,
            name1 = 0,
            param1 = 95004,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 5,
            weight_slot = {
            },
        },
        [210005] = {
            activation = 0,
            growth_type = 0,
            id = 210005,
            name1 = 0,
            param1 = 95005,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 6,
            weight_slot = {
            },
        },
        [210006] = {
            activation = 0,
            growth_type = 0,
            id = 210006,
            name1 = 0,
            param1 = 95006,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 7,
            weight_slot = {
            },
        },
        [210007] = {
            activation = 0,
            growth_type = 0,
            id = 210007,
            name1 = 0,
            param1 = 95007,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 8,
            weight_slot = {
            },
        },
        [210008] = {
            activation = 0,
            growth_type = 0,
            id = 210008,
            name1 = 0,
            param1 = 95008,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 9,
            weight_slot = {
            },
        },
        [210009] = {
            activation = 0,
            growth_type = 0,
            id = 210009,
            name1 = 0,
            param1 = 95009,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 10,
            weight_slot = {
            },
        },
        [210010] = {
            activation = 0,
            growth_type = 0,
            id = 210010,
            name1 = 0,
            param1 = 95010,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 11,
            weight_slot = {
            },
        },
        [210011] = {
            activation = 0,
            growth_type = 0,
            id = 210011,
            name1 = 0,
            param1 = 95011,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 12,
            weight_slot = {
            },
        },
        [210012] = {
            activation = 0,
            growth_type = 0,
            id = 210012,
            name1 = 0,
            param1 = 95012,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 13,
            weight_slot = {
            },
        },
        [210013] = {
            activation = 0,
            growth_type = 0,
            id = 210013,
            name1 = 0,
            param1 = 95013,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 14,
            weight_slot = {
            },
        },
        [210014] = {
            activation = 0,
            growth_type = 0,
            id = 210014,
            name1 = 0,
            param1 = 95014,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 15,
            weight_slot = {
            },
        },
        [210015] = {
            activation = 0,
            growth_type = 0,
            id = 210015,
            name1 = 0,
            param1 = 95015,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 16,
            weight_slot = {
            },
        },
        [210016] = {
            activation = 0,
            growth_type = 0,
            id = 210016,
            name1 = 0,
            param1 = 95016,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 17,
            weight_slot = {
            },
        },
        [210017] = {
            activation = 0,
            growth_type = 0,
            id = 210017,
            name1 = 0,
            param1 = 95017,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 18,
            weight_slot = {
            },
        },
        [210018] = {
            activation = 0,
            growth_type = 0,
            id = 210018,
            name1 = 0,
            param1 = 95018,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 19,
            weight_slot = {
            },
        },
        [210019] = {
            activation = 0,
            growth_type = 0,
            id = 210019,
            name1 = 0,
            param1 = 95019,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 20,
            weight_slot = {
            },
        },
        [210020] = {
            activation = 0,
            growth_type = 0,
            id = 210020,
            name1 = 0,
            param1 = 95020,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 21,
            weight_slot = {
            },
        },
        [210021] = {
            activation = 0,
            growth_type = 0,
            id = 210021,
            name1 = 0,
            param1 = 95021,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 22,
            weight_slot = {
            },
        },
        [210022] = {
            activation = 0,
            growth_type = 0,
            id = 210022,
            name1 = 0,
            param1 = 95022,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 23,
            weight_slot = {
            },
        },
        [210023] = {
            activation = 0,
            growth_type = 0,
            id = 210023,
            name1 = 0,
            param1 = 95023,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 24,
            weight_slot = {
            },
        },
        [210024] = {
            activation = 0,
            growth_type = 0,
            id = 210024,
            name1 = 0,
            param1 = 95024,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 25,
            weight_slot = {
            },
        },
        [210025] = {
            activation = 0,
            growth_type = 0,
            id = 210025,
            name1 = 0,
            param1 = 95025,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 26,
            weight_slot = {
            },
        },
        [210026] = {
            activation = 0,
            growth_type = 0,
            id = 210026,
            name1 = 0,
            param1 = 95026,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 27,
            weight_slot = {
            },
        },
        [210027] = {
            activation = 0,
            growth_type = 0,
            id = 210027,
            name1 = 0,
            param1 = 95027,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 28,
            weight_slot = {
            },
        },
        [210028] = {
            activation = 0,
            growth_type = 0,
            id = 210028,
            name1 = 0,
            param1 = 95028,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 29,
            weight_slot = {
            },
        },
        [210029] = {
            activation = 0,
            growth_type = 0,
            id = 210029,
            name1 = 0,
            param1 = 95029,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 30,
            weight_slot = {
            },
        },
        [210030] = {
            activation = 0,
            growth_type = 0,
            id = 210030,
            name1 = 0,
            param1 = 95030,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 31,
            weight_slot = {
            },
        },
        [210031] = {
            activation = 0,
            growth_type = 0,
            id = 210031,
            name1 = 0,
            param1 = 95031,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 32,
            weight_slot = {
            },
        },
        [210032] = {
            activation = 0,
            growth_type = 0,
            id = 210032,
            name1 = 0,
            param1 = 95032,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 33,
            weight_slot = {
            },
        },
        [210033] = {
            activation = 0,
            growth_type = 0,
            id = 210033,
            name1 = 0,
            param1 = 95033,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 34,
            weight_slot = {
            },
        },
        [210034] = {
            activation = 0,
            growth_type = 0,
            id = 210034,
            name1 = 0,
            param1 = 95034,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 35,
            weight_slot = {
            },
        },
        [210035] = {
            activation = 0,
            growth_type = 0,
            id = 210035,
            name1 = 0,
            param1 = 95035,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 36,
            weight_slot = {
            },
        },
        [210036] = {
            activation = 0,
            growth_type = 0,
            id = 210036,
            name1 = 0,
            param1 = 95036,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 37,
            weight_slot = {
            },
        },
        [210037] = {
            activation = 0,
            growth_type = 0,
            id = 210037,
            name1 = 0,
            param1 = 95037,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 38,
            weight_slot = {
            },
        },
        [210038] = {
            activation = 0,
            growth_type = 0,
            id = 210038,
            name1 = 0,
            param1 = 95038,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 39,
            weight_slot = {
            },
        },
        [210039] = {
            activation = 0,
            growth_type = 0,
            id = 210039,
            name1 = 0,
            param1 = 95039,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 40,
            weight_slot = {
            },
        },
        [210040] = {
            activation = 0,
            growth_type = 0,
            id = 210040,
            name1 = 0,
            param1 = 95040,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 41,
            weight_slot = {
            },
        },
        [210041] = {
            activation = 0,
            growth_type = 0,
            id = 210041,
            name1 = 0,
            param1 = 95041,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 42,
            weight_slot = {
            },
        },
        [210042] = {
            activation = 0,
            growth_type = 0,
            id = 210042,
            name1 = 0,
            param1 = 95042,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 43,
            weight_slot = {
            },
        },
        [210043] = {
            activation = 0,
            growth_type = 0,
            id = 210043,
            name1 = 0,
            param1 = 95043,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 44,
            weight_slot = {
            },
        },
        [210044] = {
            activation = 0,
            growth_type = 0,
            id = 210044,
            name1 = 0,
            param1 = 95044,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 45,
            weight_slot = {
            },
        },
        [210045] = {
            activation = 0,
            growth_type = 0,
            id = 210045,
            name1 = 0,
            param1 = 95045,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 46,
            weight_slot = {
            },
        },
        [210046] = {
            activation = 0,
            growth_type = 0,
            id = 210046,
            name1 = 0,
            param1 = 95046,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 47,
            weight_slot = {
            },
        },
        [210047] = {
            activation = 0,
            growth_type = 0,
            id = 210047,
            name1 = 0,
            param1 = 95047,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 48,
            weight_slot = {
            },
        },
        [210048] = {
            activation = 0,
            growth_type = 0,
            id = 210048,
            name1 = 0,
            param1 = 95048,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 49,
            weight_slot = {
            },
        },
        [210049] = {
            activation = 0,
            growth_type = 0,
            id = 210049,
            name1 = 0,
            param1 = 95049,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 50,
            weight_slot = {
            },
        },
        [210050] = {
            activation = 0,
            growth_type = 0,
            id = 210050,
            name1 = 0,
            param1 = 95050,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 51,
            weight_slot = {
            },
        },
        [210051] = {
            activation = 0,
            growth_type = 0,
            id = 210051,
            name1 = 0,
            param1 = 95051,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 52,
            weight_slot = {
            },
        },
        [210052] = {
            activation = 0,
            growth_type = 0,
            id = 210052,
            name1 = 0,
            param1 = 95052,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 53,
            weight_slot = {
            },
        },
        [210053] = {
            activation = 0,
            growth_type = 0,
            id = 210053,
            name1 = 0,
            param1 = 95053,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 54,
            weight_slot = {
            },
        },
        [210054] = {
            activation = 0,
            growth_type = 0,
            id = 210054,
            name1 = 0,
            param1 = 95054,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 55,
            weight_slot = {
            },
        },
        [210055] = {
            activation = 0,
            growth_type = 0,
            id = 210055,
            name1 = 0,
            param1 = 95055,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 56,
            weight_slot = {
            },
        },
        [210056] = {
            activation = 0,
            growth_type = 0,
            id = 210056,
            name1 = 0,
            param1 = 95056,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 57,
            weight_slot = {
            },
        },
        [210057] = {
            activation = 0,
            growth_type = 0,
            id = 210057,
            name1 = 0,
            param1 = 95057,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 58,
            weight_slot = {
            },
        },
        [210058] = {
            activation = 0,
            growth_type = 0,
            id = 210058,
            name1 = 0,
            param1 = 95058,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 59,
            weight_slot = {
            },
        },
        [210059] = {
            activation = 0,
            growth_type = 0,
            id = 210059,
            name1 = 0,
            param1 = 95059,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 60,
            weight_slot = {
            },
        },
        [215000] = {
            activation = 0,
            growth_type = 1,
            id = 215000,
            name1 = 0,
            param1 = 91000,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 1,
            weight_slot = {
            },
        },
        [215001] = {
            activation = 0,
            growth_type = 1,
            id = 215001,
            name1 = 0,
            param1 = 91001,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 2,
            weight_slot = {
            },
        },
        [215002] = {
            activation = 0,
            growth_type = 1,
            id = 215002,
            name1 = 0,
            param1 = 91002,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 3,
            weight_slot = {
            },
        },
        [215003] = {
            activation = 0,
            growth_type = 1,
            id = 215003,
            name1 = 0,
            param1 = 91003,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 4,
            weight_slot = {
            },
        },
        [215004] = {
            activation = 0,
            growth_type = 1,
            id = 215004,
            name1 = 0,
            param1 = 91004,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 5,
            weight_slot = {
            },
        },
        [215005] = {
            activation = 0,
            growth_type = 1,
            id = 215005,
            name1 = 0,
            param1 = 91005,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 6,
            weight_slot = {
            },
        },
        [215006] = {
            activation = 0,
            growth_type = 1,
            id = 215006,
            name1 = 0,
            param1 = 91006,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 7,
            weight_slot = {
            },
        },
        [215007] = {
            activation = 0,
            growth_type = 1,
            id = 215007,
            name1 = 0,
            param1 = 91007,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 8,
            weight_slot = {
            },
        },
        [215008] = {
            activation = 0,
            growth_type = 1,
            id = 215008,
            name1 = 0,
            param1 = 91008,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 9,
            weight_slot = {
            },
        },
        [215009] = {
            activation = 0,
            growth_type = 1,
            id = 215009,
            name1 = 0,
            param1 = 91009,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 10,
            weight_slot = {
            },
        },
        [215010] = {
            activation = 0,
            growth_type = 1,
            id = 215010,
            name1 = 0,
            param1 = 91010,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 11,
            weight_slot = {
            },
        },
        [215011] = {
            activation = 0,
            growth_type = 1,
            id = 215011,
            name1 = 0,
            param1 = 91011,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 12,
            weight_slot = {
            },
        },
        [215012] = {
            activation = 0,
            growth_type = 1,
            id = 215012,
            name1 = 0,
            param1 = 91012,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 13,
            weight_slot = {
            },
        },
        [215013] = {
            activation = 0,
            growth_type = 1,
            id = 215013,
            name1 = 0,
            param1 = 91013,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 14,
            weight_slot = {
            },
        },
        [215014] = {
            activation = 0,
            growth_type = 1,
            id = 215014,
            name1 = 0,
            param1 = 91014,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 15,
            weight_slot = {
            },
        },
        [215015] = {
            activation = 0,
            growth_type = 1,
            id = 215015,
            name1 = 0,
            param1 = 91015,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 16,
            weight_slot = {
            },
        },
        [215016] = {
            activation = 0,
            growth_type = 1,
            id = 215016,
            name1 = 0,
            param1 = 91016,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 17,
            weight_slot = {
            },
        },
        [215017] = {
            activation = 0,
            growth_type = 1,
            id = 215017,
            name1 = 0,
            param1 = 91017,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 18,
            weight_slot = {
            },
        },
        [215018] = {
            activation = 0,
            growth_type = 1,
            id = 215018,
            name1 = 0,
            param1 = 91018,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 19,
            weight_slot = {
            },
        },
        [215019] = {
            activation = 0,
            growth_type = 1,
            id = 215019,
            name1 = 0,
            param1 = 91019,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 20,
            weight_slot = {
            },
        },
        [215020] = {
            activation = 0,
            growth_type = 1,
            id = 215020,
            name1 = 0,
            param1 = 91020,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 21,
            weight_slot = {
            },
        },
        [215021] = {
            activation = 0,
            growth_type = 1,
            id = 215021,
            name1 = 0,
            param1 = 91021,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 22,
            weight_slot = {
            },
        },
        [215022] = {
            activation = 0,
            growth_type = 1,
            id = 215022,
            name1 = 0,
            param1 = 91022,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 23,
            weight_slot = {
            },
        },
        [215023] = {
            activation = 0,
            growth_type = 1,
            id = 215023,
            name1 = 0,
            param1 = 91023,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 24,
            weight_slot = {
            },
        },
        [215024] = {
            activation = 0,
            growth_type = 1,
            id = 215024,
            name1 = 0,
            param1 = 91024,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 25,
            weight_slot = {
            },
        },
        [215025] = {
            activation = 0,
            growth_type = 1,
            id = 215025,
            name1 = 0,
            param1 = 91025,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 26,
            weight_slot = {
            },
        },
        [215026] = {
            activation = 0,
            growth_type = 1,
            id = 215026,
            name1 = 0,
            param1 = 91026,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 27,
            weight_slot = {
            },
        },
        [215027] = {
            activation = 0,
            growth_type = 1,
            id = 215027,
            name1 = 0,
            param1 = 91027,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 28,
            weight_slot = {
            },
        },
        [215028] = {
            activation = 0,
            growth_type = 1,
            id = 215028,
            name1 = 0,
            param1 = 91028,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 29,
            weight_slot = {
            },
        },
        [215029] = {
            activation = 0,
            growth_type = 1,
            id = 215029,
            name1 = 0,
            param1 = 91029,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 30,
            weight_slot = {
            },
        },
        [215030] = {
            activation = 0,
            growth_type = 1,
            id = 215030,
            name1 = 0,
            param1 = 91030,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 31,
            weight_slot = {
            },
        },
        [215031] = {
            activation = 0,
            growth_type = 1,
            id = 215031,
            name1 = 0,
            param1 = 91031,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 32,
            weight_slot = {
            },
        },
        [215032] = {
            activation = 0,
            growth_type = 1,
            id = 215032,
            name1 = 0,
            param1 = 91032,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 33,
            weight_slot = {
            },
        },
        [215033] = {
            activation = 0,
            growth_type = 1,
            id = 215033,
            name1 = 0,
            param1 = 91033,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 34,
            weight_slot = {
            },
        },
        [215034] = {
            activation = 0,
            growth_type = 1,
            id = 215034,
            name1 = 0,
            param1 = 91034,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 35,
            weight_slot = {
            },
        },
        [215035] = {
            activation = 0,
            growth_type = 1,
            id = 215035,
            name1 = 0,
            param1 = 91035,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 36,
            weight_slot = {
            },
        },
        [215036] = {
            activation = 0,
            growth_type = 1,
            id = 215036,
            name1 = 0,
            param1 = 91036,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 37,
            weight_slot = {
            },
        },
        [215037] = {
            activation = 0,
            growth_type = 1,
            id = 215037,
            name1 = 0,
            param1 = 91037,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 38,
            weight_slot = {
            },
        },
        [215038] = {
            activation = 0,
            growth_type = 1,
            id = 215038,
            name1 = 0,
            param1 = 91038,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 39,
            weight_slot = {
            },
        },
        [215039] = {
            activation = 0,
            growth_type = 1,
            id = 215039,
            name1 = 0,
            param1 = 91039,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 40,
            weight_slot = {
            },
        },
        [215040] = {
            activation = 0,
            growth_type = 1,
            id = 215040,
            name1 = 0,
            param1 = 91040,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 41,
            weight_slot = {
            },
        },
        [215041] = {
            activation = 0,
            growth_type = 1,
            id = 215041,
            name1 = 0,
            param1 = 91041,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 42,
            weight_slot = {
            },
        },
        [215042] = {
            activation = 0,
            growth_type = 1,
            id = 215042,
            name1 = 0,
            param1 = 91042,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 43,
            weight_slot = {
            },
        },
        [215043] = {
            activation = 0,
            growth_type = 1,
            id = 215043,
            name1 = 0,
            param1 = 91043,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 44,
            weight_slot = {
            },
        },
        [215044] = {
            activation = 0,
            growth_type = 1,
            id = 215044,
            name1 = 0,
            param1 = 91044,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 45,
            weight_slot = {
            },
        },
        [215045] = {
            activation = 0,
            growth_type = 1,
            id = 215045,
            name1 = 0,
            param1 = 91045,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 46,
            weight_slot = {
            },
        },
        [215046] = {
            activation = 0,
            growth_type = 1,
            id = 215046,
            name1 = 0,
            param1 = 91046,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 47,
            weight_slot = {
            },
        },
        [215047] = {
            activation = 0,
            growth_type = 1,
            id = 215047,
            name1 = 0,
            param1 = 91047,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 48,
            weight_slot = {
            },
        },
        [215048] = {
            activation = 0,
            growth_type = 1,
            id = 215048,
            name1 = 0,
            param1 = 91048,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 49,
            weight_slot = {
            },
        },
        [215049] = {
            activation = 0,
            growth_type = 1,
            id = 215049,
            name1 = 0,
            param1 = 91049,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 50,
            weight_slot = {
            },
        },
        [215050] = {
            activation = 0,
            growth_type = 1,
            id = 215050,
            name1 = 0,
            param1 = 91050,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 51,
            weight_slot = {
            },
        },
        [215051] = {
            activation = 0,
            growth_type = 1,
            id = 215051,
            name1 = 0,
            param1 = 91051,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 52,
            weight_slot = {
            },
        },
        [215052] = {
            activation = 0,
            growth_type = 1,
            id = 215052,
            name1 = 0,
            param1 = 91052,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 53,
            weight_slot = {
            },
        },
        [215053] = {
            activation = 0,
            growth_type = 1,
            id = 215053,
            name1 = 0,
            param1 = 91053,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 54,
            weight_slot = {
            },
        },
        [215054] = {
            activation = 0,
            growth_type = 1,
            id = 215054,
            name1 = 0,
            param1 = 91054,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 55,
            weight_slot = {
            },
        },
        [215055] = {
            activation = 0,
            growth_type = 1,
            id = 215055,
            name1 = 0,
            param1 = 91055,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 56,
            weight_slot = {
            },
        },
        [215056] = {
            activation = 0,
            growth_type = 1,
            id = 215056,
            name1 = 0,
            param1 = 91056,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 57,
            weight_slot = {
            },
        },
        [215057] = {
            activation = 0,
            growth_type = 1,
            id = 215057,
            name1 = 0,
            param1 = 91057,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 58,
            weight_slot = {
            },
        },
        [215058] = {
            activation = 0,
            growth_type = 1,
            id = 215058,
            name1 = 0,
            param1 = 91058,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 59,
            weight_slot = {
            },
        },
        [215059] = {
            activation = 0,
            growth_type = 1,
            id = 215059,
            name1 = 0,
            param1 = 91059,
            param2 = 0,
            param3 = 0,
            type = 3,
            unlock_condition = 60,
            weight_slot = {
            },
        },
        [220000] = {
            activation = 0,
            growth_type = 0,
            id = 220000,
            name1 = 0,
            param1 = 50000,
            param2 = 0,
            param3 = 0,
            type = 2,
            unlock_condition = 0,
            weight_slot = {
            },
        },
        [220001] = {
            activation = 0,
            growth_type = 0,
            id = 220001,
            name1 = 0,
            param1 = 50001,
            param2 = 0,
            param3 = 0,
            type = 2,
            unlock_condition = 0,
            weight_slot = {
            },
        },
        [220002] = {
            activation = 0,
            growth_type = 0,
            id = 220002,
            name1 = 0,
            param1 = 50002,
            param2 = 0,
            param3 = 0,
            type = 2,
            unlock_condition = 0,
            weight_slot = {
            },
        },
    },
    task_refresh = {
        {
            id = 1,
            max_refresh_cnt = 3,
            repeat_type = 1,
            slot_cnt = 4,
            type = 1,
        },
        {
            id = 2,
            max_refresh_cnt = 0,
            repeat_type = 2,
            slot_cnt = 0,
            type = 2,
        },
        {
            id = 3,
            max_refresh_cnt = 0,
            repeat_type = 0,
            slot_cnt = 0,
            type = 3,
        },
    },
}