return{
    warehouse = {
        [1] = {
            belong = 0,
            id = 1,
            level = 1,
            lock_state = 0,
            name_lang_index = 65003,
        },
        [2] = {
            belong = 0,
            id = 2,
            level = 1,
            lock_state = 0,
            name_lang_index = 65004,
        },
        [3] = {
            belong = 0,
            id = 3,
            level = 1,
            lock_state = 0,
            name_lang_index = 65005,
        },
        [4] = {
            belong = 0,
            id = 4,
            level = 1,
            lock_state = 1,
            name_lang_index = 65006,
        },
        [5] = {
            belong = 0,
            id = 5,
            level = 1,
            lock_state = 0,
            name_lang_index = 65007,
        },
        [11] = {
            belong = 1,
            id = 11,
            level = 2,
            lock_state = 0,
            name_lang_index = 65008,
        },
        [12] = {
            belong = 1,
            id = 12,
            level = 2,
            lock_state = 0,
            name_lang_index = 65009,
        },
        [21] = {
            belong = 2,
            id = 21,
            level = 2,
            lock_state = 0,
            name_lang_index = 65010,
        },
        [22] = {
            belong = 2,
            id = 22,
            level = 2,
            lock_state = 0,
            name_lang_index = 65011,
        },
        [23] = {
            belong = 2,
            id = 23,
            level = 2,
            lock_state = 0,
            name_lang_index = 65012,
        },
        [31] = {
            belong = 3,
            id = 31,
            level = 2,
            lock_state = 0,
            name_lang_index = 65013,
        },
        [32] = {
            belong = 3,
            id = 32,
            level = 2,
            lock_state = 0,
            name_lang_index = 65014,
        },
        [41] = {
            belong = 4,
            id = 41,
            level = 2,
            lock_state = 1,
            name_lang_index = 65015,
        },
        [42] = {
            belong = 4,
            id = 42,
            level = 2,
            lock_state = 1,
            name_lang_index = 65016,
        },
        [51] = {
            belong = 5,
            id = 51,
            level = 2,
            lock_state = 0,
            name_lang_index = 65013,
        },
        [52] = {
            belong = 5,
            id = 52,
            level = 2,
            lock_state = 0,
            name_lang_index = 65014,
        },
        [311] = {
            belong = 3,
            id = 311,
            level = 2,
            lock_state = 0,
            name_lang_index = 65013,
        },
        [321] = {
            belong = 3,
            id = 321,
            level = 2,
            lock_state = 0,
            name_lang_index = 65014,
        },
        [411] = {
            belong = 4,
            id = 411,
            level = 2,
            lock_state = 1,
            name_lang_index = 65015,
        },
        [421] = {
            belong = 4,
            id = 421,
            level = 2,
            lock_state = 1,
            name_lang_index = 65016,
        },
        [511] = {
            belong = 5,
            id = 511,
            level = 2,
            lock_state = 0,
            name_lang_index = 65013,
        },
        [521] = {
            belong = 5,
            id = 521,
            level = 2,
            lock_state = 0,
            name_lang_index = 65014,
        },
    },
}