---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/8/21 10:26
---

TableData = {}

local extra = require("Configs/TableData/extra")

for tableName, fileName in pairs(extra) do
    local table = require("Configs/TableData/" .. tableName);
    for sheetName, sheetRecord in pairs(table) do
        if TableData[sheetName] then
            Debug.LogError("Duplicate table config name: " .. sheetName)
        else
            TableData[sheetName] = sheetRecord
        end
    end
end

function GetLuaTableData(tableName)
    if TableData ~= nil then
        local t = TableData[tableName] 
        return t
    end
    return nil
end

function GetLuaTableDataRecordFieldValue(tableName, id, fieldName)
    if TableData ~= nil then
        local t = TableData[tableName] 
        if t ~= nil then
            local record = t[id]
            if record ~= nil then
                return record[fieldName]
            end
        end
    end
    return nil
end