---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ming.wmm.
--- DateTime: 2019/11/29 20:12
---

require "lib/class"

Event = class("Event")
local this = Event

function this:ctor() 
    self.listeners = {}
end

function this:AddListener(func)
    self.listeners[func] = true
end

function this:RemoveListener(func)
    self.listeners[func] = nil
end

function this:Invoke(...)
    for f, _ in pairs(self.listeners) do
        f(...)
    end
end

function this:RemoveAllListeners()
    self.listeners = {}
end

function this:Destroy()
    self.listeners = nil
end
